### 508p

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import font_manager, rc

In [3]:
inf = pd.read_excel("04_시군구별 제4권-부산 대구 울산 경북 경남_2019년 .xlsx",sheet_name='82p')


# 1. 3번 행을 칼럼명으로 변경
inf.columns = inf.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf = inf.drop(index=[0, 1, 2, 3, 4, 5, 6, 7])

# 3. 46, 47, 48번 행 삭제
inf = inf.drop(index=[46, 47])

# 인덱스 리셋
inf = inf.reset_index(drop=True)

inf.iloc[:, [2, 3]] = inf.iloc[:, [3, 2]].values
inf.iloc[:, [6, 7]] = inf.iloc[:, [7, 6]].values

inf = inf.loc[:, ~inf.columns.isna()]

inf = inf.drop(columns = ["G. & T.", "Division"])

inf.columns = [col.split('\n')[0] for col in inf.columns]
inf.columns = [col.split('  C.E')[0] for col in inf.columns]
inf.columns = [col.split('  S.E.')[0] for col in inf.columns]
inf.columns = [col.split('    Medical Aid')[0] for col in inf.columns]

# 창원시 관련 행 필터링 및 합계 계산
changwon_gu = ["포항시남구               ", "포항시북구               "]
changwon_data = inf[inf['구  분'].isin(changwon_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
changwon_row = pd.DataFrame([['포항시'] + changwon_data.tolist()], columns=inf.columns)

# 창원시 행 추가 및 기존 구 삭제
inf = pd.concat([inf[~inf['구  분'].isin(changwon_gu)], changwon_row], ignore_index=True)
inf = inf.rename(columns={'구  분': '지역'})

inf['지역'] = inf['지역'] + ' ' + inf.groupby('지역').cumcount().replace(0, '').astype(str)

# inf.columns = ['구  분', '진료실인원수(관외)', '입내원일수(관외)', '요양급여일수(관외)', '진료비(관외)', '급여비(관외)']
inf

                         지역     의료보장    근 로 자     공ㆍ교     지 역 의료급여 1종 의료급여 2종
0                       부산   3429267  2125381  230757  934462  101047   37620
1    중구                        42345    21852    1509   16226    1983     775
2    서구                       107856    62140    5533   33464    5187    1532
3    동구                        88115    50011    3843   27412    4944    1905
4     영도구                     116454    66798    5622   34807    7118    2109
5      부산진구                   356727   217754   21885  103523    9763    3802
6     동래구                     271371   168810   25222   70368    5053    1918
7    남구                       275015   171414   22056   73914    5683    1948
8    북구                       292005   185446   19669   71711   10745    4434
9      해운대구                   408798   254343   32926  107541   10226    3762
10    사하구                     323039   209646   14811   83646   10787    4149
11     금정구                    239553   145469   20144   65052    6537    2351
12    강서구                     135578    93145    8585   31359    1960     529
13    연제구                     209399   129234   18167   55003    4886    2109
14    수영구                     176267   103812   13741   53219    3816    1679
15    사상구                     220114   140782    8875   59306    8121    3030
16    기장군                     166631   104725    8169   47911    4238    1588
17                      대구   2455068  1504281  206656  647162   68444   28525
18  중구                    1    77312    43242    6441   24282    2533     814
19  동구                    1   345923   203787   32695   94414   11218    3809
20  서구                    1   175637   102443    6949   56039    7058    3148
21  남구                    1   147387    79272    8750   49035    7242    3088
22  북구                    1   440189   276542   33851  116601    9737    3458
23    수성구                     431193   258391   57125  100825    9895    4957
24    달서구                     575180   366198   44938  141482   15656    6906
25    달성군                     262247   174406   15907   64484    5105    2345
26                      울산   1167115   818137   59380  269958   15053    4587
27  중구                    2   225184   150891   11990   57649    3519    1135
28  남구                    2   327789   223816   20306   78259    4225    1183
29  동구                    2   162342   121560    4374   33815    1932     661
30  북구                    2   220646   169473    8877   39485    1924     887
31    울주군                     231154   152397   13833   60750    3453     721
32                      경북   2701537  1601614  237179  767803   74330   20611
33  경주시                       264385   161906   19017   74947    6686    1829
34  김천시                       142603    85082   13790   38255    4390    1086
35  안동시                       161005    86210   22322   44806    5883    1784
36                     포항시    510469   318621   41097  133341   13072    4338

In [4]:
inf2 = pd.read_excel("04_시군구별 제4권-부산 대구 울산 경북 경남_2019년 .xlsx",sheet_name='84p')


# 1. 3번 행을 칼럼명으로 변경
inf2.columns = inf2.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf2 = inf2.drop(index=[0, 1, 2, 3, 4, 5, 6, 7])

# 3. 46, 47, 48번 행 삭제
inf2 = inf2.drop(index=[50, 51])

# 인덱스 리셋
inf2 = inf2.reset_index(drop=True)

inf2.iloc[:, [2, 3]] = inf2.iloc[:, [3, 2]].values
inf2.iloc[:, [6, 7]] = inf2.iloc[:, [7, 6]].values

inf2 = inf2.loc[:, ~inf2.columns.isna()]

inf2 = inf2.drop(columns = ["G. & T.", "Division"])

inf2.columns = [col.split('\n')[0] for col in inf2.columns]
inf2.columns = [col.split('  C.E')[0] for col in inf2.columns]
inf2.columns = [col.split('  S.E.')[0] for col in inf2.columns]
inf2.columns = [col.split('    Medical Aid')[0] for col in inf2.columns]

# 창원시 관련 행 필터링 및 합계 계산
changwon_gu = ["창원시 의창구", "창원시 성산구", "창원시 마산합포구", "창원시 마산회원구", "창원시 진해구"]
changwon_data = inf2[inf2['구  분'].isin(changwon_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
changwon_row = pd.DataFrame([['창원시'] + changwon_data.tolist()], columns=inf2.columns)

# 창원시 행 추가 및 기존 구 삭제
inf2 = pd.concat([inf2[~inf2['구  분'].isin(changwon_gu)], changwon_row], ignore_index=True)

inf2 = inf2.rename(columns={'구  분': '지역'})

# inf2.columns = ['구  분', '진료실인원수(관외)', '입내원일수(관외)', '요양급여일수(관외)', '진료비(관외)', '급여비(관외)']
inf2

                        지역     의료보장    근 로 자     공ㆍ교     지 역 의료급여 1종 의료급여 2종
0   구미시                      423616   288523   21421  106224    5321    2127
1   영주시                      105790    57664   11622   31203    3932    1369
2   영천시                      105010    58763    9784   31191    4214    1058
3   상주시                      101076    52379   11931   32965    3161     640
4   문경시                       72762    38131    9223   22535    2318     555
5   경산시                      267194   162459   21833   74914    5966    2022
6   군위군                       24208    12952    2656    7587     827     186
7   의성군                       52887    27022    6053   17237    2244     331
8   청송군                       25508    11806    3538    9058     904     202
9   영양군                       17026     7559    2644    5794     743     286
10  영덕군                       37798    17424    3326   14965    1810     273
11  청도군                       43566    22991    4517   14140    1658     260
12  고령군                       34175    19035    2947   10728    1238     227
13  성주군                       45397    23425    4033   16034    1655     250
14  칠곡군                      119644    75700    5328   35056    2718     842
15  예천군                       55381    27280    9998   16046    1666     391
16  봉화군                       32258    16242    3652   10932    1147     285
17  울진군                       50156    27031    4216   16077    2586     246
18  울릉군                        9623     3409    2231    3768     191      24
19                      경남  3421417  2108532  285196  933611   73262   20816
20                     진주시   351049   204723   42882   92712    7807    2925
21                     통영시   133639    67868    9710   50826    3941    1294
22                     사천시   114124    66864    9813   33133    3574     740
23                     김해시   559701   369867   33095  142881   10077    3781
24                     밀양시   107398    58502    9878   34344    3666    1008
25                     거제시   254105   175214   10731   64533    2999     628
26                     양산시   356315   232561   19879   95187    6507    2181
27                     의령군    27892    14785    3233    8486    1210     178
28                     함안군    68629    41086    5823   19536    1815     369
29                     창녕군    64551    35716    5161   21117    2113     444
30                     고성군    53146    28179    4385   18309    1898     375
31                     남해군    44102    22096    4234   15951    1496     325
32                     하동군    46905    23107    4929   16743    1762     364
33                     산청군    35779    17905    3917   12372    1322     263
34                     함양군    40029    20680    4534   13107    1458     250
35                     거창군    62560    33444    7042   19460    1981     633
36                     합천군    45432    23416    5445   14429    1800     342
37                     창원시  1056061   672519  100505  260485   17836    4716

In [5]:
inf3 = pd.read_excel("04_시군구별 제4권-부산 대구 울산 경북 경남_2019년 .xlsx",sheet_name='86p')


# 1. 3번 행을 칼럼명으로 변경
inf3.columns = inf3.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf3 = inf3.drop(index=[0, 1, 2, 3, 4, 5, 6, 7])

# 3. 46, 47, 48번 행 삭제
inf3 = inf3.drop(index=[46, 47])

# 인덱스 리셋
inf3 = inf3.reset_index(drop=True)

inf3 = inf3.drop(columns = [ "Division"])

inf3.columns = [col.split('\n')[0] for col in inf3.columns]

## 창원시 관련 행 필터링 및 합계 계산
changwon_gu = ["포항시남구               ", "포항시북구               "]
changwon_data = inf3[inf3['구  분'].isin(changwon_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
changwon_row = pd.DataFrame([['포항시'] + changwon_data.tolist()], columns=inf3.columns)


# 창원시 행 추가 및 기존 구 삭제
inf3 = pd.concat([inf3[~inf3['구  분'].isin(changwon_gu)], changwon_row], ignore_index=True)



inf3 = inf3.rename(columns={'구  분': '지역'})

inf3['지역'] = inf3['지역'] + ' ' + inf3.groupby('지역').cumcount().replace(0, '').astype(str)

# inf3.columns = ['구  분', '진료실인원수(관외)', '입내원일수(관외)', '요양급여일수(관외)', '진료비(관외)', '급여비(관외)']
inf3

,지역,계,0-4세,5-9세,10-14세,15-19세,20-24세,25-29세,30-34세,35-39세,40-44세,45-49세,50-54세,55-59세,60-64세,65-69세,70-74세,75-79세,80세 이상
0,부산,3429267,108345,135614,128377,155022,214691,228658,197674,247412,241338,279773,281871,302825,294610,212043,158423,123228,119363
1,중구,42345,668,880,920,1378,2509,3222,2491,2578,2564,3272,3466,3856,4285,3302,2618,2177,2159
2,서구,107856,2477,3298,3250,4296,6880,7006,5375,6626,6473,8281,8455,9874,10149,8002,6447,5437,5530
3,동구,88115,1953,2236,2223,3151,4766,5825,4962,5558,5375,6750,7006,7887,8610,6768,5519,4823,4703
4,영도구,116454,2424,3340,3419,4599,6421,6325,5245,6622,7031,8939,9478,11047,12031,9303,7758,6423,6049
5,부산진구,356727,10195,12187,11554,14603,23593,27883,22933,25546,23999,28133,28339,31140,30833,22236,16854,13716,12983
6,동래구,271371,8525,11466,11688,13796,16712,16971,15039,19225,19994,23270,22520,23079,22725,16707,12087,9095,8472
7,남구,275015,8305,11296,11057,13212,18490,17466,14410,18964,19972,23521,21960,22432,22715,17233,13482,10778,9722
8,북구,292005,9408,11079,11084,14151,19696,20198,16371,19399,19241,23338,27065,29491,25830,16904,11520,8781,8449
9,해운대구,408798,12494,17297,18061,21831,25641,24980,21323,28251,30623,37709,36023,35822,32773,22493,16773,13143,13561
10,사하구,323039,9717,12311,11974,15244,21130,21373,18310,23072,21958,26194,27456,30119,28682,20188,14500,10614,10197
11,금정구,239553,6069,8156,8219,10803,17562,17034,12617,15007,15039,18515,20079,22539,21781,15787,11866,9239,9241
12,강서구,135578,9583,9906,6055,4427,5469,8264,11910,17192,12462,9397,8050,8955,8838,5777,3724,2725,2844
13,연제구,209399,7128,8348,7751,9264,12588,13870,12635,15779,15022,17091,16934,17737,17775,13126,9799,7551,7001
14,수영구,176267,5014,5566,5395,6954,10594,13649,11439,12978,11861,13760,13275,14604,15739,11868,9477,7012,7082
15,사상구,220114,6245,7550,7065,9231,14610,16173,13107,14956,14064,16793,20215,23154,20757,14023,9502,6686,5983
16,기장군,166631,8140,10698,8662,8082,8030,8419,9507,15659,15660,14810,11550,11089,11087,8326,6497,5028,5387
17,대구,2455068,83202,105790,106744,130665,165808,163361,139883,172873,179903,216652,218052,212802,182503,126800,92514,76645,80871
18,중구 1,77312,2739,2812,2292,2940,5154,6581,5326,6017,5141,5872,5640,5867,5722,4342,3824,3420,3623
19,동구 1,345923,12507,14624,12935,14891,20301,22277,20603,25695,24974,27469,28066,29839,28243,20905,15989,13225,13380
20,서구 1,175637,3693,4705,4856,7145,11045,12102,9006,10059,10399,13783,16744,18735,16998,12714,9115,7495,7043
21,남구 1,147387,3294,3990,4242,5793,9489,10703,8433,9473,9223,11694,12193,13139,13202,10049,7918,6916,7636
22,북구 1,440189,15853,19660,20105,25414,31909,29271,25110,31056,33187,41475,40083,37200,30035,20175,14752,12516,12388
23,수성구,431193,11470,19538,24381,29710,31163,25607,18847,25998,32862,43128,40375,35382,29486,20470,15136,12805,14835
24,달서구,575180,18519,25059,25938,33057,42295,40239,32729,39287,42155,52097,54243,52142,41862,27335,18363,14490,15370
25,달성군,262247,15127,15402,11995,11715,14452,16581,19829,25288,21962,21134,20708,20498,16955,10810,7417,5778,6596
26,울산,1167115,46941,58180,55121,61923,76248,77056,72126,92973,90224,104027,110248,105108,84348,51705,33017,23831,24039
27,중구 2,225184,7761,10352,9747,11471,14406,14522,12466,16372,16335,19568,21452,21512,18332,11946,7825,5765,5352
28,남구 2,327789,11128,13927,14319,18203,23678,23901,20377,23986,23571,30491,32912,30651,24316,14943,9247,6332,5807
29,동구 2,162342,7159,9145,7910,7983,9375,9825,10938,15103,13325,12893,12948,14365,13246,7895,4731,2852,2649
30,북구 2,220646,12296,13998,12165,11718,14362,14780,15397,20960,19403,19037,20696,17899,11450,6243,3988,2960,3294
31,울주군,231154,8597,10758,10980,12548,14427,14028,12948,16552,17590,22038,22240,20681,17004,10678,7226,5922,6937
32,경북,2701537,90073,111212,108184,127934,157702,149272,141353,178791,180149,216292,228717,240717,223576,164424,122118,115083,145940
33,경주시,264385,7628,9754,10040,12236,15553,14714,13252,16458,17086,22341,23740,24471,22569,16663,12604,11298,13978
34,김천시,142603,5119,5866,5481,6759,8151,7602,7179,9253,9072,10746,11707,12487,11993,9022,6851,6484,8831
35,안동시,161005,5048,6182,6419,7772,9363,8028,7199,9307,10400,12548,13037,14238,13713,10655,8234,8350,10512
36,포항시,510469,18120,23874,22541,26011,30835,28516,26837,36621,36025,43213,45116,47072,43987,30025,19891,15450,16335

In [6]:
inf4 = pd.read_excel("04_시군구별 제4권-부산 대구 울산 경북 경남_2019년 .xlsx",sheet_name='88p')


# 1. 3번 행을 칼럼명으로 변경
inf4.columns = inf4.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf4 = inf4.drop(index=[0, 1, 2, 3, 4, 5, 6, 7])

# 3. 46, 47, 48번 행 삭제
inf4 = inf4.drop(index=[50, 51])

# 인덱스 리셋
inf4 = inf4.reset_index(drop=True)

inf4 = inf4.drop(columns = [ "Division"])

inf4.columns = [col.split('\n')[0] for col in inf4.columns]

# 창원시 관련 행 필터링 및 합계 계산
changwon_gu = ["창원시 의창구", "창원시 성산구", "창원시 마산합포구", "창원시 마산회원구", "창원시 진해구"]
changwon_data = inf4[inf4['구  분'].isin(changwon_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
changwon_row = pd.DataFrame([['창원시'] + changwon_data.tolist()], columns=inf4.columns)


# 창원시 행 추가 및 기존 구 삭제
inf4 = pd.concat([inf4[~inf4['구  분'].isin(changwon_gu)], changwon_row], ignore_index=True)


inf4 = inf4.rename(columns={'구  분': '지역'})
# inf4.columns = ['구  분', '진료실인원수(관외)', '입내원일수(관외)', '요양급여일수(관외)', '진료비(관외)', '급여비(관외)']
inf4

,지역,계,0-4세,5-9세,10-14세,15-19세,20-24세,25-29세,30-34세,35-39세,40-44세,45-49세,50-54세,55-59세,60-64세,65-69세,70-74세,75-79세,80세 이상
0,구미시,423616,19472,24159,22101,24743,29277,30449,31372,38280,35859,38259,36925,32404,22779,13301,8343,7105,8788
1,영주시,105790,2685,3922,4242,5140,5886,4479,3973,5473,6398,8077,8842,9693,9802,7942,5838,5875,7523
2,영천시,105010,2939,3042,3103,3899,6105,5559,4998,5796,5771,7607,8885,9844,9932,7985,6185,6016,7344
3,상주시,101076,2386,3072,3580,4634,5281,4117,3681,4617,5196,7069,8058,9729,10003,7675,6318,6400,9260
4,문경시,72762,1804,2386,2539,3425,3808,2778,2715,3632,4008,5079,5650,6868,7294,5691,4538,4614,5933
5,경산시,267194,10053,11849,10668,12803,18591,18570,16402,19911,19305,23003,22719,22146,19200,13585,10084,8684,9621
6,군위군,24208,352,395,439,577,968,936,834,856,976,1338,1991,2588,2806,2323,1953,2065,2811
7,의성군,52887,1083,941,1092,1362,1851,1768,1707,1911,2107,2855,3964,5265,6067,5283,4221,4764,6646
8,청송군,25508,492,560,561,737,986,953,837,1010,1027,1488,2155,2713,2902,2394,1954,2108,2631
9,영양군,17026,388,409,457,567,645,607,521,628,733,1116,1346,1709,1834,1458,1261,1491,1856
10,영덕군,37798,883,967,1008,1230,1483,1456,1233,1698,1756,2406,2918,3541,3851,3276,2764,3284,4044
11,청도군,43566,703,893,1047,1371,1777,1721,1398,1812,1922,2717,3252,4467,4983,4352,3269,3160,4722
12,고령군,34175,778,871,1001,1189,1746,1696,1544,1740,1771,2507,2844,3441,3371,2746,2060,2032,2838
13,성주군,45397,1064,961,1098,1397,2074,2308,1940,2023,2187,2940,3906,5100,4923,3981,2973,2721,3801
14,칠곡군,119644,4620,5900,5705,6286,6911,7018,7712,9941,10048,11063,10141,9290,7646,5142,3874,3622,4725
15,예천군,55381,2131,2495,2242,2099,2196,2104,2418,3314,3493,3496,3751,4472,4852,4072,3262,3629,5355
16,봉화군,32258,732,801,837,1144,1243,1035,950,1263,1461,1955,2667,3359,3653,2806,2278,2540,3534
17,울진군,50156,1396,1646,1738,2274,2548,2340,2216,2670,2936,3688,4141,4792,4401,3305,2808,2952,4305
18,울릉군,9623,197,267,245,279,424,518,435,577,612,781,962,1028,1015,742,555,439,547
19,경남,3421417,124391,162662,157637,177082,209000,197973,190443,253890,254317,297369,298150,294146,257534,174677,128644,110037,133465
20,진주시,351049,12659,17006,16833,19390,24106,21873,19422,24458,25437,30273,29676,28851,25255,17682,13546,11372,13210
21,통영시,133639,4114,6739,6503,6619,6911,6007,6384,10118,10391,11554,11269,11981,11264,7943,5944,4851,5047
22,사천시,114124,3663,5141,5168,5354,5953,5959,5627,7946,8505,9719,9311,9472,8938,6701,5618,4876,6173
23,김해시,559701,22849,29892,30004,33527,38587,35918,33863,45329,46584,55597,52010,44597,33425,20374,13978,11275,11892
24,밀양시,107398,2625,3334,3720,4444,5796,5104,4427,5549,5923,7450,8839,10565,11323,8584,6428,5803,7484
25,거제시,254105,12541,16448,14017,14368,14241,12643,16807,25529,23442,24765,21092,17948,15344,9021,5860,4545,5494
26,양산시,356315,16862,19639,16818,17643,20982,21961,22695,31534,29656,31397,30292,28298,23986,15727,10996,8918,8911
27,의령군,27892,524,639,699,942,1215,1187,1037,1152,1310,1754,2170,2709,2867,2258,1905,2177,3347
28,함안군,68629,1881,2788,3043,3163,3544,3471,3322,4164,4625,5428,5676,6060,6129,4393,3332,3268,4342
29,창녕군,64551,1677,1982,1890,2411,3076,3041,2892,3402,3336,4244,5178,6361,6684,4959,3991,4045,5382
30,고성군,53146,1071,1832,1870,2310,2408,2050,1958,2761,2909,3946,4348,5068,5076,4162,3519,3249,4609
31,남해군,44102,668,1012,1278,1887,2080,1531,1254,1570,1894,2911,3376,4299,4379,3608,3415,3440,5500
32,하동군,46905,912,1199,1405,1724,2267,1827,1461,1731,2229,3361,4095,4832,4773,3731,3189,3255,4914
33,산청군,35779,710,814,1020,1174,1522,1305,1126,1362,1439,2272,3094,3725,3805,3022,2552,2764,4073
34,함양군,40029,798,1148,1398,1727,1945,1519,1248,1665,1897,2805,3375,3811,3900,2982,2693,2886,4232
35,거창군,62560,1580,2416,2608,3288,3710,2579,2347,3075,3462,4609,5220,5607,5495,4092,3542,3603,5327
36,합천군,45432,710,1006,1181,1479,1985,1532,1332,1637,1858,2744,3588,4557,4689,3899,3450,3954,5831
37,창원시,1056061,38547,49627,48182,55632,68672,68466,63241,80908,79420,92540,95541,95405,80202,51539,34686,25756,27697

In [7]:
inf5 = pd.read_excel("04_시군구별 제4권-부산 대구 울산 경북 경남_2019년 .xlsx",sheet_name='98p심평원')


# 1. 3번 행을 칼럼명으로 변경
inf5.columns = inf5.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf5 = inf5.drop(index=[0, 1, 2, 3, 4])

# 3. 46, 47, 48번 행 삭제
inf5 = inf5.drop(index=[43, 44, 45])

# 인덱스 리셋
inf5 = inf5.reset_index(drop=True)


inf5.columns = [col.split('\n')[0] for col in inf5.columns]

inf5 = inf5.drop(columns = [ "조  산  원", "Division"])

## 창원시 관련 행 필터링 및 합계 계산
changwon_gu = ["포항시남구               ", "포항시북구               "]
changwon_data = inf5[inf5['구      분'].isin(changwon_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
changwon_row = pd.DataFrame([['포항시'] + changwon_data.tolist()], columns=inf5.columns)


# 창원시 행 추가 및 기존 구 삭제
inf5 = pd.concat([inf5[~inf5['구      분'].isin(changwon_gu)], changwon_row], ignore_index=True)


# 창원시 관련 구 이름
changwon_gu = ['보  건  소', '보건지소','보건진료소', '보건의료원']

# 예시: 'col1', 'col2', 'col3'의 값을 합쳐 'new_col' 생성
inf5['보건소'] = inf5[['보  건  소', '보건지소','보건진료소', '보건의료원']].sum(axis=1)

inf5 = inf5.drop(columns = [  '보  건  소', '보건지소','보건진료소', '보건의료원'])

inf5 = inf5.rename(columns={'구      분': '지역'})

inf5['지역'] = inf5['지역'] + ' ' + inf5.groupby('지역').cumcount().replace(0, '').astype(str)


inf5

,지역,계,상급종합병원,종합병원,병 원,요양병원,의 원,치과병원,치과의원,한방병원,한 의 원,약 국,보건소
0,부산,6752,4,25,142,190,2384,24,1273,10,1136,1530,32
1,중구,182,0,1,1,5,69,0,39,1,25,40,1
2,서구,235,3,1,4,6,60,0,34,1,35,90,1
3,동구,239,0,3,5,6,77,2,34,1,44,66,1
4,영도구,203,0,2,1,5,73,0,31,0,34,56,1
5,부산진구,986,1,3,19,14,429,3,170,1,157,188,1
6,동래구,608,0,3,16,17,184,4,130,0,117,136,1
7,남구,475,0,1,8,8,157,1,99,0,90,110,1
8,북구,465,0,2,11,14,166,3,88,0,77,102,2
9,해운대구,814,0,2,14,18,320,4,160,1,133,159,3
10,사하구,541,0,0,18,25,184,1,100,2,85,125,1
11,금정구,466,0,1,10,22,147,0,96,2,81,106,1
12,강서구,147,0,0,4,0,49,1,27,0,21,37,8
13,연제구,450,0,1,10,16,153,2,89,1,80,96,1
14,수영구,395,0,2,8,11,123,1,78,0,82,88,1
15,사상구,317,0,2,8,18,111,1,58,0,42,76,1
16,기장군,229,0,1,5,5,82,1,40,0,33,55,7
17,대구,5083,5,11,109,69,1803,16,883,3,878,1281,25
18,중구 1,594,1,2,13,3,248,4,109,1,70,142,1
19,동구 1,649,0,1,9,7,236,0,103,0,117,175,1
20,서구 1,374,0,1,8,9,119,0,53,0,70,113,1
21,남구 1,345,2,1,7,10,103,0,56,0,62,103,1
22,북구 1,748,1,1,20,11,250,2,141,0,120,200,2
23,수성구,948,0,1,15,8,346,5,166,2,208,196,1
24,달서구,1064,1,4,31,13,378,5,195,0,172,264,1
25,달성군,361,0,0,6,8,123,0,60,0,59,88,17
26,울산,1801,0,8,43,42,609,4,383,3,275,410,24
27,중구 2,323,0,2,10,5,108,0,67,0,48,82,1
28,남구 2,765,0,3,20,18,271,2,179,2,115,153,2
29,동구 2,242,0,1,1,4,87,1,45,0,36,66,1
30,북구 2,211,0,1,4,4,69,1,48,1,32,48,3
31,울주군,260,0,1,8,11,74,0,44,0,44,61,17
32,경북,4474,0,20,74,117,1292,13,670,6,639,1083,559
33,경주시,407,0,1,10,14,115,2,58,1,68,109,29
34,김천시,212,0,2,1,4,60,0,33,0,24,56,32
35,안동시,290,0,3,5,7,80,2,43,1,42,67,40
36,포항시,877,0,5,14,29,278,1,162,1,127,222,38

In [8]:
inf6 = pd.read_excel("04_시군구별 제4권-부산 대구 울산 경북 경남_2019년 .xlsx",sheet_name='100p')


# 1. 3번 행을 칼럼명으로 변경
inf6.columns = inf6.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf6 = inf6.drop(index=[0, 1, 2, 3, 4])

# 3. 46, 47, 48번 행 삭제
inf6 = inf6.drop(index=[47, 48, 49])

# 인덱스 리셋
inf6 = inf6.reset_index(drop=True)


inf6.columns = [col.split('\n')[0] for col in inf6.columns]

inf6 = inf6.drop(columns = [ "조  산  원", "Division"])

# 창원시 관련 행 필터링 및 합계 계산
changwon_gu = ["창원시 의창구", "창원시 성산구", "창원시 마산합포구", "창원시 마산회원구", "창원시 진해구"]
changwon_data = inf6[inf6['구      분'].isin(changwon_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
changwon_row = pd.DataFrame([['창원시'] + changwon_data.tolist()], columns=inf6.columns)


# 창원시 행 추가 및 기존 구 삭제
inf6 = pd.concat([inf6[~inf6['구      분'].isin(changwon_gu)], changwon_row], ignore_index=True)



# 창원시 관련 구 이름
changwon_gu = ['보  건  소', '보건지소','보건진료소', '보건의료원']

# 예시: 'col1', 'col2', 'col3'의 값을 합쳐 'new_col' 생성
inf6['보건소'] = inf6[['보  건  소', '보건지소','보건진료소', '보건의료원']].sum(axis=1)

inf6 = inf6.drop(columns = [  '보  건  소', '보건지소','보건진료소', '보건의료원'])

inf6 = inf6.rename(columns={'구      분': '지역'})

inf6

,지역,계,상급종합병원,종합병원,병 원,요양병원,의 원,치과병원,치과의원,한방병원,한 의 원,약 국,보건소
0,구미시,616,0,3,8,9,217,5,104,0,92,156,22
1,영주시,191,0,1,6,4,51,0,28,1,30,46,24
2,영천시,192,0,1,2,3,59,1,19,1,35,45,25
3,상주시,186,0,2,1,3,45,0,25,0,25,41,44
4,문경시,147,0,1,2,1,45,0,19,0,18,38,23
5,경산시,427,0,1,4,12,146,2,74,0,63,106,19
6,군위군,41,0,0,0,0,8,0,4,0,4,7,18
7,의성군,108,0,0,5,6,19,0,7,0,10,22,39
8,청송군,55,0,0,1,0,13,0,5,0,8,10,18
9,영양군,24,0,0,1,0,1,0,3,0,2,3,14
10,영덕군,81,0,0,1,2,17,0,9,0,8,22,22
11,청도군,85,0,0,4,5,20,0,9,0,12,16,19
12,고령군,62,0,0,1,2,12,0,8,0,10,11,18
13,성주군,84,0,0,2,5,18,0,9,0,11,18,21
14,칠곡군,151,0,0,3,5,45,0,23,0,18,39,18
15,예천군,97,0,0,1,2,21,0,13,1,13,19,27
16,봉화군,47,0,0,1,1,7,0,4,0,7,10,17
17,울진군,83,0,0,1,2,15,0,10,0,11,18,26
18,울릉군,11,0,0,0,1,0,0,1,0,1,2,6
19,경남,5364,2,24,138,145,1639,20,896,12,802,1271,414
20,진주시,597,1,3,13,10,192,3,107,2,94,147,25
21,통영시,230,0,0,7,4,78,0,34,1,27,57,22
22,사천시,191,0,0,5,7,51,0,35,0,27,46,20
23,김해시,711,0,5,25,35,218,5,130,3,104,176,10
24,밀양시,178,0,0,8,5,44,0,26,1,23,46,25
25,거제시,317,0,3,7,2,102,3,55,0,46,76,23
26,양산시,507,1,2,10,18,174,3,83,2,81,124,9
27,의령군,60,0,0,2,2,11,0,5,0,7,11,22
28,함안군,94,0,0,3,4,22,0,13,0,12,25,15
29,창녕군,129,0,0,4,7,29,0,13,0,15,28,33
30,고성군,89,0,0,3,2,19,0,11,0,12,16,26
31,남해군,88,0,0,1,1,23,0,9,0,9,20,25
32,하동군,94,0,0,3,2,20,0,12,0,9,17,31
33,산청군,72,0,0,0,1,13,0,6,0,13,14,25
34,함양군,83,0,0,1,0,22,0,9,0,10,19,22
35,거창군,127,0,0,2,3,31,0,16,0,13,32,30
36,합천군,96,0,0,3,2,17,0,10,0,14,18,32
37,창원시,1701,0,11,41,40,573,6,322,3,286,399,19

In [9]:
inf7 = pd.read_excel("04_시군구별 제4권-부산 대구 울산 경북 경남_2019년 .xlsx",sheet_name='102p')


# 1. 3번 행을 칼럼명으로 변경
inf7.columns = inf7.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf7 = inf7.drop(index=[0, 1, 2, 3, 4, 5])

# 3. 46, 47, 48번 행 삭제
inf7 = inf7.drop(index=[44, 45, 46])

# 인덱스 리셋
inf7 = inf7.reset_index(drop=True)
inf7 = inf7.loc[:, ~inf7.columns.isna()]

inf7.columns = [col.split('\n')[0] for col in inf7.columns]
inf7.columns = [col.split('physical')[0] for col in inf7.columns]
inf7 = inf7.drop(columns = [ "Division"])

## 창원시 관련 행 필터링 및 합계 계산
changwon_gu = ["포항시남구               ", "포항시북구               "]
changwon_data = inf7[inf7['구   분'].isin(changwon_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
changwon_row = pd.DataFrame([['포항시'] + changwon_data.tolist()], columns=inf7.columns)


# 창원시 행 추가 및 기존 구 삭제
inf7 = pd.concat([inf7[~inf7['구   분'].isin(changwon_gu)], changwon_row], ignore_index=True)


# # 창원시 관련 구 이름
# changwon_gu = ['보  건  소', '보건지소','보건진료소', '보건의료원']

# # 예시: 'col1', 'col2', 'col3'의 값을 합쳐 'new_col' 생성
# inf7['보건소'] = inf7[['보  건  소', '보건지소','보건진료소', '보건의료원']].sum(axis=1)

# inf7 = inf7.drop(columns = [  '보  건  소', '보건지소','보건진료소', '보건의료원'])

inf7 = inf7.rename(columns={'구   분': '지역'})

inf7['지역'] = inf7['지역'] + ' ' + inf7.groupby('지역').cumcount().replace(0, '').astype(str)

inf7

,지역,계,의 사,치 과 의 사,한 의 사,간호사,약 사,물리치료사,작업치료사,사회복지사
0,부산,37028,8008,1757,1691,18514,2795,3237,636,390
1,중구,886,195,52,42,431,69,74,16,7
2,서구,5827,1348,74,57,3844,266,162,45,31
3,동구,1794,353,52,67,980,114,172,41,15
4,영도구,846,172,44,51,383,83,93,11,9
5,부산진구,5240,1346,243,257,2554,368,377,67,28
6,동래구,3029,576,177,155,1501,233,315,44,28
7,남구,1711,359,131,109,711,163,188,26,24
8,북구,2354,452,135,113,1149,183,255,39,28
9,해운대구,4158,931,222,208,1986,310,393,73,35
10,사하구,1967,435,132,131,736,216,248,31,38
11,금정구,1779,332,109,130,739,165,211,46,47
12,강서구,343,92,36,27,102,52,34,0,0
13,연제구,1923,412,114,117,822,169,208,49,32
14,수영구,1975,398,97,109,956,154,190,55,16
15,사상구,2238,397,87,69,1133,152,260,93,47
16,기장군,958,210,52,49,487,98,57,0,5
17,대구,26087,5908,1330,1146,12557,2083,2274,576,213
18,중구 1,3945,1113,302,99,1878,238,240,62,13
19,동구 1,2594,623,128,138,1160,271,214,27,33
20,서구 1,1533,273,60,90,636,155,223,75,21
21,남구 1,4287,971,79,84,2596,216,234,88,19
22,북구 1,3855,702,182,148,1788,316,494,188,37
23,수성구,2927,666,227,289,1043,296,330,56,20
24,달서구,6027,1340,280,212,3164,464,437,76,54
25,달성군,919,220,72,86,292,127,102,4,16
26,울산,8950,1754,504,410,4612,724,731,133,82
27,중구 2,1787,307,74,60,948,149,184,54,11
28,남구 2,3117,672,239,186,1461,272,241,18,28
29,동구 2,2229,455,74,45,1437,118,86,5,9
30,북구 2,869,146,56,45,392,87,110,28,5
31,울주군,948,174,61,74,374,98,110,28,29
32,경북,19165,3662,957,1027,9577,1625,1836,231,250
33,경주시,1788,347,85,101,879,168,172,17,19
34,김천시,931,182,45,41,493,79,71,4,16
35,안동시,1950,338,62,64,1152,109,156,40,29
36,포항시,5123,851,225,211,2944,347,426,62,57

In [10]:
inf8 = pd.read_excel("04_시군구별 제4권-부산 대구 울산 경북 경남_2019년 .xlsx",sheet_name='104p')


# 1. 3번 행을 칼럼명으로 변경
inf8.columns = inf8.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf8 = inf8.drop(index=[0, 1, 2, 3, 4, 5])

# 3. 46, 47, 48번 행 삭제
inf8 = inf8.drop(index=[48,49,50])

# 인덱스 리셋
inf8 = inf8.reset_index(drop=True)
inf8 = inf8.loc[:, ~inf8.columns.isna()]

inf8.columns = [col.split('\n')[0] for col in inf8.columns]
inf8.columns = [col.split('physical')[0] for col in inf8.columns]
inf8 = inf8.drop(columns = [ "Division"])

# 창원시 관련 행 필터링 및 합계 계산
changwon_gu = ["창원시 의창구", "창원시 성산구", "창원시 마산합포구", "창원시 마산회원구", "창원시 진해구"]
changwon_data = inf8[inf8['구   분'].isin(changwon_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
changwon_row = pd.DataFrame([['창원시'] + changwon_data.tolist()], columns=inf8.columns)


# 창원시 행 추가 및 기존 구 삭제
inf8 = pd.concat([inf8[~inf8['구   분'].isin(changwon_gu)], changwon_row], ignore_index=True)


# # 창원시 관련 구 이름
# changwon_gu = ['보  건  소', '보건지소','보건진료소', '보건의료원']

# # 예시: 'col1', 'col2', 'col3'의 값을 합쳐 'new_col' 생성
# inf8['보건소'] = inf8[['보  건  소', '보건지소','보건진료소', '보건의료원']].sum(axis=1)

# inf8 = inf8.drop(columns = [  '보  건  소', '보건지소','보건진료소', '보건의료원'])

inf8 = inf8.rename(columns={'구   분': '지역'})

inf8

,지역,계,의 사,치 과 의 사,한 의 사,간호사,약 사,물리치료사,작업치료사,사회복지사
0,구미시,2733,554,155,123,1325,239,275,44,18
1,영주시,716,139,40,47,297,67,94,15,17
2,영천시,611,132,27,49,254,65,70,0,14
3,상주시,700,124,33,37,363,59,66,12,6
4,문경시,454,103,25,27,201,48,43,1,6
5,경산시,1615,345,111,91,657,169,194,30,18
6,군위군,66,16,6,8,18,7,11,0,0
7,의성군,292,63,13,22,130,30,28,1,5
8,청송군,127,37,7,12,47,13,7,0,4
9,영양군,50,11,5,8,21,3,2,0,0
10,영덕군,179,40,13,16,64,25,19,0,2
11,청도군,297,57,12,32,113,29,44,0,10
12,고령군,146,28,11,20,57,16,11,0,3
13,성주군,255,52,13,22,106,27,29,0,6
14,칠곡군,406,92,30,29,149,56,37,0,13
15,예천군,308,56,17,24,124,27,51,5,4
16,봉화군,135,24,8,15,58,15,13,0,2
17,울진군,228,53,12,24,98,24,16,0,1
18,울릉군,55,18,2,4,27,3,1,0,0
19,경남,27744,5532,1370,1257,13972,2132,2669,524,288
20,진주시,4146,880,151,133,2400,257,264,40,21
21,통영시,828,168,42,38,348,88,129,6,9
22,사천시,714,140,39,43,315,71,76,14,16
23,김해시,3611,672,195,181,1652,321,448,92,50
24,밀양시,549,122,37,34,215,68,62,3,8
25,거제시,1454,244,86,64,750,118,157,24,11
26,양산시,4003,832,249,168,2162,232,263,55,42
27,의령군,151,30,6,14,61,16,20,0,4
28,함안군,352,67,17,20,139,36,50,15,8
29,창녕군,446,92,18,33,208,43,41,1,10
30,고성군,284,62,14,23,124,25,32,0,4
31,남해군,168,44,12,16,45,23,27,0,1
32,하동군,224,46,16,16,90,25,28,0,3
33,산청군,129,33,11,19,42,14,9,0,1
34,함양군,161,45,12,12,50,21,21,0,0
35,거창군,367,78,20,21,164,43,36,2,3
36,합천군,209,47,11,21,82,24,20,0,4
37,창원시,9948,1930,434,401,5125,707,986,272,93

In [11]:
inf9 = pd.read_excel("04_시군구별 제4권-부산 대구 울산 경북 경남_2019년 .xlsx",sheet_name='106p')


# 1. 3번 행을 칼럼명으로 변경
inf9.columns = inf9.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf9 = inf9.drop(index=[0, 1, 2, 3, 4, 5, 6])

# 3. 46, 47, 48번 행 삭제
inf9 = inf9.drop(index=[45, 46, 47])

# 인덱스 리셋
inf9 = inf9.reset_index(drop=True)

inf9.iloc[:, [3, 4]] = inf9.iloc[:, [4, 3]].values
inf9.iloc[:, [15, 16]] = inf9.iloc[:, [16, 15]].values

inf9 = inf9.loc[:, ~inf9.columns.isna()]

inf9.columns = [col.split('\n')[0] for col in inf9.columns]
inf9.columns = [col.split(' Inpatient room')[0] for col in inf9.columns]
inf9.columns = [col.split('Intensive Care Unit')[0] for col in inf9.columns]
inf9 = inf9.drop(columns = [ '계                                          Total',  '정신과폐쇄',
'격리병실                           Isolation room', '무균치료실                   Aseptic room', "Division"])

## 창원시 관련 행 필터링 및 합계 계산
changwon_gu = ["포항시남구               ", "포항시북구               "]
changwon_data = inf9[inf9['구   분'].isin(changwon_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
changwon_row = pd.DataFrame([['포항시'] + changwon_data.tolist()], columns=inf9.columns)


# 창원시 행 추가 및 기존 구 삭제
inf9 = pd.concat([inf9[~inf9['구   분'].isin(changwon_gu)], changwon_row], ignore_index=True)


# # # 창원시 관련 구 이름
# # changwon_gu = ['보  건  소', '보건지소','보건진료소', '보건의료원']

# # # 예시: 'col1', 'col2', 'col3'의 값을 합쳐 'new_col' 생성
# # inf9['보건소'] = inf9[['보  건  소', '보건지소','보건진료소', '보건의료원']].sum(axis=1)

# # inf9 = inf9.drop(columns = [  '보  건  소', '보건지소','보건진료소', '보건의료원'])

inf9 = inf9.rename(columns={'구   분': '지역'})

inf9['지역'] = inf9['지역'] + ' ' + inf9.groupby('지역').cumcount().replace(0, '').astype(str)

inf9

                         지역 일반입원실  중환자실
0                       부산   62952     90
1    중구                       1661      4
2    서구                       4857     25
3    동구                       2767      8
4     영도구                     1646      2
5      부산진구                   6882     25
6     동래구                     5588      3
7    남구                       2752      3
8    북구                       4274      2
9      해운대구                   5744      4
10    사하구                     6543      1
11     금정구                    5239      7
12    강서구                      386      0
13    연제구                     4198      1
14    수영구                     4018      2
15    사상구                     4638      2
16    기장군                     1759      1
17                      대구   33901     51
18  중구                    1   3415      8
19  동구                    1   3156      6
20  서구                    1   3487      1
21  남구                    1   5000     19
22  북구                    1   5693      3
23    수성구                     3570      0
24    달서구                     7393     14
25    달성군                     2187      0
26                      울산   13852     14
27  중구                    2   2339      7
28  남구                    2   5548      2
29  동구                    2   1903      5
30  북구                    2   1491      0
31    울주군                     2571      0
32                      경북   36488     47
33  경주시                       3723      2
34  김천시                       1451      2
35  안동시                       4286      8
36                     포항시    9047     17

In [12]:
inf10 = pd.read_excel("04_시군구별 제4권-부산 대구 울산 경북 경남_2019년 .xlsx",sheet_name='108p')


# 1. 3번 행을 칼럼명으로 변경
inf10.columns = inf10.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf10 = inf10.drop(index=[0, 1, 2, 3, 4, 5, 6])

# 3. 46, 47, 48번 행 삭제
inf10 = inf10.drop(index=[49, 50, 51])

# 인덱스 리셋
inf10 = inf10.reset_index(drop=True)

inf10.iloc[:, [3, 4]] = inf10.iloc[:, [4, 3]].values
inf10.iloc[:, [15, 16]] = inf10.iloc[:, [16, 15]].values

inf10 = inf10.loc[:, ~inf10.columns.isna()]

inf10.columns = [col.split('\n')[0] for col in inf10.columns]
inf10.columns = [col.split(' Inpatient room')[0] for col in inf10.columns]
inf10.columns = [col.split('Intensive Care Unit')[0] for col in inf10.columns]
inf10 = inf10.drop(columns = [ '계                                          Total',  '정신과폐쇄',
'격리병실                           Isolation room', '무균치료실                   Aseptic room', "Division"])

# 창원시 관련 행 필터링 및 합계 계산
changwon_gu = ["창원시 의창구", "창원시 성산구", "창원시 마산합포구", "창원시 마산회원구", "창원시 진해구"]
changwon_data = inf10[inf10['구   분'].isin(changwon_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
changwon_row = pd.DataFrame([['창원시'] + changwon_data.tolist()], columns=inf10.columns)


# 창원시 행 추가 및 기존 구 삭제
inf10 = pd.concat([inf10[~inf10['구   분'].isin(changwon_gu)], changwon_row], ignore_index=True)

inf10 = inf10.rename(columns={'구   분': '지역'})

inf10

                        지역 일반입원실  중환자실
0   구미시                      3528      6
1   영주시                      1945      3
2   영천시                      1142      1
3   상주시                      1090      2
4   문경시                       942      3
5   경산시                      3071      2
6   군위군                        10      0
7   의성군                      1405      0
8   청송군                       103      0
9   영양군                        50      0
10  영덕군                       281      0
11  청도군                       905      0
12  고령군                       286      0
13  성주군                       849      0
14  칠곡군                      1022      0
15  예천군                       705      1
16  봉화군                       255      0
17  울진군                       329      0
18  울릉군                        63      0
19                      경남  53073     47
20                     진주시   5421      5
21                     통영시   1809      0
22                     사천시   2165      1
23                     김해시   9550      2
24                     밀양시   1774      1
25                     거제시   2176      2
26                     양산시   5760      9
27                     의령군    386      0
28                     함안군   1312      0
29                     창녕군   1804      0
30                     고성군    712      0
31                     남해군    261      0
32                     하동군    565      0
33                     산청군    173      0
34                     함양군    118      0
35                     거창군    690      1
36                     합천군    611      0
37                     창원시  17786     26

In [13]:
inf11 = pd.read_excel("04_시군구별 제4권-부산 대구 울산 경북 경남_2019년 .xlsx",sheet_name='110p')


# 1. 3번 행을 칼럼명으로 변경
inf11.columns = inf11.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf11 = inf11.drop(index=[0, 1, 2, 3, 4])

# 3. 46, 47, 48번 행 삭제
inf11 = inf11.drop(index=[43, 44, 45])

# 인덱스 리셋
inf11 = inf11.reset_index(drop=True)

# inf11.iloc[:, [3, 4]] = inf11.iloc[:, [4, 3]].values
# inf11.iloc[:, [15, 16]] = inf11.iloc[:, [16, 15]].values

# inf11 = inf11.loc[:, ~inf11.columns.isna()]

inf11.columns = [col.split('\n')[0] for col in inf11.columns]
inf11.columns = [col.split(' Inpatient room')[0] for col in inf11.columns]
inf11.columns = [col.split('Intensive Care Unit')[0] for col in inf11.columns]
inf11 = inf11.drop(columns = [  '계', '유         방',
       '양전자 방사                                 단층 촬영                            PET',
       '체외충격파쇄석기     Extracorporead', '혈관조영장치', '혈관조영장치', 'Division'])

## 창원시 관련 행 필터링 및 합계 계산
changwon_gu = ["포항시남구               ", "포항시북구               "]
changwon_data = inf11[inf11['구   분'].isin(changwon_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
changwon_row = pd.DataFrame([['포항시'] + changwon_data.tolist()], columns=inf11.columns)


# 창원시 행 추가 및 기존 구 삭제
inf11 = pd.concat([inf11[~inf11['구   분'].isin(changwon_gu)], changwon_row], ignore_index=True)

inf11 = inf11.rename(columns={'구   분': '지역'})

inf11['지역'] = inf11['지역'] + ' ' + inf11.groupby('지역').cumcount().replace(0, '').astype(str)


inf11

                         지역 자기공명영상기 전산화단층촬영장치   초음파
0                       부산      123       154  2642
1    중구                           1         1    75
2    서구                          13        21   218
3    동구                          11         9   157
4     영도구                         2         2    50
5      부산진구                      19        26   422
6     동래구                        17        15   259
7    남구                           4         5   124
8    북구                           9        11   214
9      해운대구                      12        17   269
10    사하구                         9        12   190
11     금정구                        4         7   136
12    강서구                         1         1    30
13    연제구                         4         7   158
14    수영구                         8         7   141
15    사상구                         5         7   115
16    기장군                         4         6    84
17                      대구       99       133  2050
18  중구                    1      24        21   293
19  동구                    1      10        17   232
20  서구                    1       6         8   107
21  남구                    1       9        15   222
22  북구                    1      12        23   270
23    수성구                         7        12   316
24    달서구                        30        33   509
25    달성군                         1         4   101
26                      울산       33        42   636
27  중구                    2       8        11   123
28  남구                    2      16        18   292
29  동구                    2       5         9   123
30  북구                    2       3         3    44
31    울주군                         1         1    54
32                      경북       55        88  1371
33  경주시                           5         7   121
34  김천시                           3         3    64
35  안동시                           5        12   127
36                     포항시       15        20   324

In [14]:
inf12 = pd.read_excel("04_시군구별 제4권-부산 대구 울산 경북 경남_2019년 .xlsx",sheet_name='112p')


# 1. 3번 행을 칼럼명으로 변경
inf12.columns = inf12.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf12 = inf12.drop(index=[0, 1, 2, 3, 4])

#3. 46, 47, 48번 행 삭제
inf12 = inf12.drop(index=[47, 48, 49])

# 인덱스 리셋
inf12 = inf12.reset_index(drop=True)

# inf12.iloc[:, [3, 4]] = inf12.iloc[:, [4, 3]].values
# inf12.iloc[:, [15, 16]] = inf12.iloc[:, [16, 15]].values

# inf12 = inf12.loc[:, ~inf12.columns.isna()]

inf12.columns = [col.split('\n')[0] for col in inf12.columns]
# inf12.columns = [col.split(' Inpatient room')[0] for col in inf12.columns]
# inf12.columns = [col.split('Intensive Care Unit')[0] for col in inf12.columns]
inf12 = inf12.drop(columns = [  '계', '유         방',
       '양전자 방사                                 단층 촬영                            PET',
       '체외충격파쇄석기     Extracorporead', '혈관조영장치', '혈관조영장치', 'Division'])


# 창원시 관련 행 필터링 및 합계 계산
changwon_gu = ["창원시 의창구", "창원시 성산구", "창원시 마산합포구", "창원시 마산회원구", "창원시 진해구"]
changwon_data = inf12[inf12['구   분'].isin(changwon_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
changwon_row = pd.DataFrame([['창원시'] + changwon_data.tolist()], columns=inf12.columns)


# 창원시 행 추가 및 기존 구 삭제
inf12 = pd.concat([inf12[~inf12['구   분'].isin(changwon_gu)], changwon_row], ignore_index=True)

inf12 = inf12.rename(columns={'구   분': '지역'})

inf12

                        지역 자기공명영상기 전산화단층촬영장치   초음파
0   구미시                         11        13   254
1   영주시                          5         6    41
2   영천시                          1         1    44
3   상주시                          2         3    46
4   문경시                          1         5    37
5   경산시                          4         6   132
6   군위군                        NaN       NaN     7
7   의성군                        NaN         2    22
8   청송군                        NaN       NaN     9
9   영양군                        NaN       NaN     1
10  영덕군                        NaN         1    13
11  청도군                          1         1    19
12  고령군                        NaN         1     9
13  성주군                        NaN         1    14
14  칠곡군                        NaN         2    36
15  예천군                          1         1    19
16  봉화군                        NaN         1     7
17  울진군                          1         1    20
18  울릉군                        NaN         1     5
19                      경남     114       150  1721
20                     진주시      17        19   245
21                     통영시       9         8    77
22                     사천시       2         4    47
23                     김해시      19        17   226
24                     밀양시       3         5    36
25                     거제시       3         8    86
26                     양산시      12        18   190
27                     의령군     NaN         1     4
28                     함안군     NaN         2    17
29                     창녕군       1         2    28
30                     고성군       1         3    14
31                     남해군       1         2    14
32                     하동군     NaN         2    15
33                     산청군     NaN       NaN     5
34                     함양군     NaN         2    10
35                     거창군       1         3    24
36                     합천군       1         2    13
37                     창원시      44        52   670

In [15]:
inf13 = pd.read_excel("04_시군구별 제4권-부산 대구 울산 경북 경남_2019년 .xlsx",sheet_name='144p')
# Load the "114p보험료" sheet to inspect its structure and content



# 1. 3번 행을 칼럼명으로 변경
inf13.columns = inf13.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf13 = inf13.drop(index=[0, 1, 2, 3, 4, 5, 6, 7])

# 3. 46, 47, 48번 행 삭제
inf13 = inf13.drop(index=[46, 47])

# 인덱스 리셋
inf13 = inf13.reset_index(drop=True)

# # inf13.iloc[:, [3, 4]] = inf13.iloc[:, [4, 3]].values
# # inf13.iloc[:, [15, 16]] = inf13.iloc[:, [16, 15]].values

inf13 = inf13.loc[:, ~inf13.columns.isna()]

inf13.columns = [col.split('\n')[0] for col in inf13.columns]
inf13.columns = [col.split(' Inpatient room')[0] for col in inf13.columns]
inf13.columns = [col.split('Intensive Care Unit')[0] for col in inf13.columns]
inf13 = inf13.drop(columns = ['내원일수', '급여일수',
       '진료실인원당     Per Patient', '내원1일당  Per Visit ',
       '급여1일당  Per reimbursed day', 'Division'])

## 창원시 관련 행 필터링 및 합계 계산
changwon_gu = ["포항시남구               ", "포항시북구               "]
changwon_data = inf13[inf13['구 분'].isin(changwon_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
changwon_row = pd.DataFrame([['포항시'] + changwon_data.tolist()], columns=inf13.columns)


# 창원시 행 추가 및 기존 구 삭제
inf13 = pd.concat([inf13[~inf13['구 분'].isin(changwon_gu)], changwon_row], ignore_index=True)

inf13 = inf13.rename(columns={'구 분': '지역'})

inf13['지역'] = inf13['지역'] + ' ' + inf13.groupby('지역').cumcount().replace(0, '').astype(str)

inf13

                         지역    진료실인원            진료비             급여비
0                       부산   3226216  7235273203.66  5655935866.843
1    중구                        39189   106589369.16    84526510.155
2    서구                       101222   272240276.21    214746594.49
3    동구                        82511   228698593.06   182331288.906
4     영도구                     109864   336699844.34   270253606.794
5      부산진구                   335244   768250276.01   598378397.696
6     동래구                     255425   532829800.05   411809726.164
7    남구                       259100   576166625.67   447359944.074
8    북구                       275434   594396613.84   465539390.838
9      해운대구                   383366   798509976.16   622457738.708
10    사하구                     303937   687400530.89   538909189.042
11     금정구                    225543   499832907.33   390342846.242
12    강서구                     127784   227511766.67   174231585.408
13    연제구                     197481   432642094.89    336365568.02
14    수영구                     164989   374156396.61   290476921.156
15    사상구                     206848   479550570.57   377000614.591
16    기장군                     158279    319797562.2   251205944.559
17                      대구   2316591  4454180533.63   3479813517.85
18  중구                    1    72364   151952745.57   118961166.632
19  동구                    1   327298   676310900.95   531983149.706
20  서구                    1   164390   381747363.74   302232977.012
21  남구                    1   137879   322410129.26   256049195.208
22  북구                    1   416273    754558154.9   586295132.692
23    수성구                     406457   726592690.15   562531591.849
24    달서구                     542683  1000226951.85   779818136.821
25    달성군                     249247   440381597.21    341942167.93
26                      울산   1101587  1938685130.17   1496333073.07
27  중구                    2   211841   402266873.46   311747846.802
28  남구                    2   308230   530522028.76   408608683.644
29  동구                    2   154118   264801534.13   204992308.992
30  북구                    2   209397   322047928.97    246760392.53
31    울주군                     218001   419046764.85   324223841.102
32                      경북   2554098  5532111036.32  4310179303.492
33  경주시                       247716   550172897.48   428175413.413
34  김천시                       134936   306805100.63   239384905.243
35  안동시                       152465   352640364.88   276378735.193
36                     포항시    482289  1008247004.42   784418160.167

In [16]:
inf14 = pd.read_excel("04_시군구별 제4권-부산 대구 울산 경북 경남_2019년 .xlsx",sheet_name='146p')


# 1. 3번 행을 칼럼명으로 변경
inf14.columns = inf14.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf14 = inf14.drop(index=[0, 1, 2, 3, 4, 5, 6, 7])

# 3. 46, 47, 48번 행 삭제
inf14 = inf14.drop(index=[50, 51])

# 인덱스 리셋
inf14 = inf14.reset_index(drop=True)

# # inf14.iloc[:, [3, 4]] = inf14.iloc[:, [4, 3]].values
# # inf14.iloc[:, [15, 16]] = inf14.iloc[:, [16, 15]].values

inf14 = inf14.loc[:, ~inf14.columns.isna()]

inf14.columns = [col.split('\n')[0] for col in inf14.columns]
# # inf14.columns = [col.split(' Inpatient room')[0] for col in inf14.columns]
# # inf14.columns = [col.split('Intensive Care Unit')[0] for col in inf14.columns]
inf14 = inf14.drop(columns = ['내원일수', '급여일수',
       '진료실인원당     Per Patient', '내원1일당  Per Visit ',
       '급여1일당  Per reimbursed day', 'Division'])

# 창원시 관련 행 필터링 및 합계 계산
changwon_gu = ["창원시 의창구", "창원시 성산구", "창원시 마산합포구", "창원시 마산회원구", "창원시 진해구"]
changwon_data = inf14[inf14['구 분'].isin(changwon_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
changwon_row = pd.DataFrame([['창원시'] + changwon_data.tolist()], columns=inf14.columns)


# 창원시 행 추가 및 기존 구 삭제
inf14 = pd.concat([inf14[~inf14['구 분'].isin(changwon_gu)], changwon_row], ignore_index=True)

inf14 = inf14.rename(columns={'구 분': '지역'})

inf14

                        지역    진료실인원            진료비             급여비
0   구미시                      398204   603293149.05   462985729.979
1   영주시                      100348   235422070.44   184472262.174
2   영천시                       99813   245067763.84   192843114.144
3   상주시                       96206   255865976.82   198882622.613
4   문경시                       69275   167817331.26   130979794.758
5   경산시                      252571   477268858.08   370274010.824
6   군위군                       23218    63884035.54    49579804.399
7   의성군                       51141   159658275.39   125037051.181
8   청송군                       24379     67154715.4    52428659.882
9   영양군                       16158    43697082.38    34217592.517
10  영덕군                       36058   114534077.81    90977848.218
11  청도군                       41917   129489651.63   101951974.287
12  고령군                       32369    81878634.69     64006476.81
13  성주군                       43069   114546240.66    89000117.667
14  칠곡군                      112268   205884697.34   160290750.548
15  예천군                       53001   132660292.97   103809859.596
16  봉화군                       30541    82301007.67    64459326.896
17  울진군                       47053   114225941.65    90603595.115
18  울릉군                        9103    19595866.29    15021497.868
19                      경남  3226667  6623105067.17  5139220521.356
20                     진주시   329828   614714122.51   477519293.975
21                     통영시   126249   282997495.96   222581367.507
22                     사천시   107543   241388723.79   189755675.086
23                     김해시   524626   977478358.12   754233225.422
24                     밀양시   101556    265669489.1   208068026.814
25                     거제시   239936   415973702.16   318384863.665
26                     양산시   336675    651336381.4   505153756.218
27                     의령군    26731    87028991.03    68426544.511
28                     함안군    64890   156990484.06   122519816.898
29                     창녕군    61192   175307614.31   137344424.329
30                     고성군    50575   142863108.16   111520832.595
31                     남해군    42137   128730494.88   100641380.123
32                     하동군    44556   125292597.22    97988442.966
33                     산청군    34211    97116781.47    76068399.505
34                     함양군    38298   105372034.74     82542824.76
35                     거창군    59729   146081532.36    114204204.09
36                     합천군    43611   136634812.34   106961551.463
37                     창원시   994324  1872128343.56  1445305891.429

In [17]:
inf15 = pd.read_excel("04_시군구별 제4권-부산 대구 울산 경북 경남_2019년 .xlsx",sheet_name='162p')


# 1. 3번 행을 칼럼명으로 변경
inf15.columns = inf15.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf15 = inf15.drop(index=[0, 1, 2, 3, 4, 5, 6, 7])

# 3. 46, 47, 48번 행 삭제
inf15 = inf15.drop(index=[46, 47])

# 인덱스 리셋
inf15 = inf15.reset_index(drop=True)

# # inf15.iloc[:, [3, 4]] = inf15.iloc[:, [4, 3]].values
# # inf15.iloc[:, [15, 16]] = inf15.iloc[:, [16, 15]].values

inf15 = inf15.loc[:, ~inf15.columns.isna()]

inf15.columns = [col.split('\n')[0] for col in inf15.columns]
# # inf15.columns = [col.split(' Inpatient room')[0] for col in inf15.columns]
# # inf15.columns = [col.split('Intensive Care Unit')[0] for col in inf15.columns]
inf15 = inf15.drop(columns = ['내원일수', '급여일수',
       '진료실인원당     Per Patient', '내원1일당  Per Visit ',
       '급여1일당  Per reimbursed day', 'Division'])

## 창원시 관련 행 필터링 및 합계 계산
changwon_gu = ["포항시남구               ", "포항시북구               "]
changwon_data = inf15[inf15['구 분'].isin(changwon_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
changwon_row = pd.DataFrame([['포항시'] + changwon_data.tolist()], columns=inf15.columns)


# 창원시 행 추가 및 기존 구 삭제
inf15 = pd.concat([inf15[~inf15['구 분'].isin(changwon_gu)], changwon_row], ignore_index=True)

inf15 = inf15.rename(columns={'구 분': '지역'})

inf15['지역'] = inf15['지역'] + ' ' + inf15.groupby('지역').cumcount().replace(0, '').astype(str)

inf15

                         지역    진료실인원            진료비             급여비
0                       부산   3131087  6452715390.73  5020442197.969
1    중구                        29902    39378927.55    31092064.637
2    서구                        84482   141518773.23   111439268.936
3    동구                        66969     91229488.9    72092503.144
4     영도구                      96330   150835254.24   119952439.348
5      부산진구                   293358   395756833.11   304266384.109
6     동래구                     218901   224397280.94   169456954.317
7    남구                       219208   213136086.83   162353772.707
8    북구                       247463   297610062.71   228192318.599
9      해운대구                   338258   402929955.28   311605370.044
10    사하구                     271758   313505582.57   242456513.593
11     금정구                    192061   186290032.86   144316761.446
12    강서구                      95543    46450908.68    34726614.307
13    연제구                     159963   144151044.25   111547497.867
14    수영구                     135187   159222542.14   121657394.003
15    사상구                     170807    178784773.6   138360665.443
16    기장군                     134950   127286949.03     99185733.69
17                      대구   2255053  4051893948.94  3155311951.464
18  중구                    1    59208    59798487.99    45957020.215
19  동구                    1   284994   329136190.14   257574644.323
20  서구                    1   133129   125147512.97    98650930.843
21  남구                    1   107647   146803202.91   116818185.995
22  북구                    1   371322   358566482.53    277124117.06
23    수성구                     359204   289934263.78    221280431.32
24    달서구                     490799      507575960   388392879.733
25    달성군                     207422   134221426.56   102655041.232
26                      울산   1059381  1615553774.42  1237482573.874
27  중구                    2   181806   165052248.09   124629447.448
28  남구                    2   288354   305581578.64   227673782.159
29  동구                    2   143085   180598353.95   140015641.983
30  북구                    2   175066    111915800.6    82077876.314
31    울주군                     165957   130745342.41    100212576.84
32                      경북   2365396  3609542956.65  2779169872.409
33  경주시                       218667   315489428.73   241857416.176
34  김천시                       119022    168314464.2   129318078.217
35  안동시                       141942   255051927.27   198195567.496
36                     포항시    434508   522860943.77   401277032.253

In [18]:
inf16 = pd.read_excel("04_시군구별 제4권-부산 대구 울산 경북 경남_2019년 .xlsx",sheet_name='164p')


# 1. 3번 행을 칼럼명으로 변경
inf16.columns = inf16.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf16 = inf16.drop(index=[0, 1, 2, 3, 4, 5, 6, 7])

# 3. 46, 47, 48번 행 삭제
inf16 = inf16.drop(index=[50, 51])

# 인덱스 리셋
inf16 = inf16.reset_index(drop=True)

# # inf16.iloc[:, [3, 4]] = inf16.iloc[:, [4, 3]].values
# # inf16.iloc[:, [15, 16]] = inf16.iloc[:, [16, 15]].values

inf16 = inf16.loc[:, ~inf16.columns.isna()]

inf16.columns = [col.split('\n')[0] for col in inf16.columns]
# # inf16.columns = [col.split(' Inpatient room')[0] for col in inf16.columns]
# # inf16.columns = [col.split('Intensive Care Unit')[0] for col in inf16.columns]
inf16 = inf16.drop(columns = ['내원일수', '급여일수',
       '진료실인원당     Per Patient', '내원1일당  Per Visit ',
       '급여1일당  Per reimbursed day', 'Division'])

# 창원시 관련 행 필터링 및 합계 계산
changwon_gu = ["창원시 의창구", "창원시 성산구", "창원시 마산합포구", "창원시 마산회원구", "창원시 진해구"]
changwon_data = inf16[inf16['구 분'].isin(changwon_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
changwon_row = pd.DataFrame([['창원시'] + changwon_data.tolist()], columns=inf16.columns)


# 창원시 행 추가 및 기존 구 삭제
inf16 = pd.concat([inf16[~inf16['구 분'].isin(changwon_gu)], changwon_row], ignore_index=True)

inf16 = inf16.rename(columns={'구 분': '지역'})

inf16

                        지역    진료실인원            진료비             급여비
0   구미시                      375113    408410835.4   306696939.686
1   영주시                       92683   120278370.92    92899196.021
2   영천시                       83377   112691385.19    87986254.265
3   상주시                       82813   128351867.17    97796405.653
4   문경시                       61566    80828998.83    61745653.725
5   경산시                      222017   218596627.11   167082220.333
6   군위군                       16040    11876941.57     9101633.504
7   의성군                       41343    51683263.47    40127362.849
8   청송군                       19127    14215686.72    11068080.951
9   영양군                       11797     7493137.54     5670928.612
10  영덕군                       30332    36655885.46    28785541.413
11  청도군                       31940    43341571.07    34586195.759
12  고령군                       22789    19850930.54    15348515.076
13  성주군                       30377    34372634.69    26918984.231
14  칠곡군                       88224    58765328.97    45529599.349
15  예천군                       42502    43439900.28    33841754.043
16  봉화군                       21785    19551743.92    15164930.844
17  울진군                       40940    42142333.13    32882501.272
18  울릉군                        6704      3342006.6      2433303.24
19                      경남  3074515  5096330739.49  3925919667.799
20                     진주시   314079   489638705.73    376681906.83
21                     통영시   116697   171129974.12   132628463.396
22                     사천시    95058   118555545.32    93343225.067
23                     김해시   483282   595023660.47   451294758.638
24                     밀양시    88485   116886384.58    90035635.211
25                     거제시   222306    240661831.1   180192409.599
26                     양산시   307414   427412754.93   330061868.158
27                     의령군    19964    22848119.39    17819166.835
28                     함안군    46719    39080820.64    30139210.335
29                     창녕군    48768    63466710.35    49410865.198
30                     고성군    39820     51248543.2    39314303.548
31                     남해군    34490    38734074.07    30166621.957
32                     하동군    33964    33383427.41    26170151.188
33                     산청군    25463    16825153.96    13214837.586
34                     함양군    31881    34175998.57    26462254.382
35                     거창군    54099    68132295.26    52593682.979
36                     합천군    34244    46192985.33    36050915.399
37                     창원시   867561   886613706.17   671063805.187

In [19]:
inf17 = pd.read_excel("04_시군구별 제4권-부산 대구 울산 경북 경남_2019년 .xlsx",sheet_name='174p')


# 1. 3번 행을 칼럼명으로 변경
inf17.columns = inf17.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf17 = inf17.drop(index=[0, 1, 2, 3, 4, 5, 6, 7])

# 3. 46, 47, 48번 행 삭제
inf17 = inf17.drop(index=[46, 47])

# 인덱스 리셋
inf17 = inf17.reset_index(drop=True)

# # inf17.iloc[:, [3, 4]] = inf17.iloc[:, [4, 3]].values
# # inf17.iloc[:, [15, 16]] = inf17.iloc[:, [16, 15]].values

inf17 = inf17.loc[:, ~inf17.columns.isna()]

inf17.columns = [col.split('\n')[0] for col in inf17.columns]
# # inf17.columns = [col.split(' Inpatient room')[0] for col in inf17.columns]
# # inf17.columns = [col.split('Intensive Care Unit')[0] for col in inf17.columns]
inf17 = inf17.drop(columns = ['내원일수', '급여일수',
       '진료실인원당     Per Patient', '내원1일당  Per Visit ',
       '급여1일당  Per reimbursed day', 'Division'])

## 창원시 관련 행 필터링 및 합계 계산
changwon_gu = ["포항시남구               ", "포항시북구               "]
changwon_data = inf17[inf17['구 분'].isin(changwon_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
changwon_row = pd.DataFrame([['포항시'] + changwon_data.tolist()], columns=inf17.columns)


# 창원시 행 추가 및 기존 구 삭제
inf17 = pd.concat([inf17[~inf17['구 분'].isin(changwon_gu)], changwon_row], ignore_index=True)

inf17 = inf17.rename(columns={'구 분': '지역'})

inf17['지역'] = inf17['지역'] + ' ' + inf17.groupby('지역').cumcount().replace(0, '').astype(str)

inf17

                         지역    진료실인원            진료비             급여비
0                       부산    654254   782557812.93   635493668.874
1    중구                        32752    67210441.61    53434445.518
2    서구                        81434   130721502.98   103307325.554
3    동구                        66348   137469104.16   110238785.762
4     영도구                      78798    185864590.1   150301167.446
5      부산진구                   232912    372493442.9   294112013.587
6     동래구                     195570   308432519.11   242352771.847
7    남구                       197812   363030538.84   285006171.367
8    북구                       176037   296786551.13   237347072.239
9      해운대구                   257666   395580020.88   310852368.664
10    사하구                     200292   373894948.32   296452675.449
11     금정구                    173424   313542874.47   246026084.796
12    강서구                     105517   181060857.99   139504971.101
13    연제구                     164240   288491050.64   224818070.153
14    수영구                     130194   214933854.47   168819527.153
15    사상구                     162390   300765796.97   238639949.148
16    기장군                     109424   192510613.17   152020210.869
17                      대구    452961   402286584.69   324501566.386
18  중구                    1    59702    92154257.58    73004146.417
19  동구                    1   236955   347174710.81   274408505.383
20  서구                    1   137599   256599850.77   203582046.169
21  남구                    1   117922   175606926.35   139231009.213
22  북구                    1   279360   395991672.37   309171015.632
23    수성구                     296964   436658426.37   341251160.529
24    달서구                     368126   492650991.85   391425257.088
25    달성군                     195976   306160170.65   239287126.698
26                      울산    269443   323131355.75   258850499.196
27  중구                    2   162881   237214625.37   187118399.354
28  남구                    2   165165   224940450.12   180934901.485
29  동구                    2    81135    84203180.18    64976667.009
30  북구                    2   157846   210132128.37   164682516.216
31    울주군                     175590   288301422.44   224011264.262
32                      경북   1071937  1922568079.67  1531009431.083
33  경주시                       127184   234683468.75   186317997.237
34  김천시                        79157   138490636.43   110066827.026
35  안동시                        60036    97588437.61    78183167.697
36                     포항시    323920   485386060.65   383141127.914

In [20]:
inf18 = pd.read_excel("04_시군구별 제4권-부산 대구 울산 경북 경남_2019년 .xlsx",sheet_name='176p')


# 1. 3번 행을 칼럼명으로 변경
inf18.columns = inf18.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf18 = inf18.drop(index=[0, 1, 2, 3, 4, 5, 6, 7])

# 3. 46, 47, 48번 행 삭제
inf18 = inf18.drop(index=[50, 51])

# 인덱스 리셋
inf18 = inf18.reset_index(drop=True)

# # inf18.iloc[:, [3, 4]] = inf18.iloc[:, [4, 3]].values
# # inf18.iloc[:, [15, 16]] = inf18.iloc[:, [16, 15]].values

inf18 = inf18.loc[:, ~inf18.columns.isna()]

inf18.columns = [col.split('\n')[0] for col in inf18.columns]
# # inf18.columns = [col.split(' Inpatient room')[0] for col in inf18.columns]
# # inf18.columns = [col.split('Intensive Care Unit')[0] for col in inf18.columns]
inf18 = inf18.drop(columns = ['내원일수', '급여일수',
       '진료실인원당     Per Patient', '내원1일당  Per Visit ',
       '급여1일당  Per reimbursed day', 'Division'])

# 창원시 관련 행 필터링 및 합계 계산
changwon_gu = ["창원시 의창구", "창원시 성산구", "창원시 마산합포구", "창원시 마산회원구", "창원시 진해구"]
changwon_data = inf18[inf18['구 분'].isin(changwon_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
changwon_row = pd.DataFrame([['창원시'] + changwon_data.tolist()], columns=inf18.columns)


# 창원시 행 추가 및 기존 구 삭제
inf18 = pd.concat([inf18[~inf18['구 분'].isin(changwon_gu)], changwon_row], ignore_index=True)

inf18 = inf18.rename(columns={'구 분': '지역'})

inf18

                        지역   진료실인원            진료비             급여비
0   구미시                     160003   194882313.65   156288790.293
1   영주시                      57386   115143699.52    91573066.153
2   영천시                      66139   132376378.65   104856859.879
3   상주시                      60861   127514109.65    101086216.96
4   문경시                      42265    86988332.43    69234141.033
5   경산시                     171617   258672230.97   203191790.491
6   군위군                      20547    52007093.97    40478170.895
7   의성군                      41653   107975011.92    84909688.332
8   청송군                      21195    52939028.68    41360578.931
9   영양군                      14460    36203944.84    28546663.905
10  영덕군                      27890    77878192.35    62192306.805
11  청도군                      34212    86148080.56    67365778.528
12  고령군                      27766    62027704.15    48657961.734
13  성주군                      37073    80173605.97    62081133.436
14  칠곡군                      90801   147119368.37   114761151.199
15  예천군                      42943    89220392.69    69968105.553
16  봉화군                      27198    62749263.75    49294396.052
17  울진군                      32893    72083608.52    57721093.843
18  울릉군                       7940    16253859.69    12588194.628
19                      경남  983375  1526774327.68  1213300853.557
20                     진주시   99353   125075416.78   100837387.145
21                     통영시   60018   111867521.84    89952904.111
22                     사천시   70231   122833178.47    96412450.019
23                     김해시  256761   382454697.65   302938466.784
24                     밀양시   63481   148783104.52   118032391.603
25                     거제시  114030   175311871.06   138192454.066
26                     양산시  174071   223923626.47    175091888.06
27                     의령군   22874    64180871.64    50607377.676
28                     함안군   55635   117909663.42    92380606.563
29                     창녕군   48504   111840903.96    87933559.131
30                     고성군   39343    91614564.96    72206529.047
31                     남해군   33499    89996420.81    70474758.166
32                     하동군   37192    91909169.81    71818291.778
33                     산청군   30728    80291627.51    62853561.919
34                     함양군   30228    71196036.17    56080570.378
35                     거창군   37696     77949237.1    61610521.111
36                     합천군   34937    90441827.01    70910636.064
37                     창원시  694838   985514637.39   774242086.242

In [21]:

# merged_df = pd.merge(inf, inf2, on = '구 분')

# merged_df

result1 = pd.concat([inf, inf2], axis=0)
result2 = pd.concat([inf3, inf4], axis=0)
result3 = pd.concat([inf5, inf6], axis=0)
result4 = pd.concat([inf7, inf8], axis=0)
result5 = pd.concat([inf9, inf10], axis=0)
result6 = pd.concat([inf11, inf12], axis=0)
result7 = pd.concat([inf13, inf14], axis=0)
result8 = pd.concat([inf15, inf16], axis=0)
result9 = pd.concat([inf17, inf18], axis=0)

In [22]:
dataframes = [result1, result2, result3, result4, result5, result6, result7, result8, result9]

result = dataframes[0]
for df in dataframes[1:]:
    result = result.merge(df, on='지역')
result = result.drop_duplicates(subset='지역', keep='first')
result

,지역,의료보장,근 로 자,공ㆍ교,지 역,의료급여 1종,의료급여 2종,계_x,0-4세,5-9세,...,초음파,진료실인원_x,진료비_x,급여비_x,진료실인원_y,진료비_y,급여비_y,진료실인원,진료비,급여비
0,부산,3429267,2125381,230757,934462,101047,37620,3429267,108345,135614,...,2642,3226216,7235273203.66,5655935866.843,3131087,6452715390.73,5020442197.969,654254,782557812.93,635493668.874
1,중구,42345,21852,1509,16226,1983,775,42345,668,880,...,75,39189,106589369.16,84526510.155,29902,39378927.55,31092064.637,32752,67210441.61,53434445.518
2,서구,107856,62140,5533,33464,5187,1532,107856,2477,3298,...,218,101222,272240276.21,214746594.49,84482,141518773.23,111439268.936,81434,130721502.98,103307325.554
3,동구,88115,50011,3843,27412,4944,1905,88115,1953,2236,...,157,82511,228698593.06,182331288.906,66969,91229488.9,72092503.144,66348,137469104.16,110238785.762
4,영도구,116454,66798,5622,34807,7118,2109,116454,2424,3340,...,50,109864,336699844.34,270253606.794,96330,150835254.24,119952439.348,78798,185864590.1,150301167.446
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,산청군,35779,17905,3917,12372,1322,263,35779,710,814,...,5,34211,97116781.47,76068399.505,25463,16825153.96,13214837.586,30728,80291627.51,62853561.919
71,함양군,40029,20680,4534,13107,1458,250,40029,798,1148,...,10,38298,105372034.74,82542824.76,31881,34175998.57,26462254.382,30228,71196036.17,56080570.378
72,거창군,62560,33444,7042,19460,1981,633,62560,1580,2416,...,24,59729,146081532.36,114204204.09,54099,68132295.26,52593682.979,37696,77949237.1,61610521.111
73,합천군,45432,23416,5445,14429,1800,342,45432,710,1006,...,13,43611,136634812.34,106961551.463,34244,46192985.33,36050915.399,34937,90441827.01,70910636.064
74,창원시,1056061,672519,100505,260485,17836,4716,1056061,38547,49627,...,670,994324,1872128343.56,1445305891.429,867561,886613706.17,671063805.187,694838,985514637.39,774242086.242

In [23]:
file_path = "2019 부산경남.csv"  # 저장할 파일 이름과 경로 설정
result.to_csv(file_path, index=False, encoding='utf-8-sig')  # UTF-8 인코딩으로 저장