### 508p

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import font_manager, rc

In [4]:
inf = pd.read_excel("01_시군구별 제1권-서울 인천 경기 강원_2019년.xlsx",sheet_name='82p인구')


# 1. 3번 행을 칼럼명으로 변경
inf.columns = inf.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf = inf.drop(index=[0, 1, 2, 3, 4, 5, 6, 7])

# 3. 46, 47, 48번 행 삭제
inf = inf.drop(index=[57, 58, 59])

# 인덱스 리셋
inf = inf.reset_index(drop=True)

inf.iloc[:, [2, 3]] = inf.iloc[:, [3, 2]].values
inf.iloc[:, [6, 7]] = inf.iloc[:, [7, 6]].values

inf = inf.loc[:, ~inf.columns.isna()]

inf = inf.drop(columns = ["G. & T.", "Division"])

inf.columns = [col.split('\n')[0] for col in inf.columns]
inf.columns = [col.split('  C.E')[0] for col in inf.columns]
inf.columns = [col.split('  S.E.')[0] for col in inf.columns]
inf.columns = [col.split('    Medical Aid')[0] for col in inf.columns]

# 창원시 관련 행 필터링 및 합계 계산
suwon_gu = ["수원시장안구           ", "수원시권선구           ", "수원시팔달구           ", "수원시영통구           "]
suwon_data = inf[inf['구  분'].isin(suwon_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
suwon_row = pd.DataFrame([['수원시'] + suwon_data.tolist()], columns=inf.columns)

# 창원시 관련 행 필터링 및 합계 계산
sungnam_gu = ["성남시수정구           ", "성남시중원구           ", "성남시분당구           "]
sungnam_data = inf[inf['구  분'].isin(sungnam_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
sungnam_row = pd.DataFrame([['성남시'] + sungnam_data.tolist()], columns=inf.columns)

# 창원시 관련 행 필터링 및 합계 계산
anyang_gu = ["안양시만안구           ", "안양시동안구           "]
anyang_data = inf[inf['구  분'].isin(anyang_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
anyang_row = pd.DataFrame([['안양시'] + anyang_data.tolist()], columns=inf.columns)

# 창원시 행 추가 및 기존 구 삭제
inf = pd.concat([inf[~inf['구  분'].isin(suwon_gu)], suwon_row], ignore_index=True)
inf = pd.concat([inf[~inf['구  분'].isin(sungnam_gu)], sungnam_row], ignore_index=True)
inf = pd.concat([inf[~inf['구  분'].isin(anyang_gu)], anyang_row], ignore_index=True)
inf = inf.rename(columns={'구  분': '지역'})

inf['지역'] = inf['지역'] + ' ' + inf.groupby('지역').cumcount().replace(0, '').astype(str)

# inf.columns = ['구  분', '진료실인원수(관외)', '입내원일수(관외)', '요양급여일수(관외)', '진료비(관외)', '급여비(관외)']
inf

,지역,의료보장,근 로 자,공ㆍ교,지 역,의료급여 1종,의료급여 2종
0,서울,9933336,6410576,576211,2695880,179257,71412
1,종로구,157094,92512,11069,49231,3442,840
2,중구,138071,84314,5503,44532,2967,755
3,용산구,231921,143113,14686,68331,4416,1375
4,성동구,305714,201231,14947,82873,4507,2156
5,광진구,359122,231676,17531,103182,4664,2069
6,동대문구,348727,215560,17378,105242,7849,2698
7,중랑구,397458,242088,15248,126078,10248,3796
8,성북구,443118,279766,26575,125710,7630,3437
9,강북구,312878,184095,11894,102666,9914,4309
10,도봉구,332897,207826,18543,97102,6369,3057
11,노원구,533064,336075,47527,126184,16916,6362
12,은평구,478750,303868,25106,134073,10888,4815
13,서대문구,310550,199939,19106,84578,5309,1618
14,마포구,379306,253364,21274,97233,5181,2254
15,양천구,461713,311907,31760,107696,7481,2869
16,강서구,597409,402404,27201,147538,15447,4819
17,구로구,438588,280030,19207,130983,6168,2200
18,금천구,253467,153810,8153,82897,5988,2619
19,영등포구,404750,254688,22520,119597,5949,1996
20,동작구,402938,263373,26956,104271,6101,2237
21,관악구,510815,320450,25854,151427,9018,4066
22,서초구,443456,305646,34217,98977,3179,1437
23,강남구,570657,385223,41159,133552,7200,3523
24,송파구,683341,469415,46076,158666,6061,3123
25,강동구,437532,288203,26721,113261,6365,2982
26,인천,3017890,1945387,172347,804178,68643,27335
27,중구 1,138834,88171,9643,36882,3059,1079
28,동구,64473,41354,2787,17586,2042,704
29,미추홀구,413373,254602,17772,125879,10570,4550
30,연수구,375331,255359,31190,80561,5991,2230
31,남동구,547370,353064,31381,144267,13930,4728
32,부평구,521939,328285,27227,146194,13909,6324
33,계양구,305597,200009,12664,84383,5734,2807
34,서구,559713,380067,29000,137816,8537,4293
35,강화군,70542,36008,6255,23283,4436,560
36,옹진군,20718,8468,4428,7327,435,60
37,경기,13656980,9081696,809226,3523057,188168,54833
38,의정부시,451829,276260,30201,132971,9593,2804
39,부천시,853443,554101,43272,239384,12834,3852
40,수원시,1229909,838286,79745,294309,13771,3798
41,성남시,959537,652913,59325,228857,13948,4494
42,안양시,575557,395330,40912,131023,6314,1978

In [5]:
inf2 = pd.read_excel("01_시군구별 제1권-서울 인천 경기 강원_2019년.xlsx",sheet_name='84p')


# 1. 3번 행을 칼럼명으로 변경
inf2.columns = inf2.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf2 = inf2.drop(index=[0, 1, 2, 3, 4, 5, 6, 7])

# 3. 46, 47, 48번 행 삭제
inf2 = inf2.drop(index=[58, 59, 60])

# 인덱스 리셋
inf2 = inf2.reset_index(drop=True)

inf2.iloc[:, [2, 3]] = inf2.iloc[:, [3, 2]].values
inf2.iloc[:, [6, 7]] = inf2.iloc[:, [7, 6]].values

inf2 = inf2.loc[:, ~inf2.columns.isna()]

inf2 = inf2.drop(columns = ["G. & T.", "Division"])

inf2.columns = [col.split('\n')[0] for col in inf2.columns]
inf2.columns = [col.split('  C.E')[0] for col in inf2.columns]
inf2.columns = [col.split('  S.E.')[0] for col in inf2.columns]
inf2.columns = [col.split('    Medical Aid')[0] for col in inf2.columns]

# 창원시 관련 행 필터링 및 합계 계산
ansan_gu = ["안산시상록구           ", "안산시단원구           "]
ansan_data = inf2[inf2['구  분'].isin(ansan_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
ansan_row = pd.DataFrame([['안산시'] + ansan_data.tolist()], columns=inf2.columns)

# 창원시 관련 행 필터링 및 합계 계산
goyang_gu = ["고양시덕양구           ", "고양시일산동구", "고양시일산서구"]
goyang_data = inf2[inf2['구  분'].isin(goyang_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
goyang_row = pd.DataFrame([['고양시'] + goyang_data.tolist()], columns=inf2.columns)

# 창원시 관련 행 필터링 및 합계 계산
yongin_gu = ["용인시처인구", "용인시기흥구", "용인시수지구"]
yongin_data = inf2[inf2['구  분'].isin(yongin_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
yongin_row = pd.DataFrame([['용인시'] + yongin_data.tolist()], columns=inf2.columns)

# 창원시 행 추가 및 기존 구 삭제
inf2 = pd.concat([inf2[~inf2['구  분'].isin(ansan_gu)], ansan_row], ignore_index=True)
inf2 = pd.concat([inf2[~inf2['구  분'].isin(goyang_gu)], goyang_row], ignore_index=True)
inf2 = pd.concat([inf2[~inf2['구  분'].isin(yongin_gu)], yongin_row], ignore_index=True)
inf2 = inf2.rename(columns={'구  분': '지역'})

inf2['지역'] = inf2['지역'] + ' ' + inf2.groupby('지역').cumcount().replace(0, '').astype(str)

# inf2.columns = ['구  분', '진료실인원수(관외)', '입내원일수(관외)', '요양급여일수(관외)', '진료비(관외)', '급여비(관외)']
inf2

                       지역     의료보장   근 로 자     공ㆍ교     지 역 의료급여 1종 의료급여 2종
0   광명시                     322688  221135   17007   78637    4510    1399
1   평택시                     533575  346548   31711  145060    7848    2408
2    동두천시                    95374   53597    7300   30406    3474     597
3   과천시                      58858   39229    6839   12014     549     227
4   구리시                     200048  128901   12067   54418    3397    1265
5    남양주시                   709312  446371   40708  209138   10157    2938
6   오산시                     236644  162495    8196   62643    2617     693
7   시흥시                     512586  346199   17673  140344    6098    2272
8   군포시                     283322  196994   17156   64175    3904    1093
9   의왕시                     162992  113622   11292   36099    1513     466
10  하남시                     275869  187589   18001   66452    2922     905
11  파주시                     465316  301894   33611  120023    7738    2050
12  이천시                     223063  145699   15945   57026    3293    1100
13  안성시                     197484  126525    9919   55074    4985     981
14  김포시                     459769  314328   25917  112947    5192    1385
15  화성시                     869053  642365   45064  173708    6310    1606
16                   광주시    385848  255453   15203  110373    3741    1078
17  양주시                     229083  136682   19338   66574    5046    1443
18  포천시                     159782   89017   14561   50871    4306    1027
19  여주시                     113933   66328    8262   35357    3153     833
20  연천군                      44239   18587    9312   14201    1689     450
21  가평군                      63147   30961    7079   22033    2778     296
22  양평군                     118175   61268   11010   42566    2809     522
23                    강원   1549503  823820  219029  448271   45241   13142
24  춘천시                     282783  151910   47032   71958    8741    3142
25  원주시                     351485  206581   37686   96376    8088    2754
26  강릉시                     214272  117414   26130   62499    6168    2061
27  동해시                      90951   49010   14542   24041    2605     753
28  태백시                      43242   26062    4059   11283    1422     416
29  속초시                      82564   41323   11711   25676    2937     917
30  삼척시                      67653   38049    7676   18019    3266     643
31  홍천군                      69700   33655    9775   24191    1738     341
32  횡성군                      47087   24775    4923   15834    1235     320
33  영월군                      39017   20422    4578   12764    1047     206
34  평창군                      42334   21039    3874   16231    1001     189
35  정선군                      37001   19668    3415   12779    1003     136
36  철원군                      45692   18650   11229   14170    1336     307
37  화천군                      25217    9160    8176    6871     885     125
38  양구군                      23016    8333    7129    6521     827     206
39  인제군                      31938   12269    9097    9525     845     202
40  고성군                      27618   12376    4396    9658     957     231
41  양양군                      27933   13124    3601    9875    1140     193
42                   안산시    710915  453186   20942  219595   12491    4701
43                   고양시   1078782  714375   70096  275339   14331    4641
44                   용인시   1076848  765458   61562  241440    6857    1531

In [6]:
inf3 = pd.read_excel("01_시군구별 제1권-서울 인천 경기 강원_2019년.xlsx",sheet_name='86p연령')


# 1. 3번 행을 칼럼명으로 변경
inf3.columns = inf3.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf3 = inf3.drop(index=[0, 1, 2, 3, 4, 5, 6, 7])

# 3. 46, 47, 48번 행 삭제
inf3 = inf3.drop(index=[57, 58])

# 인덱스 리셋
inf3 = inf3.reset_index(drop=True)

inf3 = inf3.drop(columns = [ "Division"])

inf3.columns = [col.split('\n')[0] for col in inf3.columns]

# 창원시 관련 행 필터링 및 합계 계산
suwon_gu = ["수원시장안구           ", "수원시권선구           ", "수원시팔달구           ", "수원시영통구           "]
suwon_data = inf3[inf3['구  분'].isin(suwon_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
suwon_row = pd.DataFrame([['수원시'] + suwon_data.tolist()], columns=inf3.columns)

# 창원시 관련 행 필터링 및 합계 계산
sungnam_gu = ["성남시수정구           ", "성남시중원구           ", "성남시분당구           "]
sungnam_data = inf3[inf3['구  분'].isin(sungnam_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
sungnam_row = pd.DataFrame([['성남시'] + sungnam_data.tolist()], columns=inf3.columns)

# 창원시 관련 행 필터링 및 합계 계산
anyang_gu = ["안양시만안구           ", "안양시동안구           "]
anyang_data = inf3[inf3['구  분'].isin(anyang_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
anyang_row = pd.DataFrame([['안양시'] + anyang_data.tolist()], columns=inf3.columns)

# 창원시 행 추가 및 기존 구 삭제
inf3 = pd.concat([inf3[~inf3['구  분'].isin(suwon_gu)], suwon_row], ignore_index=True)
inf3 = pd.concat([inf3[~inf3['구  분'].isin(sungnam_gu)], sungnam_row], ignore_index=True)
inf3 = pd.concat([inf3[~inf3['구  분'].isin(anyang_gu)], anyang_row], ignore_index=True)
inf3 = inf3.rename(columns={'구  분': '지역'})
inf3['지역'] = inf3['지역'] + ' ' + inf3.groupby('지역').cumcount().replace(0, '').astype(str)
# inf3.at[2, '지역'] = 중구
# inf3.columns = ['구  분', '진료실인원수(관외)', '입내원일수(관외)', '요양급여일수(관외)', '진료비(관외)', '급여비(관외)']
inf3

,지역,계,0-4세,5-9세,10-14세,15-19세,20-24세,25-29세,30-34세,35-39세,40-44세,45-49세,50-54세,55-59세,60-64세,65-69세,70-74세,75-79세,80세 이상
0,서울,9933336,307840,366494,372199,449004,647850,838952,760167,809190,743110,857604,801587,793103,722805,496505,385309,291243,290374
1,종로구,157094,3727,4828,5223,6622,11235,13645,11438,11201,10651,13664,13400,13590,11714,7869,6447,5635,6205
2,중구,138071,4191,4012,3316,4276,8284,12511,12551,12056,9687,10792,11236,11886,10797,7315,5593,4586,4982
3,용산구,231921,7071,7480,7365,9120,13895,20197,19906,20415,17175,20007,18878,18288,16335,10955,8653,7483,8698
4,성동구,305714,11377,10926,9618,11859,20526,26383,25431,27367,22857,25349,24720,24733,21596,14117,11068,8983,8804
5,광진구,359122,10168,11964,12394,15271,26366,36353,30803,29279,25876,29915,29279,28737,25341,16401,12359,9366,9250
6,동대문구,348727,10675,11786,11334,14002,25641,30167,25182,27656,24966,28028,27397,27862,26346,18657,15074,12278,11676
7,중랑구,397458,11909,13028,12543,15999,24636,31943,28937,31179,27268,32224,34510,36449,32743,22152,17042,12930,11966
8,성북구,443118,13820,17463,17564,21508,32163,34657,29281,33909,32704,40155,35931,34005,31100,21584,17738,14811,14725
9,강북구,312878,7734,9769,10293,13319,20371,23230,19269,22137,21744,27033,26378,27125,25369,18533,15918,13109,11547
10,도봉구,332897,9165,11565,11939,15735,21474,23586,20049,23560,22506,28517,28766,29828,28339,18896,14756,12036,12180
11,노원구,533064,15342,20521,24549,32173,39134,35753,30843,36909,39299,50952,46274,42912,38582,26234,20088,16039,17460
12,은평구,478750,14409,17441,18145,22531,29847,36341,32339,38010,35792,42380,38826,38442,35627,25111,20806,16626,16077
13,서대문구,310550,9530,10975,10815,13860,22586,27108,22121,23702,22040,26387,25127,24452,21670,14902,12707,10938,11630
14,마포구,379306,12805,13814,13928,15817,25816,36257,33628,34480,30307,33443,28667,26577,22982,15368,12924,10942,11551
15,양천구,461713,13267,20066,24406,28154,30411,30933,27360,33346,36303,45327,40848,37748,32831,22234,15827,11034,11618
16,강서구,597409,20978,23456,21650,25777,35645,52657,51168,53943,46039,48271,43824,46472,44328,30080,22161,15085,15875
17,구로구,438588,15343,16782,14972,17080,24638,33266,33564,37124,33309,36709,35639,37470,35137,24591,18154,12904,11906
18,금천구,253467,7337,7592,7076,9027,15214,22924,20482,19593,16957,20774,22610,24385,21025,14147,10225,7475,6624
19,영등포구,404750,14104,13400,11655,13932,22432,37435,37901,35853,29402,32662,32412,34145,30674,20411,15117,11406,11809
20,동작구,402938,12677,14271,13311,16166,28311,38801,32994,32777,29623,32156,30342,31247,28723,20234,16356,12489,12460
21,관악구,510815,12142,13556,13399,17411,40021,68784,49929,41541,34354,38160,35920,36886,34287,25279,20399,15563,13184
22,서초구,443456,14965,21433,22361,23545,25848,32112,32582,37512,38307,43268,35264,30840,28436,19808,15919,10558,10698
23,강남구,570657,15807,23598,28040,32278,35149,45992,44863,48151,48323,56140,46445,39401,35380,25215,19844,12993,13038
24,송파구,683341,24661,29146,28663,32814,41857,54994,55880,60839,54055,58404,53964,52888,48772,32981,23169,14896,15358
25,강동구,437532,14636,17622,17640,20728,26350,32923,31666,36651,33566,36887,34930,36735,34671,23431,16965,11078,11053
26,인천,3017890,109803,136341,133665,150844,195602,223187,198755,241897,234337,265872,261758,264794,215542,129891,97468,73813,84321
27,중구 1,138834,5586,6752,6338,6084,7942,11184,9797,12049,12093,12461,10369,9920,9144,6205,5139,3776,3995
28,동구,64472,1857,2518,2536,2873,3500,3501,3242,4599,4910,5401,5032,5395,5617,4062,3559,2847,3023
29,미추홀구,413374,13803,16047,15159,18193,26952,31306,27320,32475,30467,34858,33736,35411,32339,21115,17209,13112,13872
30,연수구,375331,16198,20672,20427,21452,25026,27187,25421,31558,31637,35415,32217,31180,22492,11783,8353,6350,7963
31,남동구,547370,20260,26119,24874,27343,34968,40515,36270,45801,44412,48253,46579,46876,38303,23701,17095,12452,13549
32,부평구,521939,17122,20330,21013,25520,34443,40338,35420,40207,37614,44873,47054,48437,39745,23951,17379,13280,15213
33,계양구,305597,8923,11736,12529,16134,22257,24273,19032,21463,21291,27163,30514,32128,23131,12169,8425,6571,7858
34,서구,559713,24152,29696,28013,30039,36103,40534,38703,49472,47265,51509,49261,46128,34699,19577,13576,9717,11269
35,강화군,70542,1424,1925,2263,2557,2980,2951,2543,3204,3474,4587,5437,7130,7847,5818,5416,4754,6232
36,옹진군,20718,478,546,513,649,1431,1398,1007,1069,1174,1352,1559,2189,2225,1510,1317,954,1347
37,경기,13656980,536279,666358,645724,712805,876013,973775,918879,1130815,1110426,1253615,1171093,1107099,892590,551411,413510,325609,370979
38,의정부시,451829,15711,19691,19730,24014,30911,31926,26633,33766,33364,41395,40231,38524,31620,20202,16395,13451,14265
39,부천시,853443,28912,34538,34056,40792,56787,65507,59529,67893,63091,73700,75815,80450,66909,39103,25908,18852,21601
40,수원시,1229909,48015,58342,57303,67002,88273,101690,90136,103403,100313,112301,106964,98114,72530,43093,31244,23873,27313
41,성남시,959537,31891,40573,41661,49192,61064,73205,67741,76058,74820,89010,82128,79377,66992,42414,32139,24166,27106
42,안양시,575557,19772,23460,24997,30806,39243,43047,39535,43189,41909,51841,51786,51701,42654,25481,17453,13190,15493

In [7]:
inf4 = pd.read_excel("01_시군구별 제1권-서울 인천 경기 강원_2019년.xlsx",sheet_name='88p')


# 1. 3번 행을 칼럼명으로 변경
inf4.columns = inf4.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf4 = inf4.drop(index=[0, 1, 2, 3, 4, 5, 6, 7])

# 3. 46, 47, 48번 행 삭제
inf4 = inf4.drop(index=[58, 59])

# 인덱스 리셋
inf4 = inf4.reset_index(drop=True)

inf4 = inf4.drop(columns = [ "Division"])

inf4.columns = [col.split('\n')[0] for col in inf4.columns]

# 창원시 관련 행 필터링 및 합계 계산
ansan_gu = ["안산시상록구           ", "안산시단원구           "]
ansan_data = inf4[inf4['구  분'].isin(ansan_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
ansan_row = pd.DataFrame([['안산시'] + ansan_data.tolist()], columns=inf4.columns)

# 창원시 관련 행 필터링 및 합계 계산
goyang_gu = ["고양시덕양구           ", "고양시일산동구", "고양시일산서구"]
goyang_data = inf4[inf4['구  분'].isin(goyang_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
goyang_row = pd.DataFrame([['고양시'] + goyang_data.tolist()], columns=inf4.columns)

# 창원시 관련 행 필터링 및 합계 계산
yongin_gu = ["용인시처인구", "용인시기흥구", "용인시수지구"]
yongin_data = inf4[inf4['구  분'].isin(yongin_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
yongin_row = pd.DataFrame([['용인시'] + yongin_data.tolist()], columns=inf4.columns)

# 창원시 행 추가 및 기존 구 삭제
inf4 = pd.concat([inf4[~inf4['구  분'].isin(ansan_gu)], ansan_row], ignore_index=True)
inf4 = pd.concat([inf4[~inf4['구  분'].isin(goyang_gu)], goyang_row], ignore_index=True)
inf4 = pd.concat([inf4[~inf4['구  분'].isin(yongin_gu)], yongin_row], ignore_index=True)
inf4 = inf4.rename(columns={'구  분': '지역'})


inf4 = inf4.rename(columns={'구  분': '지역'})
# inf4.columns = ['구  분', '진료실인원수(관외)', '입내원일수(관외)', '요양급여일수(관외)', '진료비(관외)', '급여비(관외)']
inf4

,지역,계,0-4세,5-9세,10-14세,15-19세,20-24세,25-29세,30-34세,35-39세,40-44세,45-49세,50-54세,55-59세,60-64세,65-69세,70-74세,75-79세,80세 이상
0,광명시,322688,11294,14752,15430,17683,20137,21406,20859,25764,26106,30226,27817,26491,23317,14828,10338,7802,8438
1,평택시,533575,22615,26764,25671,27702,33787,39131,38067,45742,44641,49234,45468,41457,31597,19512,14831,12566,14790
2,동두천시,95374,2866,4120,4203,4794,5821,5823,4871,6221,6691,8305,8170,8138,7414,4897,4460,4109,4471
3,과천시,58858,1953,2573,2866,3471,4020,4018,3797,4186,3985,5421,5408,5108,4070,2517,1862,1548,2055
4,구리시,200048,7328,9059,8705,10392,13664,14132,12060,15885,15539,18245,18300,17768,14106,8526,6293,4987,5059
5,남양주시,709312,28370,39298,38316,39390,43585,41127,37659,57196,62029,68313,59677,55160,46283,30837,24021,18752,19299
6,오산시,236644,11495,14367,12753,12370,14248,17246,18449,24530,22384,21606,18407,15939,12055,7248,5282,4148,4117
7,시흥시,512586,22919,26079,24244,26331,33929,38031,38115,47483,44519,48922,47875,41941,28947,15384,10361,8146,9360
8,군포시,283322,10380,12611,12798,15309,18301,20716,19712,22083,21292,25942,25122,25094,20017,11209,8137,6462,8137
9,의왕시,162992,6047,7117,6745,8399,11215,11791,10506,12111,11314,14062,14788,15316,12814,7199,5011,3809,4748
10,하남시,275869,13697,15962,12223,11318,14668,18180,20011,27882,25041,22853,20248,21046,19325,12827,8925,5637,6026
11,파주시,465316,19893,25656,24201,24451,27275,31563,32202,39450,38035,42793,37218,34037,28110,17692,14976,13025,14739
12,이천시,223063,8969,11152,10770,11957,14075,17132,15466,17430,17082,18674,18186,17931,14896,9349,6924,5854,7216
13,안성시,197484,6650,8886,8904,9706,12058,12726,12472,15436,15284,17045,16373,16393,14410,9747,7190,6122,8082
14,김포시,459769,23504,29033,23743,21165,24467,29415,32261,46504,43491,40023,33775,32085,27397,17940,13952,10107,10907
15,화성시,869053,49161,58064,50075,43120,47604,62387,73408,93907,85727,77895,62313,53680,40601,25061,17608,12942,15500
16,광주시,385848,17543,18959,16314,17271,22167,25357,27287,36947,32330,34064,31873,31452,27475,17219,12186,8687,8717
17,양주시,229083,8599,11357,11546,12427,14040,14414,13082,16924,18053,21427,19279,18244,16199,10423,8696,6926,7447
18,포천시,159782,4137,5333,5823,7418,10607,11871,9660,9380,9750,12874,14718,15999,14505,8335,6747,5659,6966
19,여주시,113933,3337,4417,4566,5392,6578,6562,5736,7156,7443,8991,9880,10754,10049,7195,5321,4733,5823
20,연천군,44239,1429,1519,1463,1867,2586,3146,2190,2301,2215,2891,3334,4121,4285,2826,2668,2404,2994
21,가평군,63147,1617,2023,2195,2691,3208,3118,2810,3328,3602,4616,5418,6492,6707,4621,3532,3239,3930
22,양평군,118175,3166,4440,4780,4978,5470,5464,4965,6574,7319,9175,9577,11681,12150,9017,6925,5706,6788
23,강원,1549503,48013,61759,64609,79204,97541,87627,77174,96676,102911,126678,130807,141153,134811,88332,69491,65707,77010
24,춘천시,282783,9722,12635,12736,15228,19355,18084,15899,19494,19523,23599,23493,23834,21844,13571,10697,10449,12620
25,원주시,351485,12601,16254,17197,19548,23421,22338,20517,25496,26551,31390,30639,29868,25867,15432,10966,10467,12933
26,강릉시,214272,6023,8035,8837,11387,14136,11642,9725,12898,14684,18411,17865,19173,18602,12815,10300,9036,10703
27,동해시,90951,2828,4060,4190,4909,5287,4379,3974,5815,6700,8279,7827,7921,7615,5308,4125,3791,3943
28,태백시,43242,1130,1734,1829,2230,2274,1623,1637,2593,3085,3508,3665,3871,4209,3114,2514,2169,2057
29,속초시,82564,2638,3330,3343,4436,5018,4363,4163,5334,5582,7127,7486,7831,7181,4513,3628,3051,3540
30,삼척시,67653,1833,2303,2376,3238,5136,3013,2764,3700,4135,5213,5547,6299,6135,4465,3699,3498,4299
31,홍천군,69700,1808,2250,2440,3090,3511,3355,3013,3542,3774,4813,5815,7365,7807,5058,3795,3539,4725
32,횡성군,47087,1002,1289,1513,2183,2284,1950,1725,2111,2233,3122,4009,5124,5595,3767,2855,2779,3546
33,영월군,39017,729,1053,1188,1821,2076,1419,1310,1718,2017,2874,3433,4179,4353,3183,2391,2480,2793
34,평창군,42334,851,1188,1404,1745,1921,1638,1517,1987,2361,3189,3788,4678,4928,3291,2650,2390,2808
35,정선군,37001,752,1146,1238,1458,1739,1336,1493,1924,2256,2824,3241,3960,4089,2810,2243,2199,2293
36,철원군,45692,1694,1753,1829,2224,3128,3269,2428,2477,2618,3248,3483,4026,3765,2494,2439,2412,2405
37,화천군,25217,970,931,862,1066,1797,2266,1552,1409,1322,1566,1866,2212,2123,1348,1183,1300,1444
38,양구군,23016,938,958,867,1269,1506,1837,1330,1429,1230,1462,1662,2085,1960,1158,963,1134,1228
39,인제군,31938,1299,1297,1159,1238,1994,2290,1904,2088,1927,2100,2421,3114,2941,1791,1352,1395,1628
40,고성군,27618,608,743,756,1023,1624,1712,1158,1226,1305,1933,2246,2782,2867,1995,1800,1800,2040
41,양양군,27933,587,800,845,1111,1334,1113,1065,1435,1608,2020,2321,2831,2930,2219,1891,1818,2005
42,안산시,710915,22634,27632,29953,39630,54098,58933,49469,52651,53568,69239,72158,65481,45718,24485,16435,13060,15771
43,고양시,1078782,37294,47924,49253,59679,73875,77697,66027,79002,82727,105488,100481,93666,70456,40199,31979,28191,34844
44,용인시,1076848,45081,60657,60437,62088,68252,67014,64164,90433,96762,107044,88306,73459,58982,42025,35711,27456,28977

In [8]:
inf5 = pd.read_excel("01_시군구별 제1권-서울 인천 경기 강원_2019년.xlsx",sheet_name='98p심평원')


# 1. 3번 행을 칼럼명으로 변경
inf5.columns = inf5.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf5 = inf5.drop(index=[0, 1, 2, 3, 4])

# 3. 46, 47, 48번 행 삭제
inf5 = inf5.drop(index=[54, 55, 56])

# 인덱스 리셋
inf5 = inf5.reset_index(drop=True)


inf5.columns = [col.split('\n')[0] for col in inf5.columns]

inf5 = inf5.drop(columns = [ "조  산  원", "Division"])

# 창원시 관련 행 필터링 및 합계 계산
suwon_gu = ["수원시장안구           ", "수원시권선구           ", "수원시팔달구           ", "수원시영통구           "]
suwon_data = inf5[inf5['구      분'].isin(suwon_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
suwon_row = pd.DataFrame([['수원시'] + suwon_data.tolist()], columns=inf5.columns)

# 창원시 관련 행 필터링 및 합계 계산
sungnam_gu = ["성남시수정구           ", "성남시중원구           ", "성남시분당구           "]
sungnam_data = inf5[inf5['구      분'].isin(sungnam_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
sungnam_row = pd.DataFrame([['성남시'] + sungnam_data.tolist()], columns=inf5.columns)

# 창원시 관련 행 필터링 및 합계 계산
anyang_gu = ["안양시만안구           ", "안양시동안구           "]
anyang_data = inf5[inf5['구      분'].isin(anyang_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
anyang_row = pd.DataFrame([['안양시'] + anyang_data.tolist()], columns=inf5.columns)

# 창원시 행 추가 및 기존 구 삭제
inf5 = pd.concat([inf5[~inf5['구      분'].isin(suwon_gu)], suwon_row], ignore_index=True)
inf5 = pd.concat([inf5[~inf5['구      분'].isin(sungnam_gu)], sungnam_row], ignore_index=True)
inf5 = pd.concat([inf5[~inf5['구      분'].isin(anyang_gu)], anyang_row], ignore_index=True)


# 창원시 관련 구 이름
changwon_gu = ['보  건  소', '보건지소','보건진료소', '보건의료원']

# 예시: 'col1', 'col2', 'col3'의 값을 합쳐 'new_col' 생성
inf5['보건소'] = inf5[['보  건  소', '보건지소','보건진료소', '보건의료원']].sum(axis=1)

inf5 = inf5.drop(columns = [  '보  건  소', '보건지소','보건진료소', '보건의료원'])

inf5 = inf5.rename(columns={'구      분': '지역'})

inf5['지역'] = inf5['지역'] + ' ' + inf5.groupby('지역').cumcount().replace(0, '').astype(str)


inf5

,지역,계,상급종합병원,종합병원,병 원,요양병원,의 원,치과병원,치과의원,한방병원,한 의 원,약 국,보건소
0,서울,22739,13,44,228,124,8628,65,4836,53,3617,5095,33
1,종로구,668,2,2,3,0,193,1,163,0,131,172,1
2,중구,728,0,2,4,0,241,6,211,1,95,167,1
3,용산구,435,0,1,2,0,135,0,106,0,62,127,1
4,성동구,593,1,0,6,3,213,1,127,0,93,148,1
5,광진구,723,1,1,5,3,268,2,154,0,118,170,1
6,동대문구,832,1,3,14,9,260,4,157,1,157,224,1
7,중랑구,689,0,3,12,3,237,0,148,0,108,177,1
8,성북구,729,1,0,6,7,251,1,149,0,113,200,1
9,강북구,628,0,1,8,6,225,1,124,0,96,166,1
10,도봉구,485,0,1,8,6,163,1,103,2,85,115,1
11,노원구,952,0,3,7,6,350,3,195,2,159,225,2
12,은평구,874,0,2,11,6,320,1,175,2,145,209,3
13,서대문구,587,1,1,5,3,208,2,125,1,89,150,2
14,마포구,929,0,0,2,3,371,3,200,1,150,198,1
15,양천구,816,0,3,5,5,279,4,177,3,150,189,1
16,강서구,1080,0,4,17,4,394,3,219,4,191,243,1
17,구로구,741,1,1,8,9,261,1,166,2,110,180,2
18,금천구,475,0,1,6,4,158,0,106,3,78,118,1
19,영등포구,1001,0,7,8,12,339,1,238,2,149,244,1
20,동작구,762,1,1,5,3,259,2,172,1,132,185,1
21,관악구,909,0,1,10,3,319,1,204,2,153,215,1
22,서초구,1465,1,0,12,4,630,5,315,6,252,236,3
23,강남구,3088,2,2,33,9,1639,15,566,11,366,444,1
24,송파구,1527,1,1,16,10,561,4,318,4,250,360,2
25,강동구,1023,0,3,15,6,354,3,218,5,185,233,1
26,인천,4497,3,16,62,71,1573,9,911,33,658,1097,63
27,중구 1,177,1,1,2,4,57,0,36,1,16,55,4
28,동구,122,0,2,0,0,42,0,25,0,18,34,1
29,미추홀구,643,0,2,13,14,211,1,124,7,93,175,3
30,연수구,467,0,1,4,4,177,2,101,1,76,99,2
31,남동구,955,1,0,14,18,355,1,189,7,148,221,1
32,부평구,847,1,2,10,8,308,4,170,8,124,210,2
33,계양구,477,0,2,8,10,160,0,105,4,71,114,2
34,서구,670,0,5,8,9,240,1,144,4,94,164,1
35,강화군,107,0,1,2,4,20,0,14,1,16,22,27
36,옹진군,32,0,0,1,0,3,0,3,0,2,3,20
37,경기,20491,5,59,277,345,7065,37,4204,65,3146,4950,331
38,의정부시,729,0,4,13,10,273,2,143,3,95,185,1
39,부천시,1432,1,4,23,31,510,4,282,9,218,346,3
40,수원시,2082,1,3,33,25,731,1,444,4,353,483,4
41,성남시,2095,1,6,17,16,788,7,461,4,343,448,4
42,안양시,1099,1,2,14,9,382,1,252,2,183,249,2

In [9]:
inf6 = pd.read_excel("01_시군구별 제1권-서울 인천 경기 강원_2019년.xlsx",sheet_name='100p')


# 1. 3번 행을 칼럼명으로 변경
inf6.columns = inf6.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf6 = inf6.drop(index=[0, 1, 2, 3, 4])

# 3. 46, 47, 48번 행 삭제
inf6 = inf6.drop(index=[55, 56, 57])

# 인덱스 리셋
inf6 = inf6.reset_index(drop=True)


inf6.columns = [col.split('\n')[0] for col in inf6.columns]

inf6 = inf6.drop(columns = [ "조  산  원", "Division"])

# 창원시 관련 행 필터링 및 합계 계산
ansan_gu = ["안산시상록구           ", "안산시단원구           "]
ansan_data = inf6[inf6['구      분'].isin(ansan_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
ansan_row = pd.DataFrame([['안산시'] + ansan_data.tolist()], columns=inf6.columns)

# 창원시 관련 행 필터링 및 합계 계산
goyang_gu = ["고양시덕양구           ", "고양시일산동구", "고양시일산서구"]
goyang_data = inf6[inf6['구      분'].isin(goyang_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
goyang_row = pd.DataFrame([['고양시'] + goyang_data.tolist()], columns=inf6.columns)

# 창원시 관련 행 필터링 및 합계 계산
yongin_gu = ["용인시처인구", "용인시기흥구", "용인시수지구"]
yongin_data = inf6[inf6['구      분'].isin(yongin_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
yongin_row = pd.DataFrame([['용인시'] + yongin_data.tolist()], columns=inf6.columns)

# 창원시 행 추가 및 기존 구 삭제
inf6 = pd.concat([inf6[~inf6['구      분'].isin(ansan_gu)], ansan_row], ignore_index=True)
inf6 = pd.concat([inf6[~inf6['구      분'].isin(goyang_gu)], goyang_row], ignore_index=True)
inf6 = pd.concat([inf6[~inf6['구      분'].isin(yongin_gu)], yongin_row], ignore_index=True)
inf6 = inf6.rename(columns={'구      분': '지역'})



# 창원시 관련 구 이름
changwon_gu = ['보  건  소', '보건지소','보건진료소', '보건의료원']

# 예시: 'col1', 'col2', 'col3'의 값을 합쳐 'new_col' 생성
inf6['보건소'] = inf6[['보  건  소', '보건지소','보건진료소', '보건의료원']].sum(axis=1)

inf6 = inf6.drop(columns = [  '보  건  소', '보건지소','보건진료소', '보건의료원'])

inf6 = inf6.rename(columns={'구      분': '지역'})

inf6['지역'] = inf6['지역'] + ' ' + inf6.groupby('지역').cumcount().replace(0, '').astype(str)


inf6

,지역,계,상급종합병원,종합병원,병 원,요양병원,의 원,치과병원,치과의원,한방병원,한 의 원,약 국,보건소
0,광명시,530,0,1,5,5,205,0,114,0,81,118,1
1,평택시,765,0,4,11,7,253,0,148,1,111,207,22
2,동두천시,140,0,0,1,10,41,0,26,0,18,43,1
3,과천시,92,0,0,0,NaN,38,1,17,0,14,21,1
4,구리시,418,0,1,9,5,146,0,93,0,66,95,3
5,남양주시,912,0,3,12,19,308,0,194,0,139,225,11
6,오산시,314,0,2,6,6,103,1,70,1,41,83,1
7,시흥시,622,0,3,4,13,226,2,131,9,74,154,6
8,군포시,429,0,2,3,8,140,2,97,0,68,107,2
9,의왕시,189,0,0,2,4,62,1,44,0,30,43,2
10,하남시,381,0,0,7,4,148,0,76,0,58,87,1
11,파주시,573,0,1,11,20,184,0,114,1,85,143,14
12,이천시,333,0,1,4,8,108,1,55,0,44,89,23
13,안성시,271,0,2,2,10,74,1,47,0,33,77,25
14,김포시,604,0,2,15,7,200,0,131,6,94,135,14
15,화성시,1001,0,3,12,12,339,0,204,3,148,252,28
16,광주시,406,0,1,2,7,131,1,74,0,69,105,16
17,양주시,252,0,0,5,12,80,0,47,0,30,72,6
18,포천시,209,0,2,2,6,62,0,36,0,24,54,23
19,여주시,191,0,0,4,6,50,0,33,0,27,48,23
20,연천군,69,0,0,0,1,13,0,11,0,7,22,15
21,가평군,114,0,0,3,3,26,0,20,1,16,24,21
22,양평군,178,0,0,2,8,41,0,29,1,32,38,27
23,강원,2519,1,14,45,32,769,4,388,1,362,659,244
24,춘천시,472,0,2,9,7,161,0,81,0,69,119,24
25,원주시,597,1,1,18,6,197,2,94,1,103,156,18
26,강릉시,347,0,4,3,4,114,1,56,0,59,89,17
27,동해시,140,0,1,2,3,50,0,26,0,17,39,2
28,태백시,64,0,1,1,0,23,0,9,0,7,20,3
29,속초시,165,0,2,0,2,64,1,30,0,24,41,1
30,삼척시,94,0,1,1,1,27,0,12,0,10,27,15
31,홍천군,115,0,1,2,3,30,0,16,0,11,25,27
32,횡성군,69,0,0,1,1,13,0,7,0,13,17,17
33,영월군,56,0,1,1,1,12,0,6,0,6,16,13
34,평창군,84,0,0,0,2,17,0,13,0,10,20,22
35,정선군,53,0,0,2,0,9,0,5,0,4,14,19
36,철원군,70,0,0,1,1,18,0,8,0,8,22,12
37,화천군,36,0,0,0,0,8,0,5,0,4,8,11
38,양구군,33,0,0,3,0,5,0,5,0,4,8,8
39,인제군,46,0,0,1,1,8,0,6,0,5,14,11
40,고성군,41,0,0,0,0,7,0,5,0,4,12,13
41,양양군,37,0,0,0,0,6,0,4,0,4,12,11
42,안산시,1024,1,3,21,17,357,4,187,15,140,270,8
43,고양시,1608,0,6,24,31,547,6,305,3,277,406,3
44,용인시,1429,0,3,10,25,499,2,319,2,228,321,20

In [10]:
inf7 = pd.read_excel("01_시군구별 제1권-서울 인천 경기 강원_2019년.xlsx",sheet_name='102p')


# 1. 3번 행을 칼럼명으로 변경
inf7.columns = inf7.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf7 = inf7.drop(index=[0, 1, 2, 3, 4, 5])

# 3. 46, 47, 48번 행 삭제
inf7 = inf7.drop(index=[55, 56, 57])

# 인덱스 리셋
inf7 = inf7.reset_index(drop=True)
inf7 = inf7.loc[:, ~inf7.columns.isna()]

inf7.columns = [col.split('\n')[0] for col in inf7.columns]
inf7.columns = [col.split('physical')[0] for col in inf7.columns]
inf7 = inf7.drop(columns = [ "Division"])

# 창원시 관련 행 필터링 및 합계 계산
suwon_gu = ["수원시장안구           ", "수원시권선구           ", "수원시팔달구           ", "수원시영통구           "]
suwon_data = inf7[inf7['구   분'].isin(suwon_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
suwon_row = pd.DataFrame([['수원시'] + suwon_data.tolist()], columns=inf7.columns)

# 창원시 관련 행 필터링 및 합계 계산
sungnam_gu = ["성남시수정구           ", "성남시중원구           ", "성남시분당구           "]
sungnam_data = inf7[inf7['구   분'].isin(sungnam_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
sungnam_row = pd.DataFrame([['성남시'] + sungnam_data.tolist()], columns=inf7.columns)

# 창원시 관련 행 필터링 및 합계 계산
anyang_gu = ["안양시만안구           ", "안양시동안구           "]
anyang_data = inf7[inf7['구   분'].isin(anyang_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
anyang_row = pd.DataFrame([['안양시'] + anyang_data.tolist()], columns=inf7.columns)

# 창원시 행 추가 및 기존 구 삭제
inf7 = pd.concat([inf7[~inf7['구   분'].isin(suwon_gu)], suwon_row], ignore_index=True)
inf7 = pd.concat([inf7[~inf7['구   분'].isin(sungnam_gu)], sungnam_row], ignore_index=True)
inf7 = pd.concat([inf7[~inf7['구   분'].isin(anyang_gu)], anyang_row], ignore_index=True)




inf7 = inf7.rename(columns={'구   분': '지역'})

inf7['지역'] = inf7['지역'] + ' ' + inf7.groupby('지역').cumcount().replace(0, '').astype(str)

inf7

,지역,계,의 사,치 과 의 사,한 의 사,간호사,약 사,물리치료사,작업치료사,사회복지사
0,서울,114861,30359,7308,5018,52727,9385,8240,1269,555
1,종로구,7447,2300,439,168,3732,495,230,58,25
2,중구,2865,816,275,131,1150,277,202,2,12
3,용산구,2041,574,138,75,957,182,100,8,7
4,성동구,2646,734,167,110,1169,249,185,23,9
5,광진구,3183,927,195,142,1363,298,209,23,26
6,동대문구,4864,1133,369,319,2121,369,419,100,34
7,중랑구,3024,666,190,141,1305,287,346,56,33
8,성북구,3662,951,214,146,1648,330,284,72,17
9,강북구,1797,428,164,120,475,243,292,58,17
10,도봉구,1903,400,128,108,814,201,195,34,23
11,노원구,4669,1258,252,202,2201,410,316,15,15
12,은평구,3254,790,222,176,1198,374,410,55,29
13,서대문구,6511,1441,372,134,3976,375,166,28,19
14,마포구,1961,557,254,192,361,289,268,31,9
15,양천구,3680,898,277,213,1552,342,328,55,15
16,강서구,4405,931,281,245,1970,404,482,74,18
17,구로구,4202,1027,226,145,1932,345,396,103,28
18,금천구,1549,325,133,103,528,171,245,30,14
19,영등포구,5674,1389,306,196,2708,447,475,102,51
20,동작구,3962,962,232,160,2026,365,188,14,15
21,관악구,2490,566,253,188,779,308,334,52,10
22,서초구,7240,1990,488,366,3425,488,411,50,22
23,강남구,15679,5212,924,603,7121,898,782,93,46
24,송파구,10207,2680,441,330,5394,743,531,60,28
25,강동구,5946,1404,368,305,2822,495,446,73,33
26,인천,24081,5071,1298,997,11639,1915,2415,508,238
27,중구 1,2438,557,48,47,1586,120,64,6,10
28,동구,580,116,34,20,280,55,69,2,4
29,미추홀구,3023,601,157,140,1355,273,374,83,40
30,연수구,1645,391,141,102,568,170,228,36,9
31,남동구,5532,1183,286,214,2652,398,578,171,50
32,부평구,4411,904,254,176,2087,356,471,118,45
33,계양구,2433,453,136,124,1177,199,272,46,26
34,서구,3567,753,205,128,1766,304,319,46,46
35,강화군,361,78,24,38,145,37,31,0,8
36,옹진군,91,35,13,8,23,3,9,0,0
37,경기,91723,21210,5788,4512,39694,8797,8915,1869,938
38,의정부시,3846,876,196,134,1757,332,362,147,42
39,부천시,7796,1689,406,356,3778,637,672,167,91
40,수원시,11106,2613,609,487,5364,922,852,174,85
41,성남시,11728,3008,684,484,5435,922,931,194,70
42,안양시,4702,1170,328,232,1948,429,444,114,37

In [11]:
inf8 = pd.read_excel("01_시군구별 제1권-서울 인천 경기 강원_2019년.xlsx",sheet_name='104p')


# 1. 3번 행을 칼럼명으로 변경
inf8.columns = inf8.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf8 = inf8.drop(index=[0, 1, 2, 3, 4, 5])

# 3. 46, 47, 48번 행 삭제
inf8 = inf8.drop(index=[56, 57, 58])

# 인덱스 리셋
inf8 = inf8.reset_index(drop=True)
inf8 = inf8.loc[:, ~inf8.columns.isna()]

inf8.columns = [col.split('\n')[0] for col in inf8.columns]
inf8.columns = [col.split('physical')[0] for col in inf8.columns]
inf8 = inf8.drop(columns = [ "Division"])

# 창원시 관련 행 필터링 및 합계 계산
ansan_gu = ["안산시상록구           ", "안산시단원구           "]
ansan_data = inf8[inf8['구   분'].isin(ansan_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
ansan_row = pd.DataFrame([['안산시'] + ansan_data.tolist()], columns=inf8.columns)

# 창원시 관련 행 필터링 및 합계 계산
goyang_gu = ["고양시덕양구           ", "고양시일산동구", "고양시일산서구"]
goyang_data = inf8[inf8['구   분'].isin(goyang_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
goyang_row = pd.DataFrame([['고양시'] + goyang_data.tolist()], columns=inf8.columns)

# 창원시 관련 행 필터링 및 합계 계산
yongin_gu = ["용인시처인구", "용인시기흥구", "용인시수지구"]
yongin_data = inf8[inf8['구   분'].isin(yongin_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
yongin_row = pd.DataFrame([['용인시'] + yongin_data.tolist()], columns=inf8.columns)

# 창원시 행 추가 및 기존 구 삭제
inf8 = pd.concat([inf8[~inf8['구   분'].isin(ansan_gu)], ansan_row], ignore_index=True)
inf8 = pd.concat([inf8[~inf8['구   분'].isin(goyang_gu)], goyang_row], ignore_index=True)
inf8 = pd.concat([inf8[~inf8['구   분'].isin(yongin_gu)], yongin_row], ignore_index=True)
inf8 = inf8.rename(columns={'구   분': '지역'})



inf8 = inf8.rename(columns={'구   분': '지역'})

inf8['지역'] = inf8['지역'] + ' ' + inf8.groupby('지역').cumcount().replace(0, '').astype(str)

inf8

,지역,계,의 사,치 과 의 사,한 의 사,간호사,약 사,물리치료사,작업치료사,사회복지사
0,광명시,1778,469,157,103,565,202,236,35,11
1,평택시,2655,625,203,144,1020,323,296,26,18
2,동두천시,598,124,35,35,237,71,61,17,18
3,과천시,170,48,26,18,17,33,28,0,0
4,구리시,2125,500,117,80,939,177,246,52,14
5,남양주시,2743,660,238,183,885,361,336,43,37
6,오산시,1288,274,99,61,531,137,136,36,14
7,시흥시,2225,459,167,130,830,269,302,47,21
8,군포시,1710,398,136,90,698,187,157,25,19
9,의왕시,571,125,56,36,203,68,54,3,26
10,하남시,911,239,99,75,191,133,149,16,9
11,파주시,1993,416,148,117,753,236,252,42,29
12,이천시,1029,258,91,64,350,148,96,4,18
13,안성시,955,192,61,55,403,124,92,9,19
14,김포시,2353,518,173,144,946,264,248,41,19
15,화성시,3775,957,258,207,1471,450,369,31,32
16,광주시,1356,272,109,95,442,176,196,48,18
17,양주시,970,230,69,54,336,112,114,31,24
18,포천시,729,187,50,33,286,86,65,9,13
19,여주시,583,128,38,51,198,73,70,11,14
20,연천군,160,37,18,12,49,25,18,0,1
21,가평군,318,60,23,28,136,35,29,1,6
22,양평군,659,109,38,50,216,66,117,54,9
23,강원,12115,2719,669,528,6043,1005,915,140,96
24,춘천시,2988,743,117,93,1561,213,192,37,32
25,원주시,3422,783,169,150,1685,249,287,71,28
26,강릉시,2298,471,159,69,1291,168,117,12,11
27,동해시,635,117,33,23,321,55,66,14,6
28,태백시,307,51,13,10,179,27,24,2,1
29,속초시,537,120,40,27,247,56,40,2,5
30,삼척시,333,69,21,17,152,35,36,1,2
31,홍천군,374,92,20,17,163,39,38,0,5
32,횡성군,145,31,11,20,40,19,23,1,0
33,영월군,190,42,10,11,95,20,10,0,2
34,평창군,154,37,16,17,48,22,13,0,1
35,정선군,155,30,8,10,79,16,11,0,1
36,철원군,164,38,12,13,56,28,15,0,2
37,화천군,81,23,8,12,26,8,4,0,0
38,양구군,91,25,10,11,26,9,10,0,0
39,인제군,89,22,9,11,19,15,13,0,0
40,고성군,73,12,7,8,24,13,9,0,0
41,양양군,79,13,6,9,31,13,7,0,0
42,안산시,5853,1228,267,246,2854,472,607,123,56
43,고양시,10190,2252,471,407,5144,795,811,206,104
44,용인시,4848,1089,418,301,1712,532,569,163,64

In [12]:
inf9 = pd.read_excel("01_시군구별 제1권-서울 인천 경기 강원_2019년.xlsx",sheet_name='106p')


# 1. 3번 행을 칼럼명으로 변경
inf9.columns = inf9.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf9 = inf9.drop(index=[0, 1, 2, 3, 4, 5, 6])

# 3. 46, 47, 48번 행 삭제
inf9 = inf9.drop(index=[56, 57, 58])

# 인덱스 리셋
inf9 = inf9.reset_index(drop=True)

inf9.iloc[:, [3, 4]] = inf9.iloc[:, [4, 3]].values
inf9.iloc[:, [15, 16]] = inf9.iloc[:, [16, 15]].values

inf9 = inf9.loc[:, ~inf9.columns.isna()]

inf9.columns = [col.split('\n')[0] for col in inf9.columns]
inf9.columns = [col.split(' Inpatient room')[0] for col in inf9.columns]
inf9.columns = [col.split('Intensive Care Unit')[0] for col in inf9.columns]
inf9 = inf9.drop(columns = [ '계                                          Total',  '정신과폐쇄',
'격리병실                           Isolation room', '무균치료실                   Aseptic room', "Division"])

# 창원시 관련 행 필터링 및 합계 계산
suwon_gu = ["수원시장안구           ", "수원시권선구           ", "수원시팔달구           ", "수원시영통구           "]
suwon_data = inf9[inf9['구   분'].isin(suwon_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
suwon_row = pd.DataFrame([['수원시'] + suwon_data.tolist()], columns=inf9.columns)

# 창원시 관련 행 필터링 및 합계 계산
sungnam_gu = ["성남시수정구           ", "성남시중원구           ", "성남시분당구           "]
sungnam_data = inf9[inf9['구   분'].isin(sungnam_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
sungnam_row = pd.DataFrame([['성남시'] + sungnam_data.tolist()], columns=inf9.columns)

# 창원시 관련 행 필터링 및 합계 계산
anyang_gu = ["안양시만안구           ", "안양시동안구           "]
anyang_data = inf9[inf9['구   분'].isin(anyang_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
anyang_row = pd.DataFrame([['안양시'] + anyang_data.tolist()], columns=inf9.columns)

# 창원시 행 추가 및 기존 구 삭제
inf9 = pd.concat([inf9[~inf9['구   분'].isin(suwon_gu)], suwon_row], ignore_index=True)
inf9 = pd.concat([inf9[~inf9['구   분'].isin(sungnam_gu)], sungnam_row], ignore_index=True)
inf9 = pd.concat([inf9[~inf9['구   분'].isin(anyang_gu)], anyang_row], ignore_index=True)


inf9 = inf9.rename(columns={'구   분': '지역'})

inf9['지역'] = inf9['지역'] + ' ' + inf9.groupby('지역').cumcount().replace(0, '').astype(str)
inf9.at[39, '지역'] = '부천시'
inf9

                         지역  일반입원실  중환자실
0                       서울    81044    242
1     종로구                      3074     11
2    중구                        1227      5
3     용산구                       853      2
4     성동구                      1790      4
5     광진구                      2310      4
6      동대문구                    4841      8
7     중랑구                      2691      6
8     성북구                      3361     17
9     강북구                      2207      2
10    도봉구                      1987      2
11    노원구                      3278      8
12    은평구                      3263      8
13     서대문구                    3415     11
14    마포구                       779      0
15    양천구                      2504     27
16    강서구                      3714     50
17    구로구                      4355      5
18    금천구                      1927      2
19     영등포구                    5168     10
20    동작구                      2548      8
21    관악구                      2325      3
22    서초구                      3356      8
23    강남구                      8317     20
24    송파구                      6211     12
25    강동구                      5543      9
26                      인천    30054     47
27  중구                    1    1980      9
28   동구                         704      2
29                    미추홀구     5498      4
30    연수구                      1841      2
31    남동구                      6453      8
32    부평구                      4603      7
33    계양구                      3351      2
34   서구                        4801     10
35    강화군                       749      3
36    옹진군                        74      0
37                      경기   117616    184
38     의정부시                    4526      9
39                      부천시   10526     20
40                     수원시    10422     27
41                     성남시     9155     43
42                     안양시     4264     15

In [13]:
inf10 = pd.read_excel("01_시군구별 제1권-서울 인천 경기 강원_2019년.xlsx",sheet_name='108p')


# 1. 3번 행을 칼럼명으로 변경
inf10.columns = inf10.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf10 = inf10.drop(index=[0, 1, 2, 3, 4, 5, 6])

# 3. 46, 47, 48번 행 삭제
inf10 = inf10.drop(index=[57, 58, 59])

# 인덱스 리셋
inf10 = inf10.reset_index(drop=True)

inf10.iloc[:, [3, 4]] = inf10.iloc[:, [4, 3]].values
inf10.iloc[:, [15, 16]] = inf10.iloc[:, [16, 15]].values

inf10 = inf10.loc[:, ~inf10.columns.isna()]

inf10.columns = [col.split('\n')[0] for col in inf10.columns]
inf10.columns = [col.split(' Inpatient room')[0] for col in inf10.columns]
inf10.columns = [col.split('Intensive Care Unit')[0] for col in inf10.columns]
inf10 = inf10.drop(columns = [ '계                                          Total',  '정신과폐쇄',
'격리병실                           Isolation room', '무균치료실                   Aseptic room', "Division"])

# 창원시 관련 행 필터링 및 합계 계산
ansan_gu = ["안산시상록구           ", "안산시단원구           "]
ansan_data = inf10[inf10['구   분'].isin(ansan_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
ansan_row = pd.DataFrame([['안산시'] + ansan_data.tolist()], columns=inf10.columns)

# 창원시 관련 행 필터링 및 합계 계산
goyang_gu = ["고양시덕양구           ", "고양시일산동구", "고양시일산서구"]
goyang_data = inf10[inf10['구   분'].isin(goyang_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
goyang_row = pd.DataFrame([['고양시'] + goyang_data.tolist()], columns=inf10.columns)

# 창원시 관련 행 필터링 및 합계 계산
yongin_gu = ["용인시처인구", "용인시기흥구", "용인시수지구"]
yongin_data = inf10[inf10['구   분'].isin(yongin_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
yongin_row = pd.DataFrame([['용인시'] + yongin_data.tolist()], columns=inf10.columns)

# 창원시 행 추가 및 기존 구 삭제
inf10 = pd.concat([inf10[~inf10['구   분'].isin(ansan_gu)], ansan_row], ignore_index=True)
inf10 = pd.concat([inf10[~inf10['구   분'].isin(goyang_gu)], goyang_row], ignore_index=True)
inf10 = pd.concat([inf10[~inf10['구   분'].isin(yongin_gu)], yongin_row], ignore_index=True)
inf10 = inf10.rename(columns={'구   분': '지역'})

inf10 = inf10.rename(columns={'구   분': '지역'})

inf10

                      지역 일반입원실  중환자실
0   광명시                    2099      2
1   평택시                    3676      4
2    동두천시                  2141      0
3   과천시                       0      0
4   구리시                    2416      4
5    남양주시                  5400      5
6   오산시                    2170      2
7   시흥시                    4316      3
8   군포시                    2141      2
9   의왕시                     994      0
10  하남시                    1222      0
11  파주시                    4393      1
12  이천시                    1821      1
13  안성시                    1867      2
14  김포시                    3255      4
15  화성시                    4611      7
16                   광주시   2104      1
17  양주시                    2375      0
18  포천시                    1376      2
19  여주시                    1567      0
20  연천군                     328      0
21  가평군                     626      0
22  양평군                    1267      0
23                    강원  14803     52
24  춘천시                    3317     22
25  원주시                    4173     14
26  강릉시                    2038      7
27  동해시                    1228      2
28  태백시                     554      1
29  속초시                     797      2
30  삼척시                     397      1
31  홍천군                     692      1
32  횡성군                     180      0
33  영월군                     331      1
34  평창군                     196      0
35  정선군                     208      1
36  철원군                     349      0
37  화천군                      42      0
38  양구군                     163      0
39  인제군                     138      0
40  고성군                       0      0
41  양양군                       0      0
42                   안산시   8538      7
43                   고양시  10985     20
44                   용인시   7035      3

In [14]:
inf11 = pd.read_excel("01_시군구별 제1권-서울 인천 경기 강원_2019년.xlsx",sheet_name='110p')


# 1. 3번 행을 칼럼명으로 변경
inf11.columns = inf11.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf11 = inf11.drop(index=[0, 1, 2, 3, 4])

# 3. 46, 47, 48번 행 삭제
inf11 = inf11.drop(index=[54, 55, 56])

# 인덱스 리셋
inf11 = inf11.reset_index(drop=True)


inf11.columns = [col.split('\n')[0] for col in inf11.columns]

inf11 = inf11.drop(columns = [  '계', '유         방',
       '양전자 방사                                 단층 촬영                            PET',
       '체외충격파쇄석기     Extracorporead', '혈관조영장치', '혈관조영장치', 'Division'])

# 창원시 관련 행 필터링 및 합계 계산
suwon_gu = ["수원시장안구           ", "수원시권선구           ", "수원시팔달구           ", "수원시영통구           "]
suwon_data = inf11[inf11['구   분'].isin(suwon_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
suwon_row = pd.DataFrame([['수원시'] + suwon_data.tolist()], columns=inf11.columns)

# 창원시 관련 행 필터링 및 합계 계산
sungnam_gu = ["성남시수정구           ", "성남시중원구           ", "성남시분당구           "]
sungnam_data = inf11[inf11['구   분'].isin(sungnam_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
sungnam_row = pd.DataFrame([['성남시'] + sungnam_data.tolist()], columns=inf11.columns)

# 창원시 관련 행 필터링 및 합계 계산
anyang_gu = ["안양시만안구           ", "안양시동안구           "]
anyang_data = inf11[inf11['구   분'].isin(anyang_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
anyang_row = pd.DataFrame([['안양시'] + anyang_data.tolist()], columns=inf11.columns)

# 창원시 행 추가 및 기존 구 삭제
inf11 = pd.concat([inf11[~inf11['구   분'].isin(suwon_gu)], suwon_row], ignore_index=True)
inf11 = pd.concat([inf11[~inf11['구   분'].isin(sungnam_gu)], sungnam_row], ignore_index=True)
inf11 = pd.concat([inf11[~inf11['구   분'].isin(anyang_gu)], anyang_row], ignore_index=True)


inf11 = inf11.rename(columns={'구   분': '지역'})

inf11['지역'] = inf11['지역'] + ' ' + inf11.groupby('지역').cumcount().replace(0, '').astype(str)


inf11

                         지역 자기공명영상기 전산화단층촬영장치   초음파
0                       서울      411       418  8337
1     종로구                        25        27   404
2    중구                          14        18   331
3     용산구                         3         6   136
4     성동구                         6         9   173
5     광진구                        10        10   252
6      동대문구                      15        18   336
7     중랑구                        14        11   240
8     성북구                        11        12   267
9     강북구                         3         9   223
10    도봉구                         6         8   148
11    노원구                        15        18   362
12    은평구                        11        11   327
13     서대문구                      18        19   264
14    마포구                         4         6   235
15    양천구                        10        12   261
16    강서구                        21        19   405
17    구로구                        10        15   294
18    금천구                         8         6   154
19     영등포구                      27        26   431
20    동작구                        11        12   306
21    관악구                        10         8   247
22    서초구                        29        23   461
23    강남구                        73        62  1116
24    송파구                        38        33   618
25    강동구                        19        20   346
26                      인천       77       103  1657
27  중구                    1       6         9   100
28   동구                           2         2    41
29                    미추홀구       14        14   232
30    연수구                         7         9   150
31    남동구                        14        17   360
32    부평구                        13        17   296
33    계양구                         7        11   178
34   서구                          13        19   280
35    강화군                         1         3    17
36    옹진군                       NaN         2     3
37                      경기      339       394  6853
38     의정부시                      14        15   266
39                     부천시       29        32   518
40                     수원시       41        46   837
41                     성남시       56        50   833
42                     안양시       19        22   395

In [15]:
inf12 = pd.read_excel("01_시군구별 제1권-서울 인천 경기 강원_2019년.xlsx",sheet_name='112p')


# 1. 3번 행을 칼럼명으로 변경
inf12.columns = inf12.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf12 = inf12.drop(index=[0, 1, 2, 3, 4])

#3. 46, 47, 48번 행 삭제
inf12 = inf12.drop(index=[55, 56, 57])

# 인덱스 리셋
inf12 = inf12.reset_index(drop=True)

# inf12.iloc[:, [3, 4]] = inf12.iloc[:, [4, 3]].values
# inf12.iloc[:, [15, 16]] = inf12.iloc[:, [16, 15]].values

# inf12 = inf12.loc[:, ~inf12.columns.isna()]

inf12.columns = [col.split('\n')[0] for col in inf12.columns]
inf12.columns = [col.split(' Inpatient room')[0] for col in inf12.columns]
inf12.columns = [col.split('Intensive Care Unit')[0] for col in inf12.columns]
inf12 = inf12.drop(columns = [  '계', '유         방',
       '양전자 방사                                 단층 촬영                            PET',
       '체외충격파쇄석기     Extracorporead', '혈관조영장치', '혈관조영장치', 'Division'])

# 창원시 관련 행 필터링 및 합계 계산
ansan_gu = ["안산시상록구           ", "안산시단원구           "]
ansan_data = inf12[inf12['구   분'].isin(ansan_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
ansan_row = pd.DataFrame([['안산시'] + ansan_data.tolist()], columns=inf12.columns)

# 창원시 관련 행 필터링 및 합계 계산
goyang_gu = ["고양시덕양구           ", "고양시일산동구", "고양시일산서구"]
goyang_data = inf12[inf12['구   분'].isin(goyang_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
goyang_row = pd.DataFrame([['고양시'] + goyang_data.tolist()], columns=inf12.columns)

# 창원시 관련 행 필터링 및 합계 계산
yongin_gu = ["용인시처인구", "용인시기흥구", "용인시수지구"]
yongin_data = inf12[inf12['구   분'].isin(yongin_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
yongin_row = pd.DataFrame([['용인시'] + yongin_data.tolist()], columns=inf12.columns)

# 창원시 행 추가 및 기존 구 삭제
inf12 = pd.concat([inf12[~inf12['구   분'].isin(ansan_gu)], ansan_row], ignore_index=True)
inf12 = pd.concat([inf12[~inf12['구   분'].isin(goyang_gu)], goyang_row], ignore_index=True)
inf12 = pd.concat([inf12[~inf12['구   분'].isin(yongin_gu)], yongin_row], ignore_index=True)

inf12 = inf12.rename(columns={'구   분': '지역'})

inf12

                      지역 자기공명영상기 전산화단층촬영장치  초음파
0   광명시                        8         6  173
1   평택시                       15        16  254
2    동두천시                      1         1   40
3   과천시                      NaN       NaN   17
4   구리시                       10        11  146
5    남양주시                     11        12  281
6   오산시                        5         8   80
7   시흥시                        3        12  182
8   군포시                        3         8  126
9   의왕시                        1         2   41
10  하남시                        4         4   95
11  파주시                        6         7  164
12  이천시                        4         7  114
13  안성시                        5         5   60
14  김포시                       12        12  195
15  화성시                       13        15  308
16                   광주시       3         5  104
17  양주시                        3         4   67
18  포천시                        4         4   58
19  여주시                        3         3   38
20  연천군                      NaN         1   17
21  가평군                        1         2   26
22  양평군                        2         4   41
23                    강원      39        75  877
24  춘천시                        9        15  210
25  원주시                       10        19  256
26  강릉시                        6        13  149
27  동해시                        3         4   38
28  태백시                        1         3   21
29  속초시                        2         5   59
30  삼척시                        2         2   24
31  홍천군                        3         4   23
32  횡성군                        1         1   12
33  영월군                        1         2   19
34  평창군                      NaN         1   11
35  정선군                      NaN         3    9
36  철원군                        1         1   14
37  화천군                      NaN       NaN    9
38  양구군                      NaN         1    4
39  인제군                      NaN         1    8
40  고성군                      NaN       NaN    9
41  양양군                      NaN       NaN    2
42                   안산시      23        25  401
43                   고양시      27        39  644
44                   용인시      13        16  332

In [16]:
inf13 = pd.read_excel("01_시군구별 제1권-서울 인천 경기 강원_2019년.xlsx",sheet_name='152p')


# 1. 3번 행을 칼럼명으로 변경
inf13.columns = inf13.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf13 = inf13.drop(index=[0, 1, 2, 3, 4, 5, 6, 7])

# 3. 46, 47, 48번 행 삭제
inf13 = inf13.drop(index=[57, 58])

# 인덱스 리셋
inf13 = inf13.reset_index(drop=True)

# # inf13.iloc[:, [3, 4]] = inf13.iloc[:, [4, 3]].values
# # inf13.iloc[:, [15, 16]] = inf13.iloc[:, [16, 15]].values

inf13 = inf13.loc[:, ~inf13.columns.isna()]

inf13.columns = [col.split('\n')[0] for col in inf13.columns]
# # inf13.columns = [col.split(' Inpatient room')[0] for col in inf13.columns]
# # inf13.columns = [col.split('Intensive Care Unit')[0] for col in inf13.columns]
inf13 = inf13.drop(columns = ['내원일수', '급여일수',
       '진료실인원당     Per Patient', '내원1일당  Per Visit ',
       '급여1일당  Per reimbursed day', 'Division'])
# 창원시 관련 행 필터링 및 합계 계산
suwon_gu = ["수원시장안구           ", "수원시권선구           ", "수원시팔달구           ", "수원시영통구           "]
suwon_data = inf13[inf13['구 분'].isin(suwon_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
suwon_row = pd.DataFrame([['수원시'] + suwon_data.tolist()], columns=inf13.columns)

# 창원시 관련 행 필터링 및 합계 계산
sungnam_gu = ["성남시수정구           ", "성남시중원구           ", "성남시분당구           "]
sungnam_data = inf13[inf13['구 분'].isin(sungnam_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
sungnam_row = pd.DataFrame([['성남시'] + sungnam_data.tolist()], columns=inf13.columns)

# 창원시 관련 행 필터링 및 합계 계산
anyang_gu = ["안양시만안구           ", "안양시동안구           "]
anyang_data = inf13[inf13['구 분'].isin(anyang_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
anyang_row = pd.DataFrame([['안양시'] + anyang_data.tolist()], columns=inf13.columns)

# 창원시 행 추가 및 기존 구 삭제
inf13 = pd.concat([inf13[~inf13['구 분'].isin(suwon_gu)], suwon_row], ignore_index=True)
inf13 = pd.concat([inf13[~inf13['구 분'].isin(sungnam_gu)], sungnam_row], ignore_index=True)
inf13 = pd.concat([inf13[~inf13['구 분'].isin(anyang_gu)], anyang_row], ignore_index=True)

inf13 = inf13.rename(columns={'구 분': '지역'})

inf13['지역'] = inf13['지역'] + ' ' + inf13.groupby('지역').cumcount().replace(0, '').astype(str)

inf13

                          지역     진료실인원                 진료비                 급여비
0                        서울    9222102  16491896666.670002  12671033234.134001
1      종로구                      142653        266543452.46       204204820.554
2     중구                        126376        245686701.86        189825410.62
3      용산구                      211036        392772740.66       302346923.449
4      성동구                      284607        515085748.24       393257352.028
5      광진구                      333399        561764311.07       426215430.415
6       동대문구                    324160        636834175.25       492132942.716
7      중랑구                      370955        745503423.83       581012959.061
8      성북구                      413433        750184705.28       574847079.444
9      강북구                      291334        599855657.65       470220533.227
10     도봉구                      311076        587985034.63       455614227.559
11     노원구                      500506        906189959.81       709712743.238
12     은평구                      447136        861071058.78       667982473.442
13      서대문구                    288710        535966363.55       410305111.273
14     마포구                      352318        587596996.91       447967198.087
15     양천구                      431647        735557940.19       563804358.629
16     강서구                      558659       1016510656.84       791654701.614
17     구로구                      406484        741344861.77       568361580.939
18     금천구                      234332        456590498.57        356148201.98
19      영등포구                    372793        683678246.24       524775376.196
20     동작구                      373653        658743245.29       503043257.714
21     관악구                      470623        813532746.37       627828180.378
22     서초구                      406623        631483725.27        470602642.76
23     강남구                      522375        807246404.89       606072803.786
24     송파구                      638013       1012503320.42        763142630.36
25     강동구                      409201        741664690.84       569954294.665
26                       인천    2821260   5211695457.650001      4042469650.516
27   중구                    1    129150         230467595.7       179229079.775
28    동구                         60437        145207993.91        113536435.83
29  미추홀구                        385325        792350192.93       618928296.562
30     연수구                      350274        546711422.56       419708334.793
31     남동구                      512876        946623052.87        735831864.93
32     부평구                      488225        921140853.81       715755839.895
33     계양구                      285987        541812527.55       420243549.869
34    서구                        523813        875953064.71       674861082.221
35     강화군                       65593        168960447.33       131925829.067
36     옹진군                       19580         42468306.28        32449337.574
37                       경기   12770547      21416102619.09  16429077050.697998
38      의정부시                    424482         757752078.8       588010261.463
39                      부천시     798814       1433943417.32       1101047455.26
40                      수원시    1153596       1794401594.03      1372254697.742
41                      성남시     897323       1502951121.83      1148839433.287
42                      안양시     539756        906857301.52       692304779.085

In [17]:
inf14 = pd.read_excel("01_시군구별 제1권-서울 인천 경기 강원_2019년.xlsx",sheet_name='154p')


# 1. 3번 행을 칼럼명으로 변경
inf14.columns = inf14.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf14 = inf14.drop(index=[0, 1, 2, 3, 4, 5, 6, 7])

# 3. 46, 47, 48번 행 삭제
inf14 = inf14.drop(index=[58, 59])

# 인덱스 리셋
inf14 = inf14.reset_index(drop=True)

# # inf14.iloc[:, [3, 4]] = inf14.iloc[:, [4, 3]].values
# # inf14.iloc[:, [15, 16]] = inf14.iloc[:, [16, 15]].values

inf14 = inf14.loc[:, ~inf14.columns.isna()]

inf14.columns = [col.split('\n')[0] for col in inf14.columns]
# # inf14.columns = [col.split(' Inpatient room')[0] for col in inf14.columns]
# # inf14.columns = [col.split('Intensive Care Unit')[0] for col in inf14.columns]
inf14 = inf14.drop(columns = ['내원일수', '급여일수',
       '진료실인원당     Per Patient', '내원1일당  Per Visit ',
       '급여1일당  Per reimbursed day', 'Division'])
# 창원시 관련 행 필터링 및 합계 계산
ansan_gu = ["안산시상록구           ", "안산시단원구           "]
ansan_data = inf14[inf14['구 분'].isin(ansan_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
ansan_row = pd.DataFrame([['안산시'] + ansan_data.tolist()], columns=inf14.columns)

# 창원시 관련 행 필터링 및 합계 계산
goyang_gu = ["고양시덕양구           ", "고양시일산동구", "고양시일산서구"]
goyang_data = inf14[inf14['구 분'].isin(goyang_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
goyang_row = pd.DataFrame([['고양시'] + goyang_data.tolist()], columns=inf14.columns)

# 창원시 관련 행 필터링 및 합계 계산
yongin_gu = ["용인시처인구", "용인시기흥구", "용인시수지구"]
yongin_data = inf14[inf14['구 분'].isin(yongin_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
yongin_row = pd.DataFrame([['용인시'] + yongin_data.tolist()], columns=inf14.columns)

# 창원시 행 추가 및 기존 구 삭제
inf14 = pd.concat([inf14[~inf14['구 분'].isin(ansan_gu)], ansan_row], ignore_index=True)
inf14 = pd.concat([inf14[~inf14['구 분'].isin(goyang_gu)], goyang_row], ignore_index=True)
inf14 = pd.concat([inf14[~inf14['구 분'].isin(yongin_gu)], yongin_row], ignore_index=True)

inf14 = inf14.rename(columns={'구 분': '지역'})

inf14

                      지역    진료실인원            진료비             급여비
0   광명시                    303221   532296803.96   409189487.088
1   평택시                    498633   839193611.77   644738057.364
2    동두천시                   88740   187702827.34   148269161.311
3   과천시                     54998    85542960.55     64449405.16
4   구리시                    188219   333746389.32   257431225.131
5    남양주시                  665616  1159722682.45   892468379.909
6   오산시                    221518   340057132.03   260943074.435
7   시흥시                    475785   749469555.35   573456649.614
8   군포시                    265926   443833026.21   340189821.027
9   의왕시                    153213   254489457.77     192992569.9
10  하남시                    260697   445589016.74   339266139.311
11  파주시                    435805   765623488.88   595226776.926
12  이천시                    208130   350727005.45   269236963.625
13  안성시                    182662   334322168.87    258311672.48
14  김포시                    428792   722360613.84   554006427.608
15  화성시                    814320  1159459854.83   882263443.792
16                   광주시   359190   588440043.42   446699471.183
17  양주시                    214493   382604923.14   297136645.988
18  포천시                    146481   289085596.45   224821605.463
19  여주시                    106311    218150655.1   169329522.255
20  연천군                     41614    94515935.71     74565765.01
21  가평군                     59482   138423665.49   109547954.785
22  양평군                    110434   242947514.34   188277398.605
23                    강원  1455794  2899120469.71  2262547267.492
24  춘천시                    265435    520920830.4   410761634.459
25  원주시                    329807   582937059.36   450555844.793
26  강릉시                    200461    383822124.9   300782692.852
27  동해시                     85982   168914733.69   131837743.989
28  태백시                     40837    85700720.99    66607654.603
29  속초시                     76899   150171572.88   117754387.629
30  삼척시                     63759    142436311.9    111778839.64
31  홍천군                     65710   148079094.54   115020558.444
32  횡성군                     44486   102759188.26     79423589.58
33  영월군                     36994    86768563.94    66847140.028
34  평창군                     39742    84211798.63    64601532.613
35  정선군                     34601    75079774.52    58161213.733
36  철원군                     43144    91885942.56    72198493.883
37  화천군                     23809    51951974.47    40911139.369
38  양구군                     21708    44776616.62    35196592.064
39  인제군                     30138    59513482.97    46379191.759
40  고성군                     25913    61013776.98     47959273.09
41  양양군                     26369     58176902.1    45769744.964
42                   안산시   654085  1093116107.92   843251490.866
43                   고양시  1007361  1708082989.66  1311119655.598
44                   용인시  1010850   1560693079.0  1179431659.427

In [18]:
inf15 = pd.read_excel("01_시군구별 제1권-서울 인천 경기 강원_2019년.xlsx",sheet_name='170p관내')


# 1. 3번 행을 칼럼명으로 변경
inf15.columns = inf15.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf15 = inf15.drop(index=[0, 1, 2, 3, 4, 5, 6, 7])

# 3. 46, 47, 48번 행 삭제
inf15 = inf15.drop(index=[57, 58])

# 인덱스 리셋
inf15 = inf15.reset_index(drop=True)

# # inf15.iloc[:, [3, 4]] = inf15.iloc[:, [4, 3]].values
# # inf15.iloc[:, [15, 16]] = inf15.iloc[:, [16, 15]].values

inf15 = inf15.loc[:, ~inf15.columns.isna()]

inf15.columns = [col.split('\n')[0] for col in inf15.columns]
# # inf15.columns = [col.split(' Inpatient room')[0] for col in inf15.columns]
# # inf15.columns = [col.split('Intensive Care Unit')[0] for col in inf15.columns]
inf15 = inf15.drop(columns = ['내원일수', '급여일수',
       '진료실인원당     Per Patient', '내원1일당  Per Visit ',
       '급여1일당  Per reimbursed day', 'Division'])
# 창원시 관련 행 필터링 및 합계 계산
suwon_gu = ["수원시장안구           ", "수원시권선구           ", "수원시팔달구           ", "수원시영통구           "]
suwon_data = inf15[inf15['구 분'].isin(suwon_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
suwon_row = pd.DataFrame([['수원시'] + suwon_data.tolist()], columns=inf15.columns)

# 창원시 관련 행 필터링 및 합계 계산
sungnam_gu = ["성남시수정구           ", "성남시중원구           ", "성남시분당구           "]
sungnam_data = inf15[inf15['구 분'].isin(sungnam_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
sungnam_row = pd.DataFrame([['성남시'] + sungnam_data.tolist()], columns=inf15.columns)

# 창원시 관련 행 필터링 및 합계 계산
anyang_gu = ["안양시만안구           ", "안양시동안구           "]
anyang_data = inf15[inf15['구 분'].isin(anyang_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
anyang_row = pd.DataFrame([['안양시'] + anyang_data.tolist()], columns=inf15.columns)

# 창원시 행 추가 및 기존 구 삭제
inf15 = pd.concat([inf15[~inf15['구 분'].isin(suwon_gu)], suwon_row], ignore_index=True)
inf15 = pd.concat([inf15[~inf15['구 분'].isin(sungnam_gu)], sungnam_row], ignore_index=True)
inf15 = pd.concat([inf15[~inf15['구 분'].isin(anyang_gu)], anyang_row], ignore_index=True)

inf15 = inf15.rename(columns={'구 분': '지역'})

inf15['지역'] = inf15['지역'] + ' ' + inf15.groupby('지역').cumcount().replace(0, '').astype(str)

inf15

                          지역     진료실인원                 진료비                 급여비
0                        서울    8900597  14770542863.389999     11330096455.271
1      종로구                      110332        105064467.81         78723899.69
2     중구                         95889         86846605.12        66446736.618
3      용산구                      153877         122070527.3        93964772.935
4      성동구                      225667         192344535.7        144448850.07
5      광진구                      285249        292387825.68       219875007.489
6       동대문구                    272227         305205868.9       233208867.458
7      중랑구                      316256        325205352.55       251061846.667
8      성북구                      337071        326876053.64       248884861.082
9      강북구                      247625        216668287.03        166590781.25
10     도봉구                      259872        220647694.97       168076826.283
11     노원구                      437003        489571360.94       381242274.083
12     은평구                      388997        410116437.56       314413157.661
13      서대문구                    230245         247223767.5       188767029.738
14     마포구                      293204        183397442.57        137433372.03
15     양천구                      364473        311308160.61       235793396.356
16     강서구                      481553         454618780.9       346373199.355
17     구로구                      338113        365304343.97       277953265.121
18     금천구                      191044        165134265.94       126307583.822
19      영등포구                    308316         330141948.6       250478697.071
20     동작구                      299548        283087951.24       215413777.019
21     관악구                      383316        303475101.35       230256408.353
22     서초구                      328234        257476486.37       190610499.139
23     강남구                      440647        407346382.59       301681039.549
24     송파구                      552362        509994142.07       381355100.699
25     강동구                      361213        443627323.96       338308427.755
26                       인천    2655979       4093918890.66      3157254920.837
27   중구                    1    102485         90315656.63        69681773.339
28    동구                         49281         47885932.66        36898834.938
29  미추홀구                        326256        342485843.59       262899430.307
30     연수구                      304388        215968084.47         161924083.8
31     남동구                      454157        521655064.76       402538219.721
32     부평구                      428251        497509666.98       380953219.346
33     계양구                      252931        289867992.39       221279123.971
34    서구                        467054        479989241.18       364007562.351
35     강화군                       51534         59134148.18        45238365.471
36     옹진군                       12153          3124707.53          2274303.16
37                       경기   12085698  16016716917.480001  12219405047.038002
38      의정부시                    383644        461124995.56       354907673.296
39                      부천시     729056       1023703929.38       780512261.461
40                      수원시     961035        696450395.06       523243685.392
41                      성남시     756386        704003647.28       528856999.202
42                      안양시     466274        435309750.32       326109838.915

In [19]:
inf16 = pd.read_excel("01_시군구별 제1권-서울 인천 경기 강원_2019년.xlsx",sheet_name='172p')


# 1. 3번 행을 칼럼명으로 변경
inf16.columns = inf16.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf16 = inf16.drop(index=[0, 1, 2, 3, 4, 5, 6, 7])

# 3. 46, 47, 48번 행 삭제
inf16 = inf16.drop(index=[58, 59])

# 인덱스 리셋
inf16 = inf16.reset_index(drop=True)

# # inf16.iloc[:, [3, 4]] = inf16.iloc[:, [4, 3]].values
# # inf16.iloc[:, [15, 16]] = inf16.iloc[:, [16, 15]].values

inf16 = inf16.loc[:, ~inf16.columns.isna()]

inf16.columns = [col.split('\n')[0] for col in inf16.columns]
# # inf16.columns = [col.split(' Inpatient room')[0] for col in inf16.columns]
# # inf16.columns = [col.split('Intensive Care Unit')[0] for col in inf16.columns]
inf16 = inf16.drop(columns = ['내원일수', '급여일수',
       '진료실인원당     Per Patient', '내원1일당  Per Visit ',
       '급여1일당  Per reimbursed day', 'Division'])
# 창원시 관련 행 필터링 및 합계 계산
ansan_gu = ["안산시상록구           ", "안산시단원구           "]
ansan_data = inf16[inf16['구 분'].isin(ansan_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
ansan_row = pd.DataFrame([['안산시'] + ansan_data.tolist()], columns=inf16.columns)

# 창원시 관련 행 필터링 및 합계 계산
goyang_gu = ["고양시덕양구           ", "고양시일산동구", "고양시일산서구"]
goyang_data = inf16[inf16['구 분'].isin(goyang_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
goyang_row = pd.DataFrame([['고양시'] + goyang_data.tolist()], columns=inf16.columns)

# 창원시 관련 행 필터링 및 합계 계산
yongin_gu = ["용인시처인구", "용인시기흥구", "용인시수지구"]
yongin_data = inf16[inf16['구 분'].isin(yongin_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
yongin_row = pd.DataFrame([['용인시'] + yongin_data.tolist()], columns=inf16.columns)

# 창원시 행 추가 및 기존 구 삭제
inf16 = pd.concat([inf16[~inf16['구 분'].isin(ansan_gu)], ansan_row], ignore_index=True)
inf16 = pd.concat([inf16[~inf16['구 분'].isin(goyang_gu)], goyang_row], ignore_index=True)
inf16 = pd.concat([inf16[~inf16['구 분'].isin(yongin_gu)], yongin_row], ignore_index=True)

inf16 = inf16.rename(columns={'구 분': '지역'})

inf16

                      지역    진료실인원            진료비             급여비
0   광명시                    268878   247157497.14   186617420.664
1   평택시                    450810    478775938.2   359287860.406
2    동두천시                   78887    85669400.62     67082720.51
3   과천시                     42066     19640048.2    14489049.724
4   구리시                    164934   174319875.13   133587582.643
5    남양주시                  576001   478662819.67   361714556.198
6   오산시                    191473   160191099.66    119790118.78
7   시흥시                    413081    316919489.5   235850636.943
8   군포시                    234306   213571888.49   160949719.811
9   의왕시                    110121     57658664.5    43030407.531
10  하남시                    197250   145462410.83   108660176.569
11  파주시                    382542   329785647.23   250574434.213
12  이천시                    188561   174195824.28   130234707.029
13  안성시                    157223   146408906.75   111094703.153
14  김포시                    379969    372056521.4   280393545.349
15  화성시                    695483   521714099.72   392383323.311
16                   광주시   287096   215685680.06   158778849.501
17  양주시                    175161   120336734.85    91257812.232
18  포천시                    124738   124431469.25    94742320.643
19  여주시                     87878    91313556.22    69423570.733
20  연천군                     32139     25158989.6    19557265.226
21  가평군                     47264    38964220.77    30558152.876
22  양평군                     87238    82278586.15    62532989.966
23                    강원  1366191  2189406066.61  1696776125.297
24  춘천시                    251664    423572953.9   332468822.867
25  원주시                    311074    460616252.4   353042299.714
26  강릉시                    189295   303581992.52   236093135.262
27  동해시                     79497    91634036.51    69651089.969
28  태백시                     36696    34813241.68     26043302.98
29  속초시                     70899    81844577.33    62487070.937
30  삼척시                     55722    63475106.92    48749731.849
31  홍천군                     55484    54735900.09    41443393.528
32  횡성군                     34637    28931393.55    21947054.939
33  영월군                     29030    26181372.36    19609455.797
34  평창군                     30817    18873118.13    14232952.606
35  정선군                     26099    13126087.13     9728322.431
36  철원군                     36268     30350515.5    23577370.909
37  화천군                     17821     9439501.82     7244721.573
38  양구군                     17656    11425319.95     8734225.369
39  인제군                     24191    14758996.68    11047526.894
40  고성군                     15626     9447675.09     7199235.815
41  양양군                     17996     9049425.65     6903335.143
42                   안산시   556869    543282456.8   412995320.046
43                   고양시   845026   774375174.55   587510473.901
44                   용인시   823570   555764885.71   413342004.075

In [20]:
inf17 = pd.read_excel("01_시군구별 제1권-서울 인천 경기 강원_2019년.xlsx",sheet_name='182p관외')


# 1. 3번 행을 칼럼명으로 변경
inf17.columns = inf17.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf17 = inf17.drop(index=[0, 1, 2, 3, 4, 5, 6, 7])

# 3. 46, 47, 48번 행 삭제
inf17 = inf17.drop(index=[57, 58])

# 인덱스 리셋
inf17 = inf17.reset_index(drop=True)

# # inf17.iloc[:, [3, 4]] = inf17.iloc[:, [4, 3]].values
# # inf17.iloc[:, [15, 16]] = inf17.iloc[:, [16, 15]].values

inf17 = inf17.loc[:, ~inf17.columns.isna()]

inf17.columns = [col.split('\n')[0] for col in inf17.columns]
# # inf17.columns = [col.split(' Inpatient room')[0] for col in inf17.columns]
# # inf17.columns = [col.split('Intensive Care Unit')[0] for col in inf17.columns]
inf17 = inf17.drop(columns = ['내원일수', '급여일수',
       '진료실인원당     Per Patient', '내원1일당  Per Visit ',
       '급여1일당  Per reimbursed day', 'Division'])
# 창원시 관련 행 필터링 및 합계 계산
suwon_gu = ["수원시장안구           ", "수원시권선구           ", "수원시팔달구           ", "수원시영통구           "]
suwon_data = inf17[inf17['구 분'].isin(suwon_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
suwon_row = pd.DataFrame([['수원시'] + suwon_data.tolist()], columns=inf17.columns)

# 창원시 관련 행 필터링 및 합계 계산
sungnam_gu = ["성남시수정구           ", "성남시중원구           ", "성남시분당구           "]
sungnam_data = inf17[inf17['구 분'].isin(sungnam_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
sungnam_row = pd.DataFrame([['성남시'] + sungnam_data.tolist()], columns=inf17.columns)

# 창원시 관련 행 필터링 및 합계 계산
anyang_gu = ["안양시만안구           ", "안양시동안구           "]
anyang_data = inf17[inf17['구 분'].isin(anyang_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
anyang_row = pd.DataFrame([['안양시'] + anyang_data.tolist()], columns=inf17.columns)

# 창원시 행 추가 및 기존 구 삭제
inf17 = pd.concat([inf17[~inf17['구 분'].isin(suwon_gu)], suwon_row], ignore_index=True)
inf17 = pd.concat([inf17[~inf17['구 분'].isin(sungnam_gu)], sungnam_row], ignore_index=True)
inf17 = pd.concat([inf17[~inf17['구 분'].isin(anyang_gu)], anyang_row], ignore_index=True)

inf17 = inf17.rename(columns={'구 분': '지역'})

inf17['지역'] = inf17['지역'] + ' ' + inf17.groupby('지역').cumcount().replace(0, '').astype(str)

inf17

                          지역    진료실인원                진료비             급여비
0                        서울   2234352      1721353803.28  1340936778.863
1      종로구                     115899       161478984.65   125480920.864
2     중구                       101385       158840096.74   123378674.002
3      용산구                     178027       270702213.36   208382150.514
4      성동구                     225037       322741212.54   248808501.958
5      광진구                     232427       269376485.39   206340422.926
6       동대문구                   233633       331628306.35   258924075.258
7      중랑구                     267662       420298071.28   329951112.394
8      성북구                     319457       423308651.64   325962218.362
9      강북구                     219072       383187370.62   303629751.977
10     도봉구                     238734       367337339.66   287537401.276
11     노원구                     320962       416618598.87   328470469.155
12     은평구                     306877       450954621.22   353569315.781
13      서대문구                   230971       288742596.05   221538081.535
14     마포구                     272924       404199554.34   310533826.057
15     양천구                     325732       424249779.58   328010962.273
16     강서구                     395247       561891875.94   445281502.259
17     구로구                     298553        376040517.8   290408315.818
18     금천구                     175948       291456232.63   229840618.158
19      영등포구                   275932       353536297.64   274296679.125
20     동작구                     296273       375655294.05   287629480.695
21     관악구                     361088       510057645.02   397571772.025
22     서초구                     326687        374007238.9   279992143.621
23     강남구                     374324        399900022.3   304391764.237
24     송파구                     444864       502509178.35   381787529.661
25     강동구                     253829       298037366.88    231645866.91
26                       인천   1028696      1117776566.99   885214729.679
27   중구                    1    99433       140151939.07   109547306.436
28    동구                        49396        97322061.25    76637600.892
29  미추홀구                       283679       449864349.34   356028866.255
30     연수구                     236630       330743338.09   257784250.993
31     남동구                     327075       424967988.11   333293645.209
32     부평구                     318517       423631186.83   334802620.549
33     계양구                     183761       251944535.16   198964425.898
34    서구                       316010       395963823.53    310853519.87
35     강화군                      49801       109826299.15    86687463.596
36     옹진군                      18171        39343598.75    30175034.414
37                       경기   4754607  5399385701.610001   4209672003.66
38      의정부시                   230410       296627083.24   233102588.167
39                      부천시    400282       410239487.94   320535193.799
40                      수원시    883011      1097951198.97    849011012.35
41                      성남시    628915       798947474.55   619982434.085
42                      안양시    376578        471547551.2    366194940.17

In [21]:
inf18 = pd.read_excel("01_시군구별 제1권-서울 인천 경기 강원_2019년.xlsx",sheet_name='184p')


# 1. 3번 행을 칼럼명으로 변경
inf18.columns = inf18.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf18 = inf18.drop(index=[0, 1, 2, 3, 4, 5, 6, 7])

# 3. 46, 47, 48번 행 삭제
inf18 = inf18.drop(index=[58, 59])

# 인덱스 리셋
inf18 = inf18.reset_index(drop=True)

# # inf18.iloc[:, [3, 4]] = inf18.iloc[:, [4, 3]].values
# # inf18.iloc[:, [15, 16]] = inf18.iloc[:, [16, 15]].values

inf18 = inf18.loc[:, ~inf18.columns.isna()]

inf18.columns = [col.split('\n')[0] for col in inf18.columns]
# # inf18.columns = [col.split(' Inpatient room')[0] for col in inf18.columns]
# # inf18.columns = [col.split('Intensive Care Unit')[0] for col in inf18.columns]
inf18 = inf18.drop(columns = ['내원일수', '급여일수',
       '진료실인원당     Per Patient', '내원1일당  Per Visit ',
       '급여1일당  Per reimbursed day', 'Division'])
# 창원시 관련 행 필터링 및 합계 계산
ansan_gu = ["안산시상록구           ", "안산시단원구           "]
ansan_data = inf18[inf18['구 분'].isin(ansan_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
ansan_row = pd.DataFrame([['안산시'] + ansan_data.tolist()], columns=inf18.columns)

# 창원시 관련 행 필터링 및 합계 계산
goyang_gu = ["고양시덕양구           ", "고양시일산동구", "고양시일산서구"]
goyang_data = inf18[inf18['구 분'].isin(goyang_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
goyang_row = pd.DataFrame([['고양시'] + goyang_data.tolist()], columns=inf18.columns)

# 창원시 관련 행 필터링 및 합계 계산
yongin_gu = ["용인시처인구", "용인시기흥구", "용인시수지구"]
yongin_data = inf18[inf18['구 분'].isin(yongin_gu)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
yongin_row = pd.DataFrame([['용인시'] + yongin_data.tolist()], columns=inf18.columns)

# 창원시 행 추가 및 기존 구 삭제
inf18 = pd.concat([inf18[~inf18['구 분'].isin(ansan_gu)], ansan_row], ignore_index=True)
inf18 = pd.concat([inf18[~inf18['구 분'].isin(goyang_gu)], goyang_row], ignore_index=True)
inf18 = pd.concat([inf18[~inf18['구 분'].isin(yongin_gu)], yongin_row], ignore_index=True)

inf18 = inf18.rename(columns={'구 분': '지역'})

inf18['지역'] = inf18['지역'] + ' ' + inf18.groupby('지역').cumcount().replace(0, '').astype(str)

inf18

                       지역   진료실인원            진료비            급여비
0   광명시                    196518   285139306.82  222572066.424
1   평택시                    256728   360417673.57  285450196.958
2    동두천시                   58915   102033426.72   81186440.801
3   과천시                     45762    65902912.35   49960355.436
4   구리시                    123131   159426514.19  123843642.488
5    남양주시                  450811   681059862.78  530753823.711
6   오산시                    138314   179866032.37  141152955.655
7   시흥시                    304778   432550065.85  337606012.671
8   군포시                    175532   230261137.72  179240101.216
9   의왕시                    135346   196830793.27  149962162.369
10  하남시                    201650   300126605.91  230605962.742
11  파주시                    277737   435837841.65  344652342.713
12  이천시                    112667   176531181.17  139002256.596
13  안성시                    117799   187913262.12  147216969.327
14  김포시                    258138   350304092.44  273612882.259
15  화성시                    539936   637745755.11  489880120.481
16                   광주시   260543   372754363.36  287920621.682
17  양주시                    159735   262268188.29  205878833.756
18  포천시                     93163    164654127.2   130079284.82
19  여주시                     70658   126837098.88   99905951.522
20  연천군                     33554    69356946.11   55008499.784
21  가평군                     48686    99459444.72   78989801.909
22  양평군                     80071   160668928.19  125744408.639
23                    강원   455164    709714403.1  565771142.195
24  춘천시                     79469     97347876.5   78292811.592
25  원주시                    104579   122320806.96   97513545.079
26  강릉시                     59708    80240132.38    64689557.59
27  동해시                     45754    77280697.18    62186654.02
28  태백시                     26153    50887479.31   40564351.623
29  속초시                     38924    68326995.55   55267316.692
30  삼척시                     41894    78961204.98   63029107.791
31  홍천군                     44923    93343194.45   73577164.916
32  횡성군                     36701    73827794.71   57476534.641
33  영월군                     28825    60587191.58   47237684.231
34  평창군                     33724     65338680.5   50368580.007
35  정선군                     29237    61953687.39   48432891.302
36  철원군                     33792    61535427.06   48621122.974
37  화천군                     20781    42512472.65   33666417.796
38  양구군                     18046    33351296.67   26462366.695
39  인제군                     24872    44754486.29   35331664.865
40  고성군                     23393    51566101.89   40760037.275
41  양양군                     23451    49127476.45   38866409.821
42                   안산시   427596   549833651.12   430256170.82
43                   고양시   737388   933707815.11  723609181.697
44                   용인시   770492  1004928193.29  766089655.352

In [22]:

# merged_df = pd.merge(inf, inf2, on = '구 분')

# merged_df

result1 = pd.concat([inf, inf2], axis=0)
result2 = pd.concat([inf3, inf4], axis=0)
result3 = pd.concat([inf5, inf6], axis=0)
result4 = pd.concat([inf7, inf8], axis=0)
result5 = pd.concat([inf9, inf10], axis=0)
result6 = pd.concat([inf11, inf12], axis=0)
result7 = pd.concat([inf13, inf14], axis=0)
result8 = pd.concat([inf15, inf16], axis=0)
result9 = pd.concat([inf17, inf18], axis=0)


col = '지역'
result1[col] = result1[col].str.strip()
result2[col] = result2[col].str.strip()
result3[col] = result3[col].str.strip()
result4[col] = result4[col].str.strip()
result5[col] = result5[col].str.strip()
result6[col] = result6[col].str.strip()
result7[col] = result7[col].str.strip()
result8[col] = result8[col].str.strip()
result9[col] = result9[col].str.strip()

result1 = result1.reset_index(drop=True)
result2 = result2.reset_index(drop=True)
result3 = result3.reset_index(drop=True)
result4 = result4.reset_index(drop=True)
result5 = result5.reset_index(drop=True)
result6 = result6.reset_index(drop=True)
result7 = result7.reset_index(drop=True)
result8 = result8.reset_index(drop=True)
result9 = result9.reset_index(drop=True)

In [23]:
result1['지역'] = result1['지역'] + ' ' + result1.groupby('지역').cumcount().replace(0, '').astype(str)
result2['지역'] = result2['지역'] + ' ' + result1.groupby('지역').cumcount().replace(0, '').astype(str)
result3['지역'] = result3['지역'] + ' ' + result1.groupby('지역').cumcount().replace(0, '').astype(str)
result4['지역'] = result4['지역'] + ' ' + result1.groupby('지역').cumcount().replace(0, '').astype(str)
result5['지역'] = result5['지역'] + ' ' + result1.groupby('지역').cumcount().replace(0, '').astype(str)
result6['지역'] = result6['지역'] + ' ' + result1.groupby('지역').cumcount().replace(0, '').astype(str)
result7['지역'] = result7['지역'] + ' ' + result1.groupby('지역').cumcount().replace(0, '').astype(str)
result8['지역'] = result8['지역'] + ' ' + result1.groupby('지역').cumcount().replace(0, '').astype(str)
result9['지역'] = result9['지역'] + ' ' + result1.groupby('지역').cumcount().replace(0, '').astype(str)

In [24]:


dataframes = [result1, result2, result3, result4, result5, result6, result7, result8, result9]

result = dataframes[0]
for df in dataframes[1:]:
    result = result.merge(df, on='지역')
result = result.drop_duplicates(subset='지역', keep='first')
result

,지역,의료보장,근 로 자,공ㆍ교,지 역,의료급여 1종,의료급여 2종,계_x,0-4세,5-9세,...,초음파,진료실인원_x,진료비_x,급여비_x,진료실인원_y,진료비_y,급여비_y,진료실인원,진료비,급여비
0,서울,9933336,6410576,576211,2695880,179257,71412,9933336,307840,366494,...,8337,9222102,16491896666.670002,12671033234.134001,8900597,14770542863.389999,11330096455.271,2234352,1721353803.28,1340936778.863
1,종로구,157094,92512,11069,49231,3442,840,157094,3727,4828,...,404,142653,266543452.46,204204820.554,110332,105064467.81,78723899.69,115899,161478984.65,125480920.864
2,중구,138071,84314,5503,44532,2967,755,138071,4191,4012,...,331,126376,245686701.86,189825410.62,95889,86846605.12,66446736.618,101385,158840096.74,123378674.002
3,용산구,231921,143113,14686,68331,4416,1375,231921,7071,7480,...,136,211036,392772740.66,302346923.449,153877,122070527.3,93964772.935,178027,270702213.36,208382150.514
4,성동구,305714,201231,14947,82873,4507,2156,305714,11377,10926,...,173,284607,515085748.24,393257352.028,225667,192344535.7,144448850.07,225037,322741212.54,248808501.958
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,고성군,27618,12376,4396,9658,957,231,27618,608,743,...,9,25913,61013776.98,47959273.09,15626,9447675.09,7199235.815,23393,51566101.89,40760037.275
84,양양군,27933,13124,3601,9875,1140,193,27933,587,800,...,2,26369,58176902.1,45769744.964,17996,9049425.65,6903335.143,23451,49127476.45,38866409.821
85,안산시,710915,453186,20942,219595,12491,4701,710915,22634,27632,...,401,654085,1093116107.92,843251490.866,556869,543282456.8,412995320.046,427596,549833651.12,430256170.82
86,고양시,1078782,714375,70096,275339,14331,4641,1078782,37294,47924,...,644,1007361,1708082989.66,1311119655.598,845026,774375174.55,587510473.901,737388,933707815.11,723609181.697
87,용인시,1076848,765458,61562,241440,6857,1531,1076848,45081,60657,...,332,1010850,1560693079.0,1179431659.427,823570,555764885.71,413342004.075,770492,1004928193.29,766089655.352

In [25]:
file_path = "2019 경기 강원.csv"  # 저장할 파일 이름과 경로 설정
result.to_csv(file_path, index=False, encoding='utf-8-sig')  # UTF-8 인코딩으로 저장