In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import font_manager, rc

In [2]:
# 적용인구 현황
inf = pd.read_excel("03_시군구별 제3권-광주 전북 전남 제주_2019년.xlsx",sheet_name='82p_인구')

# 1. 3번 행을 칼럼명으로 변경
inf.columns = inf.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf = inf.drop(index=[0, 1, 2, 3, 4, 5, 6, 7])

# 3. 46, 47, 48번 행 삭제
inf = inf.drop(index=[56, 57, 58])

# 인덱스 리셋
inf = inf.reset_index(drop=True)

inf.iloc[:, [2, 3]] = inf.iloc[:, [3, 2]].values
inf.iloc[:, [6, 7]] = inf.iloc[:, [7, 6]].values

inf = inf.loc[:, ~inf.columns.isna()]

inf = inf.drop(columns = ["G. & T.", "Division"])

inf.columns = [col.split('\n')[0] for col in inf.columns]
inf.columns = [col.split('  C.E')[0] for col in inf.columns]
inf.columns = [col.split('  S.E.')[0] for col in inf.columns]
inf.columns = [col.split('    Medical Aid')[0] for col in inf.columns]

inf

# 창원시 관련 행 필터링 및 합계 계산
jeonju =[ '전주시완산구             ','전주시덕진구             ']
jeonju_data = inf[inf['구  분'].isin(jeonju)].iloc[:, 1:].sum()

# 새로운 창원시 행 생성
jeonju_row = pd.DataFrame([['전주시'] + jeonju_data.tolist()], columns=inf.columns)

# 전주시 행 추가 및 기존 구 삭제
inf = pd.concat([inf[~inf['구  분'].isin(jeonju)], jeonju_row], ignore_index=True)
inf = inf.rename(columns={'구  분': '지역'})

inf['지역'] = inf['지역'] + ' ' + inf.groupby('지역').cumcount().replace(0, '').astype(str)

inf

                         지역     의료보장    근 로 자     공ㆍ교     지 역 의료급여 1종 의료급여 2종
0                       광주   1472535   900866  141552  366687   40646   22784
1    동구                        98872    54224   11494   27146    4141    1867
2    서구                       303357   184831   30815   74963    8159    4589
3    남구                       218884   128640   25974   54731    6110    3429
4    북구                       436493   259429   42036  113714   13816    7498
5     광산구                     414929   273742   31233   96133    8420    5401
6                       전북   1837478  1048946  194740  508751   60362   24679
7   군산시                       273214   163835   22011   75141    8920    3307
8   익산시                       290541   169903   26017   79827   10782    4012
9   정읍시                       111951    58367   11896   35142    4825    1721
10  남원시                        82450    43032    9015   25429    3477    1497
11  김제시                        85252    44692    8427   25988    4691    1454
12  완주군                        93982    54798    8423   26508    3224    1029
13  진안군                        25949    12797    3536    8380    1024     212
14  무주군                        24509    12660    2730    8019     849     251
15  장수군                        22736    11164    3096    7323     824     329
16  임실군                        29147    14757    4042    8898    1087     363
17  순창군                        28669    14403    3896    9109     911     350
18  고창군                        56156    27641    5845   19987    2178     505
19  부안군                        53765    25734    6104   19265    2136     526
20                      전남   1891561  1050460  192587  576309   57034   15171
21  목포시                       231823   126602   24114   69724    8150    3233
22  여수시                       286094   178852   20071   78249    7106    1816
23  순천시                       281285   171230   30139   72991    5429    1496
24  나주시                       116135    66046   12182   33507    3711     689
25  광양시                       158579   108323    9603   37418    2331     904
26  담양군                        47305    24164    6314   14884    1590     353
27  곡성군                        29091    15045    3746    8726    1304     270
28  구례군                        26724    13013    3572    8818    1010     311
29  고흥군                        65535    30434    7037   24342    3200     522
30  보성군                        41548    19839    4898   14669    1780     362
31  화순군                        63395    35438    6488   18728    2060     681
32  장흥군                        39076    17969    5314   13602    1702     489
33  강진군                        35576    17348    4207   12099    1472     450
34  해남군                        71199    33314    7656   26875    2807     547
35  영암군                        58429    32240    5145   19044    1621     379
36  무안군                        81516    42971   11677   24633    1805     430
37  함평군                        33260    16174    3935   11524    1346     281
38  영광군                        54252    27839    5002   18609    2218     584
39  장성군                        46639    23209    7475   13940    1662     353
40  완도군                        52023    21153    5257   23541    1796     276
41  진도군                        31478    12922    3891   12826    1395     444
42  신안군                        40599    16335    4864   17560    1539     301
43                      제주    686146   380854   67939  217695   13779    5879
44            제주시             499746   284633   50692  150752    9382    4287
45             서귀포시           186400    96221   17247   66943    4397    1592
46                     전주시    659157   395163   79702  159735   15434    9123

In [3]:
# 연령별 의료 보장
inf2 = pd.read_excel("03_시군구별 제3권-광주 전북 전남 제주_2019년.xlsx",sheet_name='84p')

# 1. 3번 행을 칼럼명으로 변경
inf2.columns = inf2.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf2 = inf2.drop(index=[0, 1, 2, 3, 4, 5, 6, 7])

# 56, 57, 58번 행 삭제
inf2 = inf2.drop(index=[56, 57])

# 인덱스 리셋
inf2 = inf2.reset_index(drop=True)

inf2 = inf2.drop(columns = [ "Division"])

inf2.columns = [col.split('\n')[0] for col in inf2.columns]

# 전주시 관련 행 필터링 및 합계 계산
jeonju =[ '전주시완산구             ','전주시덕진구             ']
jeonju_data = inf2[inf2['구  분'].isin(jeonju)].iloc[:, 1:].sum()

# 새로운 전주시 행 생성
jeonju_row = pd.DataFrame([['전주시'] + jeonju_data.tolist()], columns=inf2.columns)

# 전주시 행 추가 및 기존 구 삭제
inf2 = pd.concat([inf2[~inf2['구  분'].isin(jeonju)], jeonju_row], ignore_index=True)
inf2 = inf2.rename(columns={'구  분': '지역'})

inf2['지역'] = inf2['지역'] + ' ' + inf2.groupby('지역').cumcount().replace(0, '').astype(str)

inf2

,지역,계,0-4세,5-9세,10-14세,15-19세,20-24세,25-29세,30-34세,35-39세,40-44세,45-49세,50-54세,55-59세,60-64세,65-69세,70-74세,75-79세,80세 이상
0,광주,1472535,54358,72968,74707,90078,110759,101523,85816,111737,114891,132662,123572,112368,92441,61698,50869,39429,42659
1,동구,98872,3195,3478,3051,4443,6929,7087,6000,6762,6299,7340,7386,8071,7964,5976,5447,4574,4870
2,서구,303357,9829,13708,14754,18950,23959,21960,17520,21921,23001,27974,26501,23714,19428,12970,10479,8020,8669
3,남구,218884,7493,10860,10953,12732,15401,13570,11473,15955,16370,18318,17167,16871,15813,11182,9574,7303,7849
4,북구,436493,15629,19673,20035,25273,32556,31020,26130,32237,31740,37410,37273,36102,30116,20092,16088,12212,12907
5,광산구,414929,18212,25249,25914,28680,31914,27886,24693,34862,37481,41620,35245,27610,19120,11478,9281,7320,8364
6,전북,1837478,57825,79732,82719,99975,118271,102451,88947,115084,123868,153372,152073,154507,139553,104194,87547,76764,100596
7,군산시,273214,9305,13339,13017,14843,16550,14422,13976,19920,20510,24434,22168,22365,20594,15124,12133,9490,11024
8,익산시,290541,8813,12184,13118,16465,20907,17591,13947,17596,19295,24491,25036,25449,22405,16026,12663,10695,13860
9,정읍시,111951,2839,4087,4549,5737,6551,5086,4406,5571,6802,8771,9361,9735,9203,7041,6710,6507,8995
10,남원시,82450,2280,3035,3424,4293,4601,3445,3072,3965,4694,6511,6994,7190,6925,5493,5011,4657,6860
11,김제시,85252,1912,2818,2964,3540,4311,3881,3402,4307,4599,5884,6578,7776,7770,6287,5616,5446,8161
12,완주군,93982,3219,4428,4208,4281,5110,4673,4458,6246,6473,7364,7617,8090,7440,5667,4706,4189,5813
13,진안군,25949,672,732,752,981,1181,982,847,1057,1223,1709,2118,2581,2532,2081,1911,1872,2718
14,무주군,24509,496,782,900,967,1054,918,824,1033,1274,1747,2018,2317,2302,1927,1614,1806,2530
15,장수군,22736,479,762,824,895,1048,857,811,992,1166,1510,1844,2075,2177,1868,1506,1608,2314
16,임실군,29147,744,781,868,1026,1335,1289,1118,1219,1404,1827,2334,2749,2666,2191,2095,2191,3310
17,순창군,28669,867,818,1070,1236,1288,1058,992,1314,1439,2013,2178,2560,2554,2028,2047,2208,2999
18,고창군,56156,1188,1712,1863,2602,2649,2190,1971,2386,2723,3848,4432,5033,5229,4131,4106,4336,5757
19,부안군,53765,1185,1585,1672,2298,2642,2110,1930,2516,2705,3741,4257,4995,5221,4176,3925,3652,5155
20,전남,1891561,61422,78329,79085,96370,114776,99815,87774,115096,120797,148365,157079,163806,147932,110292,98411,93281,118931
21,목포시,231823,8027,12321,11959,13942,15767,12599,11572,17328,18198,20564,18906,18267,16284,11378,9708,7566,7437
22,여수시,286094,9764,12342,12362,15581,18772,16724,14600,18969,19585,23875,24231,25145,22358,16584,13163,10468,11571
23,순천시,281285,10526,13715,14252,17065,20192,17138,14765,19153,19794,24325,25115,24154,18919,12571,9927,8517,11157
24,나주시,116135,4978,5410,4620,4791,6193,6960,6853,8557,8172,8352,8318,9156,8716,6367,5772,5685,7235
25,광양시,158579,6408,8030,7741,9537,11893,10189,8879,11335,11479,14114,16414,13393,9815,6162,4373,3615,5202
26,담양군,47305,1149,1285,1323,1808,2978,2505,1915,2196,2274,3276,3781,4542,4361,3410,3124,3148,4230
27,곡성군,29091,517,703,853,1286,1593,1157,819,1078,1294,1977,2300,2774,2674,2122,2095,2267,3582
28,구례군,26724,507,744,902,1130,1293,1011,824,1118,1316,1909,2264,2593,2448,2010,1861,2057,2737
29,고흥군,65535,1202,1484,1778,2369,2742,2144,1818,2317,2756,3884,4709,6032,6535,5854,5636,5851,8424
30,보성군,41548,891,1052,1185,1590,1891,1422,1294,1582,1850,2584,3163,3747,3978,3369,3230,3529,5191
31,화순군,63395,1511,2151,2553,3537,3918,3214,2268,2913,3591,5150,5519,5814,5035,3747,3611,3894,4969
32,장흥군,39076,906,1202,1286,1751,1920,1574,1387,1798,1836,2594,3062,3559,3526,2791,2750,2818,4316
33,강진군,35576,887,1063,1204,1474,1715,1416,1240,1512,1640,2292,2659,3273,3350,2646,2663,2678,3864
34,해남군,71199,2203,2197,2484,3120,3458,2743,2606,3291,3724,4781,5552,6552,6659,5213,5091,5101,6424
35,영암군,58429,1913,2117,2104,2667,3232,3067,2937,3642,3652,4575,4915,5092,4461,3325,3157,3252,4321
36,무안군,81516,2817,4421,4336,4460,4718,3920,3835,5863,6077,6527,6209,6173,5565,4404,3981,3731,4479
37,함평군,33260,651,855,916,1282,1627,1377,1112,1273,1564,2158,2662,3084,3197,2536,2501,2765,3700
38,영광군,54252,1955,1834,1992,2404,2875,2617,2425,2764,3005,3846,4187,4703,4560,3633,3537,3629,4286
39,장성군,46639,1476,1630,1586,1902,2394,2763,1874,2424,2561,3353,3644,4162,3881,3014,2946,3058,3971
40,완도군,52023,1521,1840,1704,2093,2362,2193,2118,2789,2903,3523,3801,4671,4613,3675,3725,3826,4666
41,진도군,31478,815,990,1036,1302,1532,1408,1153,1457,1598,2064,2400,2850,2834,2209,2331,2496,3003
42,신안군,40599,798,943,909,1279,1711,1674,1480,1737,1928,2642,3268,4070,4163,3272,3229,3330,4166
43,제주,686146,27445,35299,34767,37691,43780,43156,38189,52102,52978,62869,58031,54102,45717,29187,24599,19860,26374
44,제주시,499746,20872,26662,26113,28693,33108,32679,28809,39039,39055,46098,42060,38297,31809,19817,16246,12994,17395
45,서귀포시,186400,6573,8637,8654,8998,10672,10477,9380,13063,13923,16771,15971,15805,13908,9370,8353,6866,8979
46,전주시,659157,23826,32669,33490,40811,49044,43949,37193,46962,49561,59522,55138,51592,42535,30154,23504,18107,21100

In [4]:
# 요양기관 현황
inf3 = pd.read_excel("03_시군구별 제3권-광주 전북 전남 제주_2019년.xlsx",sheet_name='90p심평원')

# 1. 3번 행을 칼럼명으로 변경
inf3.columns = inf3.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf3 = inf3.drop(index=[0, 1, 2, 3, 4])

# 3. 46, 47, 48번 행 삭제
inf3 = inf3.drop(index=[53, 54, 55])

# 인덱스 리셋
inf3 = inf3.reset_index(drop=True)

inf3.columns = [col.split('\n')[0] for col in inf3.columns]

inf3 = inf3.drop(columns = [ "조  산  원", "Division"])
inf3

# 전주시 관련 행 필터링 및 합계 계산
jeonju =[ '전주시완산구             ','전주시덕진구             ']
jeonju_data = inf3[inf3['구      분'].isin(jeonju)].iloc[:, 1:].sum()

# 새로운 전주시 행 생성
jeonju_row = pd.DataFrame([['전주시'] + jeonju_data.tolist()], columns=inf3.columns)

# 전주시 행 추가 및 기존 구 삭제
inf3 = pd.concat([inf3[~inf3['구      분'].isin(jeonju)], jeonju_row], ignore_index=True)
inf3 = inf3.rename(columns={'구      분': '지역'})

# 예시: 'col1', 'col2', 'col3'의 값을 합쳐 'new_col' 생성
inf3['보건소'] = inf3[['보  건  소', '보건지소','보건진료소', '보건의료원']].sum(axis=1)

inf3 = inf3.drop(columns = [  '보  건  소', '보건지소','보건진료소', '보건의료원'])

inf3 = inf3.rename(columns={'구      분': '지역'})

inf3['지역'] = inf3['지역'] + ' ' + inf3.groupby('지역').cumcount().replace(0, '').astype(str)

inf3

,지역,계,상급종합병원,종합병원,병 원,요양병원,의 원,치과병원,치과의원,한방병원,한 의 원,약 국,보건소
0,광주,2852,2,21,80,66,948,14,625,85,323,672,16
1,동구,327,2,1,6,10,113,1,56,6,34,97,1
2,서구,676,0,5,19,11,250,9,144,18,87,131,2
3,남구,427,0,3,15,9,128,0,103,17,45,104,3
4,북구,782,0,6,22,19,251,1,183,26,85,188,1
5,광산구,640,0,6,18,17,206,3,139,18,72,152,9
6,전북,3774,2,11,74,83,1165,3,588,30,505,908,405
7,군산시,494,0,2,6,9,159,0,77,2,74,131,34
8,익산시,556,1,1,7,11,174,1,95,5,78,143,40
9,정읍시,256,0,1,4,5,76,0,34,1,32,61,42
10,남원시,186,0,1,2,4,58,0,21,0,21,39,40
11,김제시,188,0,0,8,4,51,0,19,1,19,46,40
12,완주군,170,0,0,4,6,50,0,18,0,24,38,30
13,진안군,54,0,0,2,0,11,0,4,0,5,9,23
14,무주군,53,0,0,0,0,12,0,5,0,8,13,15
15,장수군,44,0,0,0,0,8,0,5,0,4,10,17
16,임실군,79,0,0,1,1,16,0,6,0,8,15,32
17,순창군,72,0,0,1,1,17,0,6,0,6,13,28
18,고창군,123,0,1,1,5,31,0,13,0,11,24,37
19,부안군,118,0,1,5,2,26,0,15,0,17,29,23
20,전남,3389,1,22,78,90,944,7,482,25,373,803,563
21,목포시,406,0,5,16,7,135,2,63,9,48,118,2
22,여수시,471,0,3,7,11,153,2,79,2,55,118,41
23,순천시,452,0,5,17,7,134,1,89,5,53,109,32
24,나주시,214,0,1,4,10,61,0,34,3,25,47,29
25,광양시,210,0,1,4,5,62,0,40,1,25,49,23
26,담양군,98,0,0,2,7,22,0,12,1,10,21,23
27,곡성군,70,0,0,1,2,14,0,9,0,5,15,24
28,구례군,57,0,0,1,3,10,0,5,0,7,11,20
29,고흥군,141,0,1,3,1,32,0,12,0,17,32,43
30,보성군,98,0,0,2,4,23,0,9,0,9,25,26
31,화순군,132,1,0,3,14,31,0,16,1,11,29,26
32,장흥군,80,0,1,1,1,23,0,8,1,10,15,20
33,강진군,71,0,0,2,1,20,0,6,0,7,17,18
34,해남군,135,0,2,2,2,36,0,16,0,10,35,32
35,영암군,100,0,0,2,2,23,0,13,0,14,22,24
36,무안군,141,0,1,2,4,44,1,17,2,16,34,20
37,함평군,76,0,0,2,2,15,1,8,0,7,16,25
38,영광군,116,0,2,0,2,34,0,15,0,13,29,21
39,장성군,80,0,0,2,2,19,0,9,0,10,17,21
40,완도군,96,0,0,1,0,25,0,10,0,9,20,31
41,진도군,68,0,0,2,1,16,0,7,0,7,13,22
42,신안군,77,0,0,2,2,12,0,5,0,5,11,40
43,제주,1245,0,6,7,10,448,1,218,0,193,297,64
44,제주시,930,0,5,4,10,343,1,163,0,143,228,32
45,서귀포시,315,0,1,3,0,105,0,55,0,50,69,32
46,전주시,1381,1,4,33,35,476,2,270,21,198,337,4

In [5]:
# 의료인력현황
inf4 = pd.read_excel("03_시군구별 제3권-광주 전북 전남 제주_2019년.xlsx",sheet_name='92p')

# 1. 3번 행을 칼럼명으로 변경
inf4.columns = inf4.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf4 = inf4.drop(index=[0, 1, 2, 3, 4, 5])

# 3. 46, 47, 48번 행 삭제
inf4 = inf4.drop(index=[54, 55, 56])

# 인덱스 리셋
inf4 = inf4.reset_index(drop=True)
inf4 = inf4.loc[:, ~inf4.columns.isna()]

inf4.columns = [col.split('\n')[0] for col in inf4.columns]
inf4.columns = [col.split('physical')[0] for col in inf4.columns]
inf4 = inf4.drop(columns = [ "Division"])

# 전주시 관련 행 필터링 및 합계 계산
jeonju =[ '전주시완산구             ','전주시덕진구             ']
jeonju_data = inf4[inf4['구   분'].isin(jeonju)].iloc[:, 1:].sum()

# 새로운 전주시 행 생성
jeonju_row = pd.DataFrame([['전주시'] + jeonju_data.tolist()], columns=inf4.columns)

# 전주시 행 추가 및 기존 구 삭제
inf4 = pd.concat([inf4[~inf4['구   분'].isin(jeonju)], jeonju_row], ignore_index=True)
inf4 = inf4.rename(columns={'구   분': '지역'})

inf4['지역'] = inf4['지역'] + ' ' + inf4.groupby('지역').cumcount().replace(0, '').astype(str)

inf4

,지역,계,의 사,치 과 의 사,한 의 사,간호사,약 사,물리치료사,작업치료사,사회복지사
0,광주,17835,3658,1009,723,8949,1276,1734,309,177
1,동구,3895,1005,171,62,2262,202,142,21,30
2,서구,3139,681,209,189,1390,242,334,56,38
3,남구,2796,496,127,141,1461,189,299,60,23
4,북구,4106,747,294,178,1827,333,565,111,51
5,광산구,3899,729,208,153,2009,310,394,61,35
6,전북,16821,3689,917,934,7652,1427,1730,287,185
7,군산시,2018,405,115,118,873,193,239,57,18
8,익산시,3043,654,179,141,1463,233,283,63,27
9,정읍시,746,157,41,58,311,86,81,4,8
10,남원시,634,140,28,40,257,65,88,5,11
11,김제시,602,135,21,35,242,63,78,11,17
12,완주군,510,115,24,44,200,53,61,0,13
13,진안군,149,38,7,16,58,13,16,0,1
14,무주군,107,28,8,12,31,13,15,0,0
15,장수군,82,23,7,11,26,11,4,0,0
16,임실군,154,42,9,12,47,19,24,0,1
17,순창군,193,47,8,18,76,18,24,0,2
18,고창군,407,83,19,25,192,36,44,2,6
19,부안군,355,81,20,26,136,37,50,3,2
20,전남,16775,3128,767,830,8539,1304,1829,165,213
21,목포시,2992,483,122,114,1703,211,314,24,21
22,여수시,2136,400,117,98,977,187,313,25,19
23,순천시,3349,523,134,99,1957,209,325,75,27
24,나주시,969,195,46,66,448,84,90,8,32
25,광양시,807,133,52,45,394,77,91,7,8
26,담양군,367,68,17,26,164,33,47,0,12
27,곡성군,180,39,13,16,65,17,26,1,3
28,구례군,189,38,9,20,76,18,26,0,2
29,고흥군,416,90,17,35,184,43,41,0,6
30,보성군,353,66,13,27,172,32,32,1,10
31,화순군,1640,372,25,40,1005,84,81,11,22
32,장흥군,244,53,15,24,99,22,29,0,2
33,강진군,237,55,15,15,109,23,18,0,2
34,해남군,570,118,21,17,271,53,72,8,10
35,영암군,243,48,16,26,76,28,43,0,6
36,무안군,538,106,37,34,212,52,85,3,9
37,함평군,242,55,15,19,96,19,36,0,2
38,영광군,475,96,22,23,243,41,40,0,10
39,장성군,237,47,11,21,93,22,35,2,6
40,완도군,225,59,19,22,71,22,32,0,0
41,진도군,145,36,11,16,41,15,26,0,0
42,신안군,221,48,20,27,83,12,27,0,4
43,제주,5575,1175,281,238,2738,477,544,86,36
44,제주시,4579,993,215,177,2349,371,385,57,32
45,서귀포시,996,182,66,61,389,106,159,29,4
46,전주시,7821,1741,431,378,3740,587,723,142,79

In [6]:
#주요시설현황
inf5 = pd.read_excel("03_시군구별 제3권-광주 전북 전남 제주_2019년.xlsx",sheet_name='94p')

# 1. 3번 행을 칼럼명으로 변경
inf5.columns = inf5.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf5 = inf5.drop(index=[0, 1, 2, 3, 4, 5, 6])

# 3. 46, 47, 48번 행 삭제
inf5 = inf5.drop(index=[55, 56, 57])

# 인덱스 리셋
inf5 = inf5.reset_index(drop=True)

inf5.iloc[:, [3, 4]] = inf5.iloc[:, [4, 3]].values
inf5.iloc[:, [15, 16]] = inf5.iloc[:, [16, 15]].values

inf5 = inf5.loc[:, ~inf5.columns.isna()]

inf5.columns = [col.split('\n')[0] for col in inf5.columns]
inf5.columns = [col.split(' Inpatient room')[0] for col in inf5.columns]
inf5.columns = [col.split('Intensive Care Unit')[0] for col in inf5.columns]
inf5 = inf5.drop(columns =  [ '계',  '정신과폐쇄',
'격리병실                           Isolation room', '무균치료실                   Aseptic room', "Division"])

# 전주시 관련 행 필터링 및 합계 계산
jeonju =[ '전주시완산구             ','전주시덕진구             ']
jeonju_data = inf5[inf5['구   분'].isin(jeonju)].iloc[:, 1:].sum()

# 새로운 전주시 행 생성
jeonju_row = pd.DataFrame([['전주시'] + jeonju_data.tolist()], columns=inf5.columns)

# 전주시 행 추가 및 기존 구 삭제
inf5 = pd.concat([inf5[~inf5['구   분'].isin(jeonju)], jeonju_row], ignore_index=True)
inf5 = inf5.rename(columns={'구   분': '지역'})

inf5['지역'] = inf5['지역'] + ' ' + inf5.groupby('지역').cumcount().replace(0, '').astype(str)

inf5.columns

Index(['지역', '일반입원실 ', '중환자실  '], dtype='object')

In [7]:
# 의료장비 현황
inf6 = pd.read_excel("03_시군구별 제3권-광주 전북 전남 제주_2019년.xlsx",sheet_name='96p')

# 1. 3번 행을 칼럼명으로 변경
inf6.columns = inf6.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf6 = inf6.drop(index=[0, 1, 2, 3, 4])

# 3. 46, 47, 48번 행 삭제
inf6 = inf6.drop(index=[53, 54, 55])

# 인덱스 리셋
inf6 = inf6.reset_index(drop=True)

inf6.columns = [col.split('\n')[0] for col in inf6.columns]
inf6.columns = [col.split(' Inpatient room')[0] for col in inf6.columns]
inf6.columns = [col.split('Intensive Care Unit')[0] for col in inf6.columns]
inf6 = inf6.drop(columns = [  '계', '유         방',
       '양전자 방사                                 단층 촬영                            PET',
       '체외충격파쇄석기     Extracorporead', '혈관조영장치', '혈관조영장치', 'Division'])

# 전주시 관련 행 필터링 및 합계 계산
jeonju =[ '전주시완산구             ','전주시덕진구             ']
jeonju_data = inf6[inf6['구   분'].isin(jeonju)].iloc[:, 1:].sum()

# 새로운 전주시 행 생성
jeonju_row = pd.DataFrame([['전주시'] + jeonju_data.tolist()], columns=inf6.columns)

# 전주시 행 추가 및 기존 구 삭제
inf6 = pd.concat([inf6[~inf6['구   분'].isin(jeonju)], jeonju_row], ignore_index=True)
inf6 = inf6.rename(columns={'구   분': '지역'})

inf6['지역'] = inf6['지역'] + ' ' + inf6.groupby('지역').cumcount().replace(0, '').astype(str)

inf6

                         지역 자기공명영상기 전산화단층촬영장치   초음파
0                       광주       74        80  1185
1    동구                           8        13   182
2    서구                          22        21   265
3    남구                           9        10   170
4    북구                          16        18   301
5     광산구                        19        18   267
6                       전북       62        97  1211
7   군산시                           9        11   155
8   익산시                           8        15   209
9   정읍시                           2         5    63
10  남원시                           2         3    56
11  김제시                           3         7    48
12  완주군                         NaN         1    35
13  진안군                           1         1    16
14  무주군                         NaN         1     7
15  장수군                         NaN       NaN     8
16  임실군                         NaN         1    13
17  순창군                         NaN         1    11
18  고창군                           2         2    21
19  부안군                           2         4    24
20                      전남       67        97  1064
21  목포시                          12        21   183
22  여수시                          10        10   170
23  순천시                          17        18   216
24  나주시                           2         4    49
25  광양시                           4         4    62
26  담양군                         NaN         2    21
27  곡성군                         NaN         1    14
28  구례군                         NaN         1    15
29  고흥군                           3         3    30
30  보성군                         NaN         2    22
31  화순군                           7         9    65
32  장흥군                           2         3    22
33  강진군                           1         2    18
34  해남군                           3         4    40
35  영암군                         NaN         1    12
36  무안군                           2         3    38
37  함평군                           1         2    10
38  영광군                           2         2    28
39  장성군                           1         2    16
40  완도군                         NaN         1    15
41  진도군                         NaN         1     6
42  신안군                         NaN         1    12
43                      제주       10        15   411
44            제주시                 9        13   329
45             서귀포시               1         2    82
46                     전주시       33        45   545

In [8]:
# 진료실적현황
inf7 = pd.read_excel("03_시군구별 제3권-광주 전북 전남 제주_2019년.xlsx",sheet_name='118p')

# 1. 3번 행을 칼럼명으로 변경
inf7.columns = inf7.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf7 = inf7.drop(index=[0, 1, 2, 3, 4, 5, 6, 7])

# 56,57번 행 삭제
inf7 = inf7.drop(index=[56, 57])

# 인덱스 리셋
inf7 = inf7.reset_index(drop=True)

inf7 = inf7.loc[:, ~inf7.columns.isna()]

inf7.columns = [col.split('\n')[0] for col in inf7.columns]
inf7 = inf7.drop(columns = ['내원일수', '급여일수',
       '진료실인원당     Per Patient', '내원1일당  Per Visit ',
       '급여1일당  Per reimbursed day', 'Division'])


# 전주시 관련 행 필터링 및 합계 계산
jeonju =[ '전주시완산구             ','전주시덕진구             ']
jeonju_data = inf7[inf7['구 분'].isin(jeonju)].iloc[:, 1:].sum()

# 새로운 전주시 행 생성
jeonju_row = pd.DataFrame([['전주시'] + jeonju_data.tolist()], columns=inf7.columns)

# 전주시 행 추가 및 기존 구 삭제
inf7 = pd.concat([inf7[~inf7['구 분'].isin(jeonju)], jeonju_row], ignore_index=True)
inf7 = inf7.rename(columns={'구 분': '지역'})

inf7['지역'] = inf7['지역'] + ' ' + inf7.groupby('지역').cumcount().replace(0, '').astype(str)

inf7

                         지역    진료실인원                진료비             급여비
0                       광주   1391896      2820451155.79  2186377062.098
1    동구                        92949       223787232.51   175054503.482
2    서구                       286684       573460847.41   442767025.515
3    남구                       207626       449452064.61   347834409.375
4    북구                       412750       871168475.46   679587608.672
5     광산구                     391887        702582535.8   541133515.054
6                       전북   1749441      4096643466.93   3212230898.82
7   군산시                       259590       554985782.18   435952469.532
8   익산시                       276015       614863781.69   483397875.484
9   정읍시                       106475        291731649.8   231566753.082
10  남원시                        78857       208918833.81   165337305.877
11  김제시                        81671       255525177.08   204725702.375
12  완주군                        89671       222859007.84   174171722.157
13  진안군                        25047        76046054.49    59812318.608
14  무주군                        23583        66004501.11    51847318.986
15  장수군                        21795        64450367.18      50389977.2
16  임실군                        28165         88080300.5    68888438.192
17  순창군                        27623        90879096.06    70710393.107
18  고창군                        53913       166961479.68   131185308.098
19  부안군                        51711       167059932.68    131446830.17
20                      전남   1802263  4504670853.990001  3518240430.374
21  목포시                       219605       523028117.98   410965969.096
22  여수시                       271179        608957872.9   474084930.881
23  순천시                       266751       535694135.67   415185944.888
24  나주시                       111075        278880732.3   217754341.803
25  광양시                       149960       253112113.25   194885645.384
26  담양군                        45102       126541901.76    98854761.035
27  곡성군                        27933         84171659.2    65584483.563
28  구례군                        25594        73333371.07    57456730.331
29  고흥군                        63064       204960930.17   162153322.201
30  보성군                        39733       124380085.43    97326583.132
31  화순군                        60445       170914650.47   133206298.117
32  장흥군                        37421       109008433.92    85229384.826
33  강진군                        34217       108078047.75    85216614.753
34  해남군                        68442       206150162.37    162156984.66
35  영암군                        55649       144618887.33   112593436.108
36  무안군                        78818       197880945.14   154677834.915
37  함평군                        31966       100961400.41    78570853.038
38  영광군                        52254       163124285.95   128063998.194
39  장성군                        44636       125365603.85    98051445.354
40  완도군                        49638       145305646.29   114100044.147
41  진도군                        29856        91059099.85    71469725.012
42  신안군                        38925       129142770.93   100651098.936
43                      제주    641778      1161521209.38    904728998.92
44            제주시             467631       807194345.81   627656539.771
45             서귀포시           174147       354326863.57   277072459.149
46                     전주시    625325      1228277502.83   952798485.952

In [9]:
# 진료실적 관내
inf8 = pd.read_excel("03_시군구별 제3권-광주 전북 전남 제주_2019년.xlsx",sheet_name='128p')


# 1. 3번 행을 칼럼명으로 변경
inf8.columns = inf8.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf8 = inf8.drop(index=[0, 1, 2, 3, 4, 5, 6, 7])

# 3. 46, 47, 48번 행 삭제
inf8 = inf8.drop(index=[56, 57])

# 인덱스 리셋
inf8 = inf8.reset_index(drop=True)

inf8 = inf8.loc[:, ~inf8.columns.isna()]

inf8.columns = [col.split('\n')[0] for col in inf8.columns]
inf8 = inf8.drop(columns = ['내원일수', '급여일수',
       '진료실인원당     Per Patient', '내원1일당  Per Visit ',
       '급여1일당  Per reimbursed day', 'Division'])

# 전주시 관련 행 필터링 및 합계 계산
jeonju =[ '전주시완산구             ','전주시덕진구             ']
jeonju_data = inf8[inf8['구 분'].isin(jeonju)].iloc[:, 1:].sum()

# 새로운 전주시 행 생성
jeonju_row = pd.DataFrame([['전주시'] + jeonju_data.tolist()], columns=inf8.columns)

# 전주시 행 추가 및 기존 구 삭제
inf8 = pd.concat([inf8[~inf8['구 분'].isin(jeonju)], jeonju_row], ignore_index=True)
inf8 = inf8.rename(columns={'구 분': '지역'})

inf8['지역'] = inf8['지역'] + ' ' + inf8.groupby('지역').cumcount().replace(0, '').astype(str)

inf8

                         지역    진료실인원            진료비                급여비
0                       광주   1351058  2379347705.33     1819159415.155
1    동구                        73499    96641527.13       75417685.176
2    서구                       253597   241093687.76      181858011.135
3    남구                       177003   189214642.04      143938515.461
4    북구                       364479   419891784.94      323144131.948
5     광산구                     357705   387310853.63      292088399.305
6                       전북   1678061  3426809582.28  2674202603.868999
7   군산시                       243962   367868647.42      285151273.069
8   익산시                       256862    466299507.4      363653945.664
9   정읍시                        95780    155319547.7      122368648.542
10  남원시                        71607   117758062.96       92460136.747
11  김제시                        66025   116039239.43       94042197.022
12  완주군                        62212    50315660.77       39639146.792
13  진안군                        18281    19928707.97       15512351.435
14  무주군                        19496    16015691.77       12375314.409
15  장수군                        16457    12981546.01       10097425.813
16  임실군                        19956    21217691.47       16555884.414
17  순창군                        21324    30261927.44       23436487.344
18  고창군                        45583    74095132.55       57999110.073
19  부안군                        44384    84892844.28       66075222.832
20                      전남   1649485  3024255011.56      2361856362.45
21  목포시                       205759   374956624.97      291555768.865
22  여수시                       253868   400572449.34      305839480.404
23  순천시                       251109   374526467.09      285619867.215
24  나주시                        90721    118862708.7       92631613.012
25  광양시                       127596   103362504.14       77397376.165
26  담양군                        31479     35520103.7       28148082.755
27  곡성군                        21393    23493711.55       18379005.543
28  구례군                        20255     28477494.9       22309276.991
29  고흥군                        53477    86253163.76       68068047.734
30  보성군                        31574     43198338.9       33662080.087
31  화순군                        49700    89591392.72       70577148.883
32  장흥군                        31408    45138078.76        34946484.18
33  강진군                        28679    45563392.88       35833177.396
34  해남군                        58504    101718802.6       79800760.419
35  영암군                        40300    34519060.14       27300374.461
36  무안군                        63141    68248971.93       53686202.584
37  함평군                        23608    26225017.13       20504188.658
38  영광군                        44172    87228433.14       68212319.547
39  장성군                        30252    37429325.66       29609670.681
40  완도군                        41614    36063213.87       28160609.027
41  진도군                        24281    24649587.67       19245547.492
42  신안군                        25372    19620325.08        15339271.87
43                      제주    613534   968058136.77      748621855.444
44            제주시             447039   667458162.22      514965899.353
45             서귀포시           150744   161223329.68      124518956.989
46                     전주시    568668   752084469.82      578135726.314

In [10]:
# 관외
inf9 = pd.read_excel("03_시군구별 제3권-광주 전북 전남 제주_2019년.xlsx",sheet_name='134p')

# 1. 3번 행을 칼럼명으로 변경
inf9.columns = inf9.iloc[3]

# 2. 0, 1, 2, 4번 행 삭제
inf9 = inf9.drop(index=[0, 1, 2, 3, 4, 5, 6, 7])

# 3. 46, 47, 48번 행 삭제
inf9 = inf9.drop(index=[56, 57])
inf9

# 인덱스 리셋
inf9 = inf9.reset_index(drop=True)

inf9 = inf9.loc[:, ~inf9.columns.isna()]


inf9.columns = [col.split('\n')[0] for col in inf9.columns]
inf9 = inf9.drop(columns = ['내원일수', '급여일수',
       '진료실인원당     Per Patient', '내원1일당  Per Visit ',
       '급여1일당  Per reimbursed day', 'Division'])

# 전주시 관련 행 필터링 및 합계 계산
jeonju =[ '전주시완산구             ','전주시덕진구             ']
jeonju_data = inf9[inf9['구 분'].isin(jeonju)].iloc[:, 1:].sum()

# 새로운 전주시 행 생성
jeonju_row = pd.DataFrame([['전주시'] + jeonju_data.tolist()], columns=inf9.columns)

# 전주시 행 추가 및 기존 구 삭제
inf9 = pd.concat([inf9[~inf9['구 분'].isin(jeonju)], jeonju_row], ignore_index=True)
inf9 = inf9.rename(columns={'구 분': '지역'})

inf9['지역'] = inf9['지역'] + ' ' + inf9.groupby('지역').cumcount().replace(0, '').astype(str)

inf9

                         지역   진료실인원            진료비             급여비
0                       광주   322314   441103450.46   367217646.943
1    동구                       79029   127145705.38    99636818.306
2    서구                      205470   332367159.65    260909014.38
3    남구                      158932   260237422.57   203895893.914
4    북구                      289860   451276690.52   356443476.724
5     광산구                    233307   315271682.17   249045115.749
6                       전북   412199   669833884.65   538028294.951
7   군산시                      107002   187117134.76   150801196.463
8   익산시                      103802   148564274.29    119743929.82
9   정읍시                       62075    136412102.1    109198104.54
10  남원시                       43852    91160770.85     72877169.13
11  김제시                       57802   139485937.65   110683505.353
12  완주군                       80333   172543347.07   134532575.365
13  진안군                       21473    56117346.52    44299967.173
14  무주군                       19660    49988809.34    39472004.577
15  장수군                       19390    51468821.17    40292551.387
16  임실군                       24826    66862609.03    52332553.778
17  순창군                       23193    60617168.62    47273905.763
18  고창군                       38989    92866347.13    73186198.025
19  부안군                       34688     82167088.4    65371607.338
20                      전남   782058  1480415842.43  1156384067.924
21  목포시                      103657   148071493.01   119410200.231
22  여수시                      114000   208385423.56   168245450.477
23  순천시                      108144   161167668.58   129566077.673
24  나주시                       82286    160018023.6   125122728.791
25  광양시                      100260   149749609.11   117488269.219
26  담양군                       38149    91021798.06     70706678.28
27  곡성군                       24250    60677947.65     47205478.02
28  구례군                       21109    44855876.17     35147453.34
29  고흥군                       45654   118707766.41    94085274.467
30  보성군                       32213    81181746.53    63664503.045
31  화순군                       43020    81323257.75    62629149.234
32  장흥군                       28053    63870355.16    50282900.646
33  강진군                       25310    62514654.87    49383437.357
34  해남군                       44961   104431359.77    82356224.241
35  영암군                       49521   110099827.19    85293061.647
36  무안군                       65385   129631973.21   100991632.331
37  함평군                       28376    74736383.28     58066664.38
38  영광군                       34570    75895852.81    59851678.647
39  장성군                       38498    87936278.19    68441774.673
40  완도군                       42019   109242432.42     85939435.12
41  진도군                       25188    66409512.18     52224177.52
42  신안군                       36260   109522445.85    85311827.066
43                      제주   137347   193463072.61   156107143.476
44            제주시            111077   139736183.59   112690640.418
45             서귀포시          112288   193103533.89    152553502.16
46                     전주시   393555   476193033.01   374662759.638

In [11]:
dataframes = [inf, inf2, inf3, inf4, inf5, inf6, inf7, inf8, inf9]  # inf4~inf9를 추가하세요

# 순차적으로 merge 진행
merged_df = dataframes[0]
for df in dataframes[1:]:
    merged_df = pd.merge(merged_df, df, on='지역')

merged_df = merged_df.drop_duplicates(subset='지역', keep='first')

merged_df

,지역,의료보장,근 로 자,공ㆍ교,지 역,의료급여 1종,의료급여 2종,계_x,0-4세,5-9세,...,초음파,진료실인원_x,진료비_x,급여비_x,진료실인원_y,진료비_y,급여비_y,진료실인원,진료비,급여비
0,광주,1472535,900866,141552,366687,40646,22784,1472535,54358,72968,...,1185,1391896,2820451155.79,2186377062.098,1351058,2379347705.33,1819159415.155,322314,441103450.46,367217646.943
1,동구,98872,54224,11494,27146,4141,1867,98872,3195,3478,...,182,92949,223787232.51,175054503.482,73499,96641527.13,75417685.176,79029,127145705.38,99636818.306
2,서구,303357,184831,30815,74963,8159,4589,303357,9829,13708,...,265,286684,573460847.41,442767025.515,253597,241093687.76,181858011.135,205470,332367159.65,260909014.38
3,남구,218884,128640,25974,54731,6110,3429,218884,7493,10860,...,170,207626,449452064.61,347834409.375,177003,189214642.04,143938515.461,158932,260237422.57,203895893.914
4,북구,436493,259429,42036,113714,13816,7498,436493,15629,19673,...,301,412750,871168475.46,679587608.672,364479,419891784.94,323144131.948,289860,451276690.52,356443476.724
5,광산구,414929,273742,31233,96133,8420,5401,414929,18212,25249,...,267,391887,702582535.8,541133515.054,357705,387310853.63,292088399.305,233307,315271682.17,249045115.749
6,전북,1837478,1048946,194740,508751,60362,24679,1837478,57825,79732,...,1211,1749441,4096643466.93,3212230898.82,1678061,3426809582.28,2674202603.868999,412199,669833884.65,538028294.951
7,군산시,273214,163835,22011,75141,8920,3307,273214,9305,13339,...,155,259590,554985782.18,435952469.532,243962,367868647.42,285151273.069,107002,187117134.76,150801196.463
8,익산시,290541,169903,26017,79827,10782,4012,290541,8813,12184,...,209,276015,614863781.69,483397875.484,256862,466299507.4,363653945.664,103802,148564274.29,119743929.82
9,정읍시,111951,58367,11896,35142,4825,1721,111951,2839,4087,...,63,106475,291731649.8,231566753.082,95780,155319547.7,122368648.542,62075,136412102.1,109198104.54
10,남원시,82450,43032,9015,25429,3477,1497,82450,2280,3035,...,56,78857,208918833.81,165337305.877,71607,117758062.96,92460136.747,43852,91160770.85,72877169.13
11,김제시,85252,44692,8427,25988,4691,1454,85252,1912,2818,...,48,81671,255525177.08,204725702.375,66025,116039239.43,94042197.022,57802,139485937.65,110683505.353
12,완주군,93982,54798,8423,26508,3224,1029,93982,3219,4428,...,35,89671,222859007.84,174171722.157,62212,50315660.77,39639146.792,80333,172543347.07,134532575.365
13,진안군,25949,12797,3536,8380,1024,212,25949,672,732,...,16,25047,76046054.49,59812318.608,18281,19928707.97,15512351.435,21473,56117346.52,44299967.173
14,무주군,24509,12660,2730,8019,849,251,24509,496,782,...,7,23583,66004501.11,51847318.986,19496,16015691.77,12375314.409,19660,49988809.34,39472004.577
15,장수군,22736,11164,3096,7323,824,329,22736,479,762,...,8,21795,64450367.18,50389977.2,16457,12981546.01,10097425.813,19390,51468821.17,40292551.387
16,임실군,29147,14757,4042,8898,1087,363,29147,744,781,...,13,28165,88080300.5,68888438.192,19956,21217691.47,16555884.414,24826,66862609.03,52332553.778
17,순창군,28669,14403,3896,9109,911,350,28669,867,818,...,11,27623,90879096.06,70710393.107,21324,30261927.44,23436487.344,23193,60617168.62,47273905.763
18,고창군,56156,27641,5845,19987,2178,505,56156,1188,1712,...,21,53913,166961479.68,131185308.098,45583,74095132.55,57999110.073,38989,92866347.13,73186198.025
19,부안군,53765,25734,6104,19265,2136,526,53765,1185,1585,...,24,51711,167059932.68,131446830.17,44384,84892844.28,66075222.832,34688,82167088.4,65371607.338
20,전남,1891561,1050460,192587,576309,57034,15171,1891561,61422,78329,...,1064,1802263,4504670853.990001,3518240430.374,1649485,3024255011.56,2361856362.45,782058,1480415842.43,1156384067.924
21,목포시,231823,126602,24114,69724,8150,3233,231823,8027,12321,...,183,219605,523028117.98,410965969.096,205759,374956624.97,291555768.865,103657,148071493.01,119410200.231
22,여수시,286094,178852,20071,78249,7106,1816,286094,9764,12342,...,170,271179,608957872.9,474084930.881,253868,400572449.34,305839480.404,114000,208385423.56,168245450.477
23,순천시,281285,171230,30139,72991,5429,1496,281285,10526,13715,...,216,266751,535694135.67,415185944.888,251109,374526467.09,285619867.215,108144,161167668.58,129566077.673
24,나주시,116135,66046,12182,33507,3711,689,116135,4978,5410,...,49,111075,278880732.3,217754341.803,90721,118862708.7,92631613.012,82286,160018023.6,125122728.791
25,광양시,158579,108323,9603,37418,2331,904,158579,6408,8030,...,62,149960,253112113.25,194885645.384,127596,103362504.14,77397376.165,100260,149749609.11,117488269.219
26,담양군,47305,24164,6314,14884,1590,353,47305,1149,1285,...,21,45102,126541901.76,98854761.035,31479,35520103.7,28148082.755,38149,91021798.06,70706678.28
27,곡성군,29091,15045,3746,8726,1304,270,29091,517,703,...,14,27933,84171659.2,65584483.563,21393,23493711.55,18379005.543,24250,60677947.65,47205478.02
28,구례군,26724,13013,3572,8818,1010,311,26724,507,744,...,15,25594,73333371.07,57456730.331,20255,28477494.9,22309276.991,21109,44855876.17,35147453.34
29,고흥군,65535,30434,7037,24342,3200,522,65535,1202,1484,...,30,63064,204960930.17,162153322.201,53477,86253163.76,68068047.734,45654,118707766.41,94085274.467
30,보성군,41548,19839,4898,14669,1780,362,41548,891,1052,...,22,39733,124380085.43,97326583.132,31574,43198338.9,33662080.087,32213,81181746.53,63664503.045
31,화순군,63395,35438,6488,18728,2060,681,63395,1511,2151,...,65,60445,170914650.47,133206298.117,49700,89591392.72,70577148.883,43020,81323257.75,62629149.234
32,장흥군,39076,17969,5314,13602,1702,489,39076,906,1202,...,22,37421,109008433.92,85229384.826,31408,45138078.76,34946484.18,28053,63870355.16,50282900.646
33,강진군,35576,17348,4207,12099,1472,450,35576,887,1063,...,18,34217,108078047.75,85216614.753,28679,45563392.88,35833177.396,25310,62514654.87,49383437.357
34,해남군,71199,33314,7656,26875,2807,547,71199,2203,2197,...,40,68442,206150162.37,162156984.66,58504,101718802.6,79800760.419,44961,104431359.77,82356224.241
35,영암군,58429,32240,5145,19044,1621,379,58429,1913,2117,...,12,55649,144618887.33,112593436.108,40300,34519060.14,27300374.461,49521,110099827.19,85293061.647
36,무안군,81516,42971,11677,24633,1805,430,81516,2817,4421,...,38,78818,197880945.14,154677834.915,63141,68248971.93,53686202.584,65385,129631973.21,100991632.331
37,함평군,33260,16174,3935,11524,1346,281,33260,651,855,...,10,31966,100961400.41,78570853.038,23608,26225017.13,20504188.658,28376,74736383.28,58066664.38
38,영광군,54252,27839,5002,18609,2218,584,54252,1955,1834,...,28,52254,163124285.95,128063998.194,44172,87228433.14,68212319.547,34570,75895852.81,59851678.647
39,장성군,46639,23209,7475,13940,1662,353,46639,1476,1630,...,16,44636,125365603.85,98051445.354,30252,37429325.66,29609670.681,38498,87936278.19,68441774.673
40,완도군,52023,21153,5257,23541,1796,276,52023,1521,1840,...,15,49638,145305646.29,114100044.147,41614,36063213.87,28160609.027,42019,109242432.42,85939435.12
41,진도군,31478,12922,3891,12826,1395,444,31478,815,990,...,6,29856,91059099.85,71469725.012,24281,24649587.67,19245547.492,25188,66409512.18,52224177.52
42,신안군,40599,16335,4864,17560,1539,301,40599,798,943,...,12,38925,129142770.93,100651098.936,25372,19620325.08,15339271.87,36260,109522445.85,85311827.066
43,제주,686146,380854,67939,217695,13779,5879,686146,27445,35299,...,411,641778,1161521209.38,904728998.92,613534,968058136.77,748621855.444,137347,193463072.61,156107143.476
44,제주시,499746,284633,50692,150752,9382,4287,499746,20872,26662,...,329,467631,807194345.81,627656539.771,447039,667458162.22,514965899.353,111077,139736183.59,112690640.418
45,서귀포시,186400,96221,17247,66943,4397,1592,186400,6573,8637,...,82,174147,354326863.57,277072459.149,150744,161223329.68,124518956.989,112288,193103533.89,152553502.16
46,전주시,659157,395163,79702,159735,15434,9123,659157,23826,32669,...,545,625325,1228277502.83,952798485.952,568668,752084469.82,578135726.314,393555,476193033.01,374662759.638

In [12]:
file_path = "2019 전라 제주.csv"  # 저장할 파일 이름과 경로 설정
merged_df.to_csv(file_path, index=False, encoding='utf-8-sig')  # UTF-8 인코딩으로 저장